using System.Text.RegularExpressions;

namespace PQueirozOptimizer.Services;

/// <summary>Traduções do novo visual (cabeçalhos, busca, notificações) e de BIOS, NVIDIA, DDU, jogos e Defender.</summary>
public static partial class Translator
{
    private static readonly Dictionary<string, string> ExtrasExact = new(StringComparer.Ordinal)
    {
        // ---------- Cabeçalhos, busca e notificações ----------
        ["Saúde, desempenho e atividade do seu PC em tempo real."] = "Your PC's health, performance and activity in real time.",
        ["Ajustes revisados item por item, com backup e reversão."] = "Tweaks reviewed item by item, with backup and restore.",
        ["Programas, tarefas e serviços que iniciam com o Windows."] = "Apps, tasks and services that start with Windows.",
        ["Drivers oficiais, instalação limpa com DDU e utilitários."] = "Official drivers, clean install with DDU and utilities.",
        ["Imagens personalizadas do Windows."] = "Custom Windows images.",
        ["Atalhos e utilitários do dia a dia."] = "Everyday shortcuts and utilities.",
        ["Tudo o que foi feito e como desfazer."] = "Everything that was done and how to undo it.",
        ["Sessão de jogo, perfis, NVIDIA, configurações dos jogos e Defender."] = "Game session, profiles, NVIDIA, game settings and Defender.",
        ["Velocidade, DNS, latência e reparos de conexão."] = "Speed, DNS, latency and connection repairs.",
        ["Perfis, tema, idioma, licença e atualizações."] = "Profiles, theme, language, license and updates.",
        ["Editor de BIOS pelo SCEWIN e ajustes recomendados."] = "BIOS editor via SCEWIN and recommended settings.",
        ["Novidades de cada versão."] = "What's new in each version.",
        ["Sobre o PQueiroz Optimizer."] = "About PQueiroz Optimizer.",
        ["Buscar recursos, ajustes e páginas…"] = "Search features, tweaks and pages…",
        ["Nada encontrado."] = "Nothing found.", ["Monitorar"] = "Monitor", ["Jogos e Rede"] = "Gaming & Network", ["Sistema"] = "System",
        ["Debloat e privacidade"] = "Debloat & privacy", ["Diagnóstico do PC"] = "PC diagnostics", ["Limpeza rápida"] = "Quick clean",
        ["Versão Padrão"] = "Standard Version", ["Editor de BIOS"] = "BIOS editor",
        ["Jogos"] = "Games", ["NVIDIA"] = "NVIDIA",

        // ---------- Patch notes ----------
        ["Editor de BIOS pelo SCEWIN (BIOS AMI): leitura de todas as configurações, busca, recomendações seguras (Above 4G, Resizable BAR, Spread Spectrum), gravação só do que mudou e restauração da cópia original."] = "BIOS editor via SCEWIN (AMI BIOS): reads every setting, search, safe recommendations (Above 4G, Resizable BAR, Spread Spectrum), writes only what changed and restores the original copy.",
        ["Perfil NVIDIA para jogos gravado direto no driver (gerenciamento de energia, baixa latência, filtragem de textura, otimização segmentada, V-Sync e cache de sombreador), com restauração."] = "NVIDIA gaming profile written straight to the driver (power management, low latency, texture filtering, threaded optimization, V-Sync and shader cache), with restore.",
        ["Instalação limpa de driver com o DDU: ponto de restauração, remoção do driver atual, reinício e o instalador novo abre sozinho no próximo logon."] = "Clean driver install with DDU: restore point, removal of the current driver, restart, and the new installer opens by itself at the next sign-in.",
        ["Configurações dos jogos: presets competitivos para Fortnite, Apex Legends, Counter-Strike 2 e Rocket League, com cópia do arquivo original."] = "Game settings: competitive presets for Fortnite, Apex Legends, Counter-Strike 2 and Rocket League, with a copy of the original file.",
        ["Windows Defender: exclusão das pastas dos jogos e liga/desliga da proteção em tempo real."] = "Windows Defender: game folder exclusions and real-time protection on/off.",
        ["Visual novo: fundo aurora animado, cartões de vidro com borda em gradiente que sobem ao passar o mouse, botões com brilho, interruptores, abas, entrada em cascata e anel de saúde animado."] = "New look: animated aurora background, glass cards with gradient borders that lift on hover, glowing buttons, switches, tabs, cascading entrance and an animated health ring.",
        ["Ao ligar a janela translúcida, o app agora liga também os efeitos de transparência do Windows, avisando antes que a mudança vale para o sistema todo."] = "Turning on the translucent window now also turns on Windows transparency effects, with a warning first that the change applies system-wide.",
        ["Dois temas novos: Areia, claro e com tom quente, menos ofuscante que o Claro; e Ameixa, escuro com tom vinho."] = "Two new themes: Sand, a warm light theme that is easier on the eyes than Light; and Plum, a dark theme with a wine tone.",
        ["Janela translúcida: quando os efeitos de transparência do Windows estão desligados, Configurações → Aparência avisa e abre a opção certa; ao ligá-los, o app fica translúcido na hora."] = "Translucent window: when Windows transparency effects are off, Settings → Appearance tells you and opens the right option; once they are on, the app turns translucent right away.",
        ["O tema Automático agora acompanha a troca de claro/escuro do Windows sem precisar reabrir o app."] = "The Automatic theme now follows Windows light/dark changes without reopening the app.",
        ["Visual mais limpo: saíram os gradientes, os brilhos e o fundo animado, e os cartões ficaram planos, sem sombra e sem subir ao passar o mouse."] = "Cleaner look: gradients, glows and the animated background are gone, and cards are now flat, without shadows or lifting on hover.",
        ["Ícones novos e exclusivos para cada otimização; SFC, DISM, CHKDSK e Reparar agora têm cada um o seu."] = "New custom icons for each optimization; SFC, DISM, CHKDSK and Repair now each have their own.",
        ["Tamanhos de texto padronizados e cabeçalho das páginas mais compacto, deixando mais espaço para o conteúdo."] = "Standardized text sizes and a more compact page header, leaving more room for content.",
        ["Nova opção em Configurações → Aparência: janela translúcida, com o fundo desfocado do Windows 11 (requer a versão 22H2 ou mais nova)."] = "New option in Settings → Appearance: translucent window, with the Windows 11 blurred background (requires version 22H2 or newer).",
        ["Busca rápida (Ctrl+K) para abrir qualquer página ou recurso, e notificações no canto da tela ao concluir cada ação."] = "Quick search (Ctrl+K) to open any page or feature, and notifications in the corner of the screen when each action finishes.",

        // ---------- Configurações dos jogos ----------
        ["Configurações dos jogos"] = "Game settings",
        ["Preset competitivo gravado direto no arquivo de configuração do jogo: menos efeitos pesados, sem V-Sync e sem desfoque. O original é guardado e volta com um clique."] = "Competitive preset written straight to the game's config file: fewer heavy effects, no V-Sync and no blur. The original is saved and comes back in one click.",
        ["Aplicar preset"] = "Apply preset", ["Reaplicar"] = "Reapply", ["Restaurar original"] = "Restore original",
        ["Não encontrado"] = "Not found", ["Preset ativo"] = "Preset on", ["Pronto"] = "Ready",
        ["Abra o jogo uma vez e feche para ele criar o arquivo de configuração."] = "Open the game once and close it so it creates its config file.",
        ["O arquivo já estava com o preset."] = "The file already had the preset.", ["Configurações originais restauradas."] = "Original settings restored.",
        ["Não há cópia original deste jogo."] = "There's no original copy for this game.",
        ["Sombras, efeitos, pós-processamento e folhagem no mínimo, sem V-Sync e sem desfoque de movimento; distância de visão alta para enxergar longe."] = "Shadows, effects, post-processing and foliage at minimum, no V-Sync and no motion blur; high view distance to see far.",
        ["Feche o Fortnite antes de aplicar: ele regrava o arquivo ao fechar."] = "Close Fortnite before applying: it rewrites the file when it closes.",
        ["Para o modo Desempenho (DX11 leve), escolha-o no menu de vídeo do jogo."] = "For Performance mode (light DX11), pick it in the game's video menu.",
        ["Sombras, oclusão de ambiente, iluminação volumétrica e decalques desligados; sem V-Sync e sem resolução dinâmica."] = "Shadows, ambient occlusion, volumetric lighting and decals off; no V-Sync and no dynamic resolution.",
        ["Feche o Apex antes de aplicar."] = "Close Apex before applying.",
        ["Texturas e modelos não mudam: ajuste-os pela VRAM da sua placa."] = "Textures and models don't change: set them for your card's VRAM.",
        ["Sem V-Sync e com NVIDIA Reflex ligado; oclusão de ambiente desligada e partículas no mínimo. As sombras ficam como estão (elas ajudam a ver inimigos)."] = "No V-Sync and NVIDIA Reflex on; ambient occlusion off and particles at minimum. Shadows stay as they are (they help you spot enemies).",
        ["Feche o CS2 antes de aplicar."] = "Close CS2 before applying.",
        ["Vale para a conta Steam que jogou CS2 por último neste PC."] = "Applies to the Steam account that last played CS2 on this PC.",
        ["Desfoque de movimento, profundidade de campo, bloom, reflexos de luz e sombras dinâmicas desligados; sem V-Sync."] = "Motion blur, depth of field, bloom, light shafts and dynamic shadows off; no V-Sync.",
        ["Feche o Rocket League antes de aplicar."] = "Close Rocket League before applying.",

        // ---------- NVIDIA ----------
        ["Perfil NVIDIA"] = "NVIDIA profile", ["Perfil NVIDIA para jogos"] = "NVIDIA gaming profile",
        ["Nenhuma placa de vídeo NVIDIA com driver instalado foi encontrada neste PC."] = "No NVIDIA graphics card with an installed driver was found on this PC.",
        ["Grava as configurações globais do Painel de Controle NVIDIA direto no driver, sem programas extras. Cada valor anterior é guardado e volta com Restaurar."] = "Writes the NVIDIA Control Panel global settings straight to the driver, with no extra programs. Each previous value is saved and comes back with Restore.",
        ["Padrão do driver"] = "Driver default", ["Já aplicado"] = "Already applied", ["Aplicar perfil"] = "Apply profile",
        ["Aplicando perfil NVIDIA"] = "Applying NVIDIA profile", ["Restaurando configurações NVIDIA"] = "Restoring NVIDIA settings",
        ["Marque pelo menos uma configuração."] = "Check at least one setting.",
        ["Vale para todos os jogos. Perfis específicos de jogo no painel da NVIDIA continuam tendo prioridade."] = "Applies to every game. Game-specific profiles in the NVIDIA panel still take priority.",
        ["Configurações NVIDIA anteriores restauradas"] = "Previous NVIDIA settings restored",
        ["Modo de gerenciamento de energia"] = "Power management mode", ["A placa não reduz o clock no meio do jogo."] = "The card doesn't lower its clock mid-game.",
        ["Preferir desempenho máximo"] = "Prefer maximum performance", ["Normal (adaptável)"] = "Normal (adaptive)", ["Ideal"] = "Optimal",
        ["Modo de baixa latência"] = "Low latency mode", ["Menos quadros na fila entre a CPU e a GPU: resposta mais rápida aos comandos."] = "Fewer frames queued between CPU and GPU: faster response to input.",
        ["Ligado"] = "On", ["Desligado"] = "Off", ["Ligada"] = "On", ["Desligada"] = "Off",
        ["Filtragem de textura – qualidade"] = "Texture filtering – quality", ["Prioriza o desempenho na filtragem de texturas, com diferença visual mínima."] = "Favors performance in texture filtering, with minimal visual difference.",
        ["Alta qualidade"] = "High quality", ["Qualidade"] = "Quality", ["Desempenho"] = "Performance", ["Alto desempenho"] = "High performance",
        ["Otimização segmentada"] = "Threaded optimization", ["Distribui o trabalho do driver em vários núcleos da CPU."] = "Spreads the driver's work across several CPU cores.",
        ["Automático"] = "Auto",
        ["Sincronização vertical"] = "Vertical sync", ["Desligada no driver: o jogo decide (use o V-Sync do jogo ou G-Sync se preferir)."] = "Off in the driver: the game decides (use the game's V-Sync or G-Sync if you prefer).",
        ["Forçar desligada"] = "Force off", ["Forçar ligada"] = "Force on", ["Usar configuração do aplicativo"] = "Use the 3D application setting", ["Rápida"] = "Fast",
        ["Tamanho do cache de sombreador"] = "Shader cache size", ["Cache ilimitado: menos travadas ao compilar shaders em jogos novos."] = "Unlimited cache: fewer stutters when new games compile shaders.",
        ["Ilimitado"] = "Unlimited", ["Desativado"] = "Disabled",
        ["Função da NvAPI indisponível neste driver."] = "NvAPI function unavailable in this driver.",

        // ---------- Defender ----------
        ["Exclua as pastas dos seus jogos da verificação em tempo real (seguro e recomendado) ou desligue a proteção temporariamente."] = "Exclude your game folders from real-time scanning (safe and recommended) or turn protection off temporarily.",
        ["Lendo o estado do Defender..."] = "Reading Defender status...",
        ["O Windows Defender não está ativo neste PC (outro antivírus pode estar no lugar dele)."] = "Windows Defender isn't active on this PC (another antivirus may be in its place).",
        ["Desligar"] = "Turn off", ["Ligar"] = "Turn on", ["Segurança do Windows"] = "Windows Security", ["Proteção em tempo real"] = "Real-time protection",
        ["Ligada."] = "On.", ["Desligada."] = "Off.",
        ["Desligar a proteção em tempo real deixa o PC sem verificação de vírus até ela ser religada (o Windows a religa sozinho depois de um tempo). Continuar?"] = "Turning off real-time protection leaves the PC without virus scanning until it's back on (Windows turns it back on by itself after a while). Continue?",
        ["Desligando a proteção em tempo real"] = "Turning off real-time protection", ["Ligando a proteção em tempo real"] = "Turning on real-time protection",
        ["Adicionar pasta"] = "Add folder", ["Escolha a pasta do jogo"] = "Choose the game folder", ["Pastas excluídas"] = "Excluded folders",
        ["O Defender não escaneia esses arquivos enquanto o jogo carrega."] = "Defender doesn't scan these files while the game loads.",
        ["Nenhuma pasta excluída."] = "No excluded folders.", ["Remover exclusão"] = "Remove exclusion",
        ["Adicionando exclusão no Defender"] = "Adding Defender exclusion", ["Removendo exclusão do Defender"] = "Removing Defender exclusion",
        ["O Windows não aplicou a mudança na proteção em tempo real."] = "Windows didn't apply the real-time protection change.",
        ["O Windows recusou a mudança porque a Proteção contra Adulteração está ativa. Desative-a em Segurança do Windows → Proteção contra vírus e ameaças → Gerenciar configurações e tente de novo."] = "Windows refused the change because Tamper Protection is on. Turn it off in Windows Security → Virus & threat protection → Manage settings and try again.",
        ["Proteção em tempo real do Defender ligada"] = "Defender real-time protection on",
        ["Proteção em tempo real do Defender desligada (o Windows a religa sozinho depois de um tempo)"] = "Defender real-time protection off (Windows turns it back on by itself after a while)",

        // ---------- BIOS ----------
        ["Editor de BIOS (SCEWIN)"] = "BIOS editor (SCEWIN)",
        ["Lê e grava as configurações da BIOS pelo Windows com o SCEWIN, a ferramenta oficial da AMI. A primeira leitura é guardada como cópia original e só os itens que você alterar são gravados. Funciona em placas com BIOS AMI (ASUS, MSI, Gigabyte, ASRock e a maioria das outras)."] = "Reads and writes BIOS settings from Windows with SCEWIN, AMI's official tool. The first read is kept as the original copy and only the items you change are written. Works on boards with AMI BIOS (ASUS, MSI, Gigabyte, ASRock and most others).",
        ["SCEWIN não configurado"] = "SCEWIN not set up", ["SCEWIN não configurado."] = "SCEWIN not set up.", ["Pronto para ler"] = "Ready to read",
        ["Escolher SCEWIN_64.exe"] = "Choose SCEWIN_64.exe", ["Trocar SCEWIN"] = "Change SCEWIN",
        ["Escolha o SCEWIN_64.exe (deixe o amifldrv64.sys na mesma pasta)"] = "Choose SCEWIN_64.exe (keep amifldrv64.sys in the same folder)",
        ["Escolha o arquivo SCEWIN_64.exe."] = "Choose the SCEWIN_64.exe file.",
        ["Ler configurações da BIOS"] = "Read BIOS settings", ["Ler de novo"] = "Read again", ["Lendo a BIOS pelo SCEWIN"] = "Reading the BIOS with SCEWIN",
        ["Restaurar BIOS"] = "Restore BIOS", ["Restaurando a BIOS original"] = "Restoring the original BIOS",
        ["Gravar de volta na BIOS a cópia original feita na primeira leitura? Vale após reiniciar."] = "Write the original copy from the first read back to the BIOS? Takes effect after restart.",
        ["Mude apenas o que você conhece. Se o PC não iniciar depois de gravar, limpe a CMOS (botão Clear CMOS ou retirando a bateria da placa-mãe por alguns minutos) para voltar ao padrão de fábrica."] = "Only change what you know. If the PC doesn't boot after writing, clear the CMOS (Clear CMOS button or removing the motherboard battery for a few minutes) to go back to factory defaults.",
        ["Buscar configuração…"] = "Search setting…", ["Recomendados"] = "Recommended", ["Alterados"] = "Changed", ["Todas"] = "All", ["Recomendado"] = "Recommended",
        ["Nenhuma das configurações recomendadas existe nesta BIOS."] = "None of the recommended settings exist in this BIOS.",
        ["Aplicar recomendados"] = "Apply recommended", ["Gravar alterações"] = "Write changes", ["Gravar na BIOS"] = "Write to BIOS", ["Gravando na BIOS"] = "Writing to BIOS",
        ["Altere uma opção para gravá-la."] = "Change an option to write it.", ["Só os itens alterados serão gravados."] = "Only changed items will be written.",
        ["As recomendações já estão aplicadas (ou não existem nesta BIOS)."] = "The recommendations are already applied (or don't exist in this BIOS).",
        ["Nenhuma alteração pendente na BIOS."] = "No pending BIOS changes.", ["Reiniciar agora para aplicar as mudanças na BIOS?"] = "Restart now to apply the BIOS changes?",
        ["Necessário para a placa de vídeo usar toda a VRAM (Resizable BAR)."] = "Required for the graphics card to use all of its VRAM (Resizable BAR).",
        ["Resizable BAR: ganho de FPS em jogos compatíveis."] = "Resizable BAR: FPS gains in supported games.",
        ["Clock de referência estável, sem oscilação proposital."] = "Stable reference clock, with no intentional fluctuation.",
        ["Ajuste a BIOS pelo Windows com o editor abaixo (SCEWIN) ou reinicie direto na BIOS para fazer à mão. Os ajustes que costumam trazer ganho real estão listados no fim da página."] = "Tune the BIOS from Windows with the editor below (SCEWIN) or restart straight into the BIOS and change it by hand. The settings that usually bring real gains are listed at the end of the page.",
        ["Não foi possível iniciar o SCEWIN."] = "Could not start SCEWIN.", ["O SCEWIN não respondeu em 3 minutos."] = "SCEWIN didn't respond within 3 minutes.",
        ["Não há cópia original da BIOS. Leia as configurações pelo menos uma vez antes."] = "There's no original BIOS copy. Read the settings at least once first.",
        ["A BIOS tem senha de administrador; remova-a para gravar pelo Windows."] = "The BIOS has an administrator password; remove it to write from Windows.",
        ["Esta placa-mãe não usa BIOS AMI compatível com o SCEWIN."] = "This motherboard doesn't use a SCEWIN-compatible AMI BIOS.",
        ["O driver do SCEWIN (amifldrv64.sys) não carregou: deixe-o na mesma pasta e desative a Integridade de Memória se necessário."] = "The SCEWIN driver (amifldrv64.sys) didn't load: keep it in the same folder and turn off Memory Integrity if needed.",
        ["Configurações da BIOS lidas pelo SCEWIN"] = "BIOS settings read by SCEWIN",
        ["BIOS: configurações originais gravadas — reinicie para aplicar"] = "BIOS: original settings written — restart to apply",

        // ---------- DDU ----------
        ["Instalação limpa de driver (DDU)"] = "Clean driver install (DDU)", ["Instalação limpa de driver"] = "Clean driver install",
        ["Remove completamente o driver de vídeo atual com o Display Driver Uninstaller, reinicia e abre o instalador do driver novo assim que você entrar no Windows. Resolve travadas, telas pretas e restos de drivers antigos."] = "Completely removes the current graphics driver with Display Driver Uninstaller, restarts and opens the new driver's installer as soon as you sign in to Windows. Fixes stutters, black screens and leftovers from old drivers.",
        ["DDU instalado"] = "DDU installed", ["DDU será instalado"] = "DDU will be installed",
        ["Nenhuma placa de vídeo reconhecida."] = "No graphics card recognized.",
        ["Baixe o driver novo"] = "Download the new driver", ["No site oficial da fabricante da sua placa."] = "From your card maker's official site.",
        ["Escolha o instalador"] = "Choose the installer", ["O arquivo .exe que você baixou."] = "The .exe file you downloaded.",
        ["Remova e reinstale"] = "Remove and reinstall", ["Ponto de restauração, DDU, reinício e instalação."] = "Restore point, DDU, restart and install.",
        ["Baixar driver oficial"] = "Download official driver", ["Escolher instalador"] = "Choose installer", ["Trocar instalador"] = "Change installer",
        ["Iniciar instalação limpa"] = "Start clean install", ["Escolha o instalador do driver novo"] = "Choose the new driver's installer",
        ["Escolha o instalador (.exe) do driver novo."] = "Choose the new driver's installer (.exe).",
        ["Fabricante da placa de vídeo não reconhecido."] = "Graphics card maker not recognized.",
        ["Copiando o instalador do driver..."] = "Copying the driver installer...", ["Criando ponto de restauração..."] = "Creating restore point...",
        ["Bloqueando drivers do Windows Update até o driver novo ser instalado..."] = "Blocking Windows Update drivers until the new driver is installed...",
        ["Removendo o driver atual com o DDU (o PC reinicia sozinho)..."] = "Removing the current driver with DDU (the PC restarts by itself)...",
        ["DDU (Display Driver Uninstaller) instalado"] = "DDU (Display Driver Uninstaller) installed",
    };

    private static readonly (Regex Regex, Func<Match, string> Build)[] ExtrasPatterns =
    {
        P(@"^Atual: (.+)  →  Novo: (.+)$", m => $"Current: {Tr(m.Groups[1].Value)}  →  New: {Tr(m.Groups[2].Value)}"),
        P(@"^(\d+) ajustes$", m => $"{m.Groups[1].Value} tweaks"),
        P(@"^Preset aplicado: (\d+) ajustes\.$", m => $"Preset applied: {m.Groups[1].Value} tweaks."),
        P(@"^Preset competitivo aplicado: ([^—]+) \((\d+) valores\)$", m => $"Competitive preset applied: {m.Groups[1].Value} ({m.Groups[2].Value} values)"),
        P(@"^Configurações originais restauradas: (.+)$", m => $"Original settings restored: {m.Groups[1].Value}"),
        P(@"^Arquivo de configuração do (.+) não encontrado\.(.*)$", m => $"{m.Groups[1].Value} config file not found." + (m.Groups[2].Value.Length > 0 ? " Open the game once and close it so it creates the file." : "")),
        P(@"^Feche o (.+) antes de aplicar: ele regrava as configurações ao fechar\.$", m => $"Close {m.Groups[1].Value} before applying: it rewrites its settings when it closes."),
        P(@"^Feche o (.+) antes de restaurar\.$", m => $"Close {m.Groups[1].Value} before restoring."),
        P(@"^Perfil NVIDIA para jogos aplicado \((\d+) configurações\)$", m => $"NVIDIA gaming profile applied ({m.Groups[1].Value} settings)"),
        P(@"^NVIDIA: não foi possível (.+) \(código (-?\d+)\)\.$", m => $"NVIDIA: couldn't complete the operation (code {m.Groups[2].Value})."),
        P(@"^(\d+) configurações$", m => $"{m.Groups[1].Value} settings"),
        P(@"^Gravar (\d+) alteração\(ões\)$", m => $"Write {m.Groups[1].Value} change(s)"),
        P(@"^(\d+) alteração\(ões\) pendente\(s\) na BIOS\. Clique em Gravar para salvar\.$", m => $"{m.Groups[1].Value} pending BIOS change(s). Click Write to save."),
        P(@"^(\d+) configuração\(ões\) marcadas\. Revise e grave\.$", m => $"{m.Groups[1].Value} setting(s) marked. Review and write."),
        P(@"^Mostrando 120 de (\d+)\. Refine a busca para ver as outras\.$", m => $"Showing 120 of {m.Groups[1].Value}. Refine the search to see the others."),
        P(@"^BIOS: (\d+) configuração\(ões\) gravada\(s\) — reinicie para aplicar$", m => $"BIOS: {m.Groups[1].Value} setting(s) written — restart to apply"),
        P(@"^O SCEWIN (não exportou as configurações|recusou a gravação|recusou a restauração) \(código (-?\d+)\)\. ?(.*)$", m => $"SCEWIN {(m.Groups[1].Value.StartsWith("não") ? "didn't export the settings" : m.Groups[1].Value.EndsWith("gravação") ? "refused the write" : "refused the restore")} (code {m.Groups[2].Value}). {Tr(m.Groups[3].Value)}"),
        P(@"^Gravar na BIOS\?\n\n(.+)\n\nAs mudanças valem depois de reiniciar\.$", m => $"Write to the BIOS?\n\n{m.Groups[1].Value}\n\nChanges take effect after restart."),
        P(@"^Placa detectada: (.+)$", m => $"Detected card: {m.Groups[1].Value}"),
        P(@"^Pasta excluída da verificação do Defender: (.+)$", m => $"Folder excluded from Defender scanning: {m.Groups[1].Value}"),
        P(@"^Exclusão do Defender removida: (.+)$", m => $"Defender exclusion removed: {m.Groups[1].Value}"),
        P(@"^Não foi possível instalar o DDU pelo winget \(código (-?\d+)\)\.$", m => $"Could not install DDU via winget (code {m.Groups[1].Value})."),
        P(@"^O DDU terminou com o código (-?\d+); nada foi agendado\.$", m => $"DDU exited with code {m.Groups[1].Value}; nothing was scheduled."),
        P(@"^Ponto de restauração não criado: (.+)$", m => $"Restore point not created: {m.Groups[1].Value}"),
        P(@"^O driver de vídeo atual será removido e o PC vai reiniciar sozinho\. Depois de entrar no Windows, o instalador ""(.+)"" abre automaticamente\.\n\nSalve seus trabalhos e feche os programas\. Continuar\?$", m => $"The current graphics driver will be removed and the PC will restart by itself. After you sign in to Windows, the installer \"{m.Groups[1].Value}\" opens automatically.\n\nSave your work and close your programs. Continue?"),
        P(@"^Proteção em tempo real ((?:Ligada|Desligada)\.)(.*)$", m => $"Real-time protection {Tr(m.Groups[1].Value)}" + (m.Groups[2].Value.Length > 0 ? " Tamper Protection is on: turn it off in Windows Security to change it from here." : "")),
        P(@"^(Ligada|Desligada)\. A Proteção contra Adulteração está ativa: desative-a na Segurança do Windows para mudar por aqui\.$", m => $"{Tr(m.Groups[1].Value + ".")} Tamper Protection is on: turn it off in Windows Security to change it from here."),
        P(@"^(\d+) quadros$", m => $"{m.Groups[1].Value} frames"),
        P(@"^Valor (.+)$", m => $"Value {m.Groups[1].Value}"),
    };
}
