using System.Text.RegularExpressions;

namespace PQueirozOptimizer.Services;

/// <summary>Traduções do Qrztweaks 2.0: Smart Optimize, catálogo de ajustes, Performance Lab, diagnóstico, perfis, Command Center e licença.</summary>
public static partial class Translator
{
    private static readonly Dictionary<string, string> V2Exact = new(StringComparer.Ordinal)
    {
        // ---------- Navegação e páginas ----------
        ["Perfis"] = "Profiles", ["Perfil"] = "Profile", ["Command Center"] = "Command Center",
        ["Análise do PC e ajustes recomendados pelo objetivo, com risco e reversão."] = "PC analysis and tweaks recommended by goal, with risk and rollback.",
        ["FPS, frametime e sensores reais, histórico e comparação antes/depois."] = "Real FPS, frametime and sensors, history and before/after comparison.",
        ["Perfis por jogo ou uso, com ativação automática do Modo Jogo."] = "Profiles per game or use, with automatic Game Mode activation.",
        ["A saúde do PC, o monitor ao vivo, os alertas e as ações rápidas ficam aqui."] = "PC health, the live monitor, alerts and quick actions are here.",
        ["Escolha o objetivo do PC: o app lê o estado de cada ajuste e recomenda só o que se aplica, com risco e reversão."] = "Choose the PC's goal: the app reads the state of each tweak and recommends only what applies, with risk and rollback.",
        ["Uma leitura guiada dos principais componentes do Windows."] = "A guided reading of the main Windows components.",
        ["Verifique sistema, drivers, serviços, rede, Bluetooth e integridade do Windows."] = "Check system, drivers, services, network, Bluetooth and Windows integrity.",
        ["Executar diagnóstico completo"] = "Run full diagnostics",

        // ---------- Smart Optimize ----------
        ["Escolha o objetivo deste PC"] = "Choose this PC's goal",
        ["O Smart Optimize lê o hardware e o estado de cada ajuste, recomenda só o que se aplica e mostra o risco, a reversão e a evidência de cada um. Nada é aplicado sem a sua revisão."] = "Smart Optimize reads the hardware and the state of each tweak, recommends only what applies and shows the risk, rollback and evidence of each one. Nothing is applied without your review.",
        ["Analisar este PC"] = "Analyze this PC", ["Analisar de novo"] = "Analyze again",
        ["Clique em \"Analisar este PC\" para detectar o hardware e conferir quais ajustes já estão aplicados. A análise só lê o sistema."] = "Click \"Analyze this PC\" to detect the hardware and check which tweaks are already applied. The analysis only reads the system.",
        ["Gaming competitivo"] = "Competitive gaming", ["gaming competitivo"] = "competitive gaming", ["Notebook"] = "Laptop", ["notebook"] = "laptop", ["Programação"] = "Development", ["programação"] = "development",
        ["Uso diário"] = "Daily use", ["uso diário"] = "daily use", ["Personalizado"] = "Custom", ["personalizado"] = "custom", ["Desktop"] = "Desktop",
        ["Frametime estável, responsividade e menos processos em segundo plano."] = "Stable frametime, responsiveness and fewer background processes.",
        ["Temperatura, autonomia, consumo e ruído."] = "Temperature, battery life, power draw and noise.",
        ["Preserva Docker, WSL, Hyper-V e ferramentas de desenvolvimento."] = "Preserves Docker, WSL, Hyper-V and development tools.",
        ["Inicialização, limpeza segura, privacidade e estabilidade."] = "Startup, safe cleanup, privacy and stability.",
        ["Nada vem marcado: você escolhe cada ajuste."] = "Nothing comes checked: you choose each tweak.",
        ["Detectando hardware e lendo o estado dos ajustes..."] = "Detecting hardware and reading the state of the tweaks...",
        ["Recalculando para o novo objetivo..."] = "Recalculating for the new goal...",
        ["Conferindo apps da Loja e tarefas agendadas..."] = "Checking Store apps and scheduled tasks...",
        ["Não foi possível concluir a análise"] = "Could not finish the analysis",
        ["Este PC"] = "This PC", ["Processador"] = "Processor", ["Placa de vídeo"] = "Graphics card", ["Memória"] = "Memory", ["Armazenamento"] = "Storage", ["Placa-mãe"] = "Motherboard",
        ["Plano de energia"] = "Power plan", ["Tipo"] = "Type", ["Virtualização"] = "Virtualization", ["Hipervisor ativo"] = "Hypervisor active", ["Não detectada"] = "Not detected", ["Não informado"] = "Not reported",
        ["Equilibrado"] = "Balanced", ["Alto desempenho"] = "High performance", ["Economia de energia"] = "Power saver", ["Desempenho máximo"] = "Ultimate performance", ["Desconhecido"] = "Unknown",
        ["Os itens marcados são os recomendados para o objetivo. Ajustes já aplicados, sem efeito neste PC ou bloqueados pelo plano ficam ocultos; use o filtro para vê-los."] = "Checked items are the ones recommended for the goal. Tweaks already applied, without effect on this PC or locked by your plan are hidden; use the filter to see them.",
        ["Mostrar também já aplicados, não aplicáveis e bloqueados"] = "Also show applied, not applicable and locked",
        ["Recomendado"] = "Recommended", ["Já aplicado"] = "Already applied", ["Não aplicável"] = "Not applicable", ["Incompatível"] = "Incompatible", ["Requer revisão"] = "Needs review", ["Falha na leitura"] = "Read failed",
        ["Seguro"] = "Safe", ["Moderado"] = "Moderate", ["Avançado"] = "Advanced", ["Requer reiniciar"] = "Needs restart", ["Ação pontual"] = "One-off action", ["Não reversível"] = "Not reversible",
        ["Revisar e aplicar"] = "Review and apply", ["Detalhes"] = "Details",
        ["Nada a recomendar para este objetivo: os ajustes já estão aplicados ou não se aplicam a este PC."] = "Nothing to recommend for this goal: the tweaks are already applied or don't apply to this PC.",
        ["Leitura atual"] = "Current reading", ["Efeitos colaterais"] = "Side effects", ["Como é verificado"] = "How it is verified", ["Como reverter"] = "How to revert",
        ["Evidência do benefício"] = "Evidence of benefit", ["Identificador"] = "Identifier", ["Não recomendado para este objetivo"] = "Not recommended for this goal",
        ["Modo Jogo ativo"] = "Game Mode active",
        ["O Modo Jogo temporário está ligado e controla o plano de energia e os serviços pausados. Desative-o antes de aplicar ajustes de energia."] = "Temporary Game Mode is on and controls the power plan and paused services. Turn it off before applying power tweaks.",
        ["Ryzen X3D com dois CCDs"] = "Ryzen X3D with two CCDs",
        ["O Windows usa a Game Bar e o plano Equilibrado para levar o jogo ao CCD com 3D V-Cache. Esses ajustes ficam bloqueados neste PC."] = "Windows uses the Game Bar and the Balanced plan to move the game to the CCD with 3D V-Cache. These tweaks are locked on this PC.",
        ["Virtualização em uso"] = "Virtualization in use",
        ["O Smart Optimize não mexe em Hyper-V, WSL, Docker nem nos recursos de virtualização. Para desligá-los, use Serviços, de forma consciente."] = "Smart Optimize doesn't touch Hyper-V, WSL, Docker or virtualization features. To turn them off, use Services, knowingly.",
        ["Objetivo Notebook em um desktop"] = "Laptop goal on a desktop",
        ["Este PC não tem bateria. O perfil Notebook prioriza consumo e temperatura; para jogos, escolha Gaming competitivo."] = "This PC has no battery. The Laptop profile prioritizes power and temperature; for games, choose Competitive gaming.",
        ["Telemetria configurada duas vezes"] = "Telemetry set twice",
        ["\"Políticas de diagnóstico, nuvem e IA\" grava AllowTelemetry = 0 e \"Só dados de diagnóstico obrigatórios\" grava 1, desfazendo parte da primeira. Escolha só uma."] = "\"Diagnostics, cloud and AI policies\" writes AllowTelemetry = 0 and \"Required diagnostic data only\" writes 1, undoing part of the first. Choose only one.",
        ["Plano de energia com Modo Jogo ativo"] = "Power plan with Game Mode active",
        ["O Modo Jogo vai restaurar o plano anterior ao ser desligado e desfaria a troca. Desative o Modo Jogo antes."] = "Game Mode will restore the previous plan when turned off and would undo the change. Turn Game Mode off first.",
        ["Hibernação em notebook"] = "Hibernation on a laptop", ["Notebooks usam a hibernação quando a bateria acaba."] = "Laptops use hibernation when the battery runs out.",
        ["Conflito"] = "Conflict", ["Precisam reiniciar para valer:"] = "Need a restart to take effect:",
        ["Resultado verificado"] = "Verified result", ["Reinicie o PC"] = "Restart the PC",
        ["Alguns ajustes só passam a valer depois de reiniciar o Windows."] = "Some tweaks only take effect after restarting Windows.",
        ["O backup de cada item está em Atividade e reversão."] = "Each item's backup is in Activity and rollback.",
        ["Ação pontual executada (não fica registrada como estado)."] = "One-off action executed (not recorded as a state).",
        ["A execução teve falhas; confira no registro se esta ação pontual foi concluída."] = "The run had failures; check the log to see whether this one-off action finished.",
        ["Escolha o ajuste a testar."] = "Choose the tweak to test.",
        ["No modo demonstração nenhum ajuste pode ser aplicado, então o Optimization Lab fica indisponível. Ative uma licença para usar."] = "In demo mode no tweak can be applied, so the Optimization Lab is unavailable. Activate a license to use it.",
        ["Nenhum ajuste do seu plano pode ser testado aqui."] = "No tweak in your plan can be tested here.",
        ["O ajuste não foi confirmado no Windows. Veja o registro da execução; o experimento continua sem o ajuste."] = "The tweak wasn't confirmed in Windows. See the run log; the experiment continues without the tweak.",
        ["A reversão não foi confirmada. Confira em Atividade e reversão."] = "The rollback wasn't confirmed. Check Activity and rollback.",
        ["Estado lido no Windows depois da execução. Ajustes de ação pontual (limpeza, TRIM) não entram aqui."] = "State read from Windows after the run. One-off actions (cleanup, TRIM) are not included here.",

        // ---------- Catálogo: nomes e categorias ----------
        ["Energia"] = "Power", ["Jogos"] = "Games", ["Interface"] = "Interface", ["Sistema"] = "System", ["Rede"] = "Network", ["Serviços"] = "Services", ["Privacidade"] = "Privacy",
        ["IA do Windows"] = "Windows AI", ["Apps"] = "Apps", ["Manutenção"] = "Maintenance",
        ["Plano de energia Qrz"] = "Qrz power plan", ["Desativar a hibernação"] = "Turn off hibernation", ["Desligar o Power Throttling"] = "Turn off Power Throttling",
        ["Modo de Jogo do Windows"] = "Windows Game Mode", ["Desligar a gravação em segundo plano"] = "Turn off background recording", ["Agendamento de GPU por hardware (HAGS)"] = "Hardware-accelerated GPU scheduling (HAGS)",
        ["Otimizações para jogos em janela"] = "Optimizations for windowed games", ["Desligar o ULPS (AMD)"] = "Turn off ULPS (AMD)", ["Prioridade para o programa em foco"] = "Priority for the program in focus",
        ["Prioridade multimídia para jogos"] = "Multimedia priority for games", ["Desligar o limite de rede do MMCSS"] = "Turn off the MMCSS network limit", ["Reparar o agendador multimídia (MMCSS)"] = "Repair the multimedia scheduler (MMCSS)",
        ["Desligar a aceleração do mouse"] = "Turn off mouse acceleration", ["Efeitos visuais para desempenho"] = "Visual effects for performance", ["Desligar a inicialização rápida"] = "Turn off Fast Startup",
        ["Atualizações só com a rede local"] = "Updates only with the local network", ["Desligar a Assistência Remota"] = "Turn off Remote Assistance", ["Serviços de telemetria e relatórios"] = "Telemetry and reporting services",
        ["Desativar o serviço de Fax"] = "Disable the Fax service", ["Desativar o Registro Remoto"] = "Disable Remote Registry", ["Desativar o serviço de Mapas"] = "Disable the Maps service",
        ["Tarefas de CEIP e feedback"] = "CEIP and feedback tasks", ["Sem anúncios e apps instalados sozinhos"] = "No ads or self-installing apps", ["Sem experiências personalizadas"] = "No tailored experiences",
        ["Desligar o ID de publicidade"] = "Turn off the advertising ID", ["Pesquisa do Iniciar sem resultados da web"] = "Start search without web results", ["Desligar o histórico de atividades"] = "Turn off activity history",
        ["Políticas de diagnóstico, nuvem e IA"] = "Diagnostics, cloud and AI policies", ["Só dados de diagnóstico obrigatórios"] = "Required diagnostic data only", ["Desligar o Copilot integrado"] = "Turn off built-in Copilot",
        ["Desligar o Recall"] = "Turn off Recall", ["Desligar o Click To Do"] = "Turn off Click To Do", ["Remover apps pré-instalados"] = "Remove preinstalled apps", ["Remover a Cortana"] = "Remove Cortana",
        ["Remover os Widgets"] = "Remove Widgets", ["Remover o OneDrive"] = "Remove OneDrive", ["TRIM / otimização das unidades"] = "TRIM / drive optimization", ["Limpar o cache DNS"] = "Clear the DNS cache",
        ["Limpeza de disco do Windows"] = "Windows Disk Cleanup",

        // ---------- Catálogo: descrições ----------
        ["Plano de baixa latência baseado no Equilibrado, com estacionamento de núcleos e estados de economia reduzidos."] = "Low-latency plan based on Balanced, with reduced core parking and power-saving states.",
        ["Apaga o hiberfil.sys, que pode ocupar até 40% da RAM no disco."] = "Deletes hiberfil.sys, which can take up to 40% of RAM on disk.",
        ["Impede o Windows de reduzir a energia de programas em segundo plano."] = "Stops Windows from reducing power to background programs.",
        ["Liga o Modo de Jogo nativo, que prioriza o jogo e adia atualizações durante a partida."] = "Turns on the native Game Mode, which prioritizes the game and postpones updates during play.",
        ["Desliga a captura contínua da Game Bar (os últimos minutos de jogo ficam sempre sendo gravados)."] = "Turns off the Game Bar's continuous capture (the last minutes of play are always being recorded).",
        ["Deixa a própria placa de vídeo gerenciar a fila de trabalho."] = "Lets the graphics card manage its own work queue.",
        ["Usa o modelo de apresentação moderno em jogos DirectX 10/11 em janela ou sem borda."] = "Uses the modern presentation model in windowed or borderless DirectX 10/11 games.",
        ["Impede a placa AMD de entrar em repouso profundo, que causa engasgos e telas pretas em alguns PCs."] = "Stops the AMD card from entering deep sleep, which causes stutters and black screens on some PCs.",
        ["Garante que o Windows dê mais tempo de CPU ao programa em primeiro plano."] = "Ensures Windows gives more CPU time to the foreground program.",
        ["Reserva menos CPU para tarefas de fundo do agendador multimídia e sobe a prioridade da categoria Games."] = "Reserves less CPU for the multimedia scheduler's background tasks and raises the Games category priority.",
        ["Remove o limite de pacotes que o Windows aplica enquanto toca áudio ou vídeo."] = "Removes the packet limit Windows applies while playing audio or video.",
        ["Restaura valores padrão do MMCSS que outros otimizadores costumam apagar."] = "Restores default MMCSS values that other optimizers often delete.",
        ["Desliga a \"precisão aprimorada do ponteiro\": o cursor anda sempre a mesma distância para o mesmo movimento."] = "Turns off \"enhance pointer precision\": the cursor always moves the same distance for the same motion.",
        ["Desliga animações de janelas, menus e da barra de tarefas, e a transparência."] = "Turns off window, menu and taskbar animations, and transparency.",
        ["Com ela ligada, \"Desligar\" só hiberna o kernel: drivers e atualizações não reiniciam de verdade."] = "With it on, \"Shut down\" only hibernates the kernel: drivers and updates don't really restart.",
        ["O Windows deixa de enviar atualizações para outros PCs pela internet."] = "Windows stops sending updates to other PCs over the internet.",
        ["Impede convites de Assistência Remota para este PC."] = "Blocks Remote Assistance invitations to this PC.",
        ["Desativa DiagTrack, dmwappushservice, o coletor de diagnóstico, o Relatório de Erros e o Assistente de Compatibilidade."] = "Disables DiagTrack, dmwappushservice, the diagnostics collector, Error Reporting and the Compatibility Assistant.",
        ["Fax do Windows."] = "Windows Fax.", ["Edição do registro deste PC pela rede."] = "Editing this PC's registry over the network.", ["Download de mapas offline."] = "Offline map downloads.",
        ["Desativa tarefas agendadas do Programa de Aperfeiçoamento e de pesquisas de feedback."] = "Disables Customer Experience Improvement Program and feedback survey scheduled tasks.",
        ["Impede o Windows de instalar jogos promocionais e mostrar sugestões no Iniciar e no Explorador."] = "Stops Windows from installing promotional games and showing suggestions in Start and File Explorer.",
        ["A Microsoft deixa de usar dados de diagnóstico para dicas e anúncios personalizados."] = "Microsoft stops using diagnostic data for tailored tips and ads.",
        ["Apps deixam de usar um identificador para anúncios personalizados."] = "Apps stop using an identifier for personalized ads.",
        ["A pesquisa do menu Iniciar mostra só o que está no PC."] = "Start menu search shows only what is on the PC.",
        ["O Windows deixa de registrar e enviar os apps e arquivos abertos."] = "Windows stops recording and sending the apps and files you open.",
        ["Conjunto de políticas: telemetria no mínimo, sem conteúdo de consumidor, sem inventário, sem análise de IA e sem instalação remota (Push)."] = "A set of policies: minimum telemetry, no consumer content, no inventory, no AI analysis and no remote install (Push).",
        ["Limita a telemetria do Windows ao nível obrigatório."] = "Limits Windows telemetry to the required level.",
        ["Desliga o Copilot embutido do Windows 11 (antes do 24H2) e o botão da barra de tarefas."] = "Turns off Windows 11's built-in Copilot (before 24H2) and its taskbar button.",
        ["Impede o Recall de tirar capturas periódicas da tela para a busca com IA."] = "Stops Recall from taking periodic screenshots for AI search.",
        ["Desliga a sobreposição de IA que analisa o que está na tela."] = "Turns off the AI overlay that analyzes what's on the screen.",
        ["Remove Notícias, Clima, Solitaire, Teams pessoal, Skype, Vincular ao Celular, Mapas e outros."] = "Removes News, Weather, Solitaire, personal Teams, Skype, Phone Link, Maps and others.",
        ["Remove o app Cortana."] = "Removes the Cortana app.", ["Remove o painel de Widgets (Web Experience)."] = "Removes the Widgets board (Web Experience).", ["Desinstala o OneDrive."] = "Uninstalls OneDrive.",
        ["Envia o TRIM aos SSDs e desfragmenta HDDs."] = "Sends TRIM to SSDs and defragments HDDs.", ["Apaga endereços de sites guardados em cache."] = "Deletes cached website addresses.",
        ["Roda a Limpeza de Disco do Windows nas categorias seguras."] = "Runs Windows Disk Cleanup on the safe categories.",

        // ---------- Catálogo: efeitos colaterais ----------
        ["Mais consumo e calor em repouso. Em notebooks reduz a bateria (por isso só aparece em desktops)."] = "More power and heat at idle. On laptops it reduces battery life (that's why it only shows on desktops).",
        ["A opção Hibernar some e a inicialização rápida deixa de funcionar."] = "The Hibernate option disappears and Fast Startup stops working.",
        ["Programas em segundo plano consomem mais energia."] = "Background programs use more power.", ["Nenhum conhecido."] = "None known.",
        ["Os atalhos de gravação da Game Bar param de funcionar."] = "The Game Bar recording shortcuts stop working.",
        ["Em alguns drivers antigos causa travadas; se notar piora, reverta."] = "On some old drivers it causes stutters; if things get worse, revert.",
        ["Raros problemas com sobreposições antigas."] = "Rare issues with old overlays.", ["Um pouco mais de consumo em repouso."] = "Slightly more power at idle.",
        ["Nenhum: corresponde ao padrão do Windows cliente."] = "None: it matches the default of client Windows.",
        ["Tarefas de fundo (downloads, gravação) podem ficar um pouco mais lentas durante o jogo."] = "Background tasks (downloads, recording) may get a little slower while gaming.",
        ["Nenhum relevante em PCs modernos."] = "Nothing relevant on modern PCs.", ["Nenhum: só recria valores padrão que faltam."] = "None: it only recreates missing default values.",
        ["Muda a sensação do mouse no Windows; pode ser preciso ajustar a sensibilidade."] = "Changes how the mouse feels in Windows; you may need to adjust the sensitivity.",
        ["O Windows fica sem animações e sem transparência."] = "Windows runs without animations and transparency.",
        ["A inicialização a frio pode levar alguns segundos a mais."] = "A cold boot may take a few seconds longer.", ["Nenhum: o download das atualizações continua igual."] = "None: update downloads stay the same.",
        ["Ninguém consegue ajudar por Assistência Remota (Quick Assist continua funcionando)."] = "Nobody can help through Remote Assistance (Quick Assist keeps working).",
        ["Sem relatórios de erro para a Microsoft e sem avisos de compatibilidade de programas antigos."] = "No error reports to Microsoft and no compatibility warnings for old programs.",
        ["Envio de fax pelo Windows para de funcionar."] = "Sending faxes through Windows stops working.",
        ["Ferramentas de administração remota de empresas podem depender dele."] = "Corporate remote administration tools may depend on it.",
        ["Mapas offline deixam de ser atualizados."] = "Offline maps stop being updated.", ["Nenhum."] = "None.", ["Sem continuar atividades entre dispositivos."] = "No continuing activities across devices.",
        ["Sem sugestões do Bing na pesquisa."] = "No Bing suggestions in search.",
        ["Sugestões da nuvem e alguns recursos de IA do Windows ficam indisponíveis."] = "Cloud suggestions and some Windows AI features become unavailable.",
        ["O Programa Windows Insider exige dados opcionais."] = "The Windows Insider Program requires optional data.",
        ["O Copilot integrado deixa de abrir pelo atalho."] = "The built-in Copilot stops opening from the shortcut.", ["Sem a linha do tempo de capturas."] = "No snapshot timeline.", ["Sem o Click To Do."] = "No Click To Do.",
        ["Os apps somem para todos os usuários. A reversão não reinstala: use a Microsoft Store."] = "The apps disappear for all users. Rollback doesn't reinstall them: use the Microsoft Store.",
        ["Não reversível pelo backup; reinstale pela Microsoft Store."] = "Not reversible through the backup; reinstall from the Microsoft Store.",
        ["O painel de Widgets e o clima da barra de tarefas somem. Não reversível pelo backup."] = "The Widgets board and the taskbar weather disappear. Not reversible through the backup.",
        ["Arquivos deixam de sincronizar com a nuvem. Confira se tudo está salvo localmente antes."] = "Files stop syncing to the cloud. Make sure everything is saved locally first.",
        ["Nenhum; pode levar alguns minutos em HDDs."] = "None; it may take a few minutes on HDDs.",
        ["Os arquivos apagados não voltam (são temporários e sobras de atualização)."] = "Deleted files don't come back (they are temporary files and update leftovers).",

        // ---------- Catálogo: verificação ----------
        ["O plano ativo passa a ser o Qrz (powercfg /getactivescheme)."] = "The active plan becomes Qrz (powercfg /getactivescheme).",
        ["HibernateEnabled = 0 em HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power."] = "HibernateEnabled = 0 in HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power.",
        ["PowerThrottlingOff = 1 em HKLM\\...\\Control\\Power\\PowerThrottling."] = "PowerThrottlingOff = 1 in HKLM\\...\\Control\\Power\\PowerThrottling.",
        ["AutoGameModeEnabled = 1 (ou ausente, que é o padrão ligado)."] = "AutoGameModeEnabled = 1 (or missing, which is the default on).",
        ["AppCaptureEnabled = 0 e GameDVR_Enabled = 0."] = "AppCaptureEnabled = 0 and GameDVR_Enabled = 0.",
        ["HwSchMode = 2 em HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers."] = "HwSchMode = 2 in HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers.",
        ["DirectXUserGlobalSettings contém SwapEffectUpgradeEnable=1."] = "DirectXUserGlobalSettings contains SwapEffectUpgradeEnable=1.",
        ["EnableUlps = 0 nas chaves da placa AMD."] = "EnableUlps = 0 in the AMD card's keys.", ["Win32PrioritySeparation = 2 ou 38."] = "Win32PrioritySeparation = 2 or 38.",
        ["SystemResponsiveness = 10 e GPU Priority = 8, Priority = 6 em Tasks\\Games."] = "SystemResponsiveness = 10 and GPU Priority = 8, Priority = 6 in Tasks\\Games.",
        ["SystemResponsiveness, NetworkThrottlingIndex e Tasks\\Games existem."] = "SystemResponsiveness, NetworkThrottlingIndex and Tasks\\Games exist.",
        ["MouseSpeed = 0 em HKCU\\Control Panel\\Mouse."] = "MouseSpeed = 0 in HKCU\\Control Panel\\Mouse.", ["VisualFXSetting = 3 e TaskbarAnimations = 0."] = "VisualFXSetting = 3 and TaskbarAnimations = 0.",
        ["DODownloadMode = 1 (ou mais restrito)."] = "DODownloadMode = 1 (or stricter).", ["Os serviços ficam com início Desativado."] = "The services get the Disabled startup type.",
        ["Fax com início Desativado."] = "Fax with Disabled startup.", ["RemoteRegistry com início Desativado."] = "RemoteRegistry with Disabled startup.", ["MapsBroker com início Desativado."] = "MapsBroker with Disabled startup.",
        ["As cinco tarefas ficam desativadas."] = "The five tasks get disabled.", ["SilentInstalledAppsEnabled e SystemPaneSuggestionsEnabled = 0."] = "SilentInstalledAppsEnabled and SystemPaneSuggestionsEnabled = 0.",
        ["EnableActivityFeed = 0 e PublishUserActivities = 0."] = "EnableActivityFeed = 0 and PublishUserActivities = 0.",
        ["AllowTelemetry = 0, DisableWindowsConsumerFeatures = 1 e DisablePushToInstall = 1."] = "AllowTelemetry = 0, DisableWindowsConsumerFeatures = 1 and DisablePushToInstall = 1.",
        ["AllowTelemetry = 1 (ou 0, mais restrito)."] = "AllowTelemetry = 1 (or 0, stricter).",
        ["Nenhum dos pacotes da lista continua instalado."] = "None of the listed packages remains installed.",
        ["O pacote Microsoft.549981C3F5F10 não está instalado."] = "The Microsoft.549981C3F5F10 package is not installed.", ["O pacote WebExperience não está instalado."] = "The WebExperience package is not installed.",
        ["O OneDrive não está mais instalado."] = "OneDrive is no longer installed.",
        ["Ação pontual: o Windows registra a última otimização em Otimizar Unidades."] = "One-off action: Windows records the last optimization in Optimize Drives.",

        // ---------- Catálogo: reversão ----------
        ["Volta ao plano anterior pela reversão ou pela página Modo Jogo."] = "Goes back to the previous plan through rollback or the Game Mode page.",
        ["A reversão religa com powercfg /h on."] = "Rollback turns it back on with powercfg /h on.", ["Remova o valor pela reversão."] = "Remove the value through rollback.",
        ["Desligue em Configurações → Jogos → Modo de Jogo."] = "Turn it off in Settings → Gaming → Game Mode.",
        ["Religue pela reversão ou em Configurações → Jogos → Capturas."] = "Turn it back on through rollback or in Settings → Gaming → Captures.",
        ["Volta ao valor anterior pela reversão (vale após reiniciar)."] = "Goes back to the previous value through rollback (takes effect after restarting).",
        ["Volta ao valor anterior pela reversão."] = "Goes back to the previous value through rollback.", ["Volta aos valores anteriores pela reversão."] = "Goes back to the previous values through rollback.",
        ["Os valores recriados ficam no backup."] = "The recreated values are in the backup.", ["A reversão devolve o tipo de início original de cada serviço."] = "Rollback restores each service's original startup type.",
        ["A reversão devolve o tipo de início."] = "Rollback restores the startup type.", ["A reversão reativa as tarefas."] = "Rollback re-enables the tasks.",
        ["A reversão remove as políticas."] = "Rollback removes the policies.", ["A reversão remove a política."] = "Rollback removes the policy.",
        ["Reinstale pela Microsoft Store."] = "Reinstall from the Microsoft Store.",
        ["No Windows 10 a reversão reinstala; no 11, baixe no site da Microsoft."] = "On Windows 10 rollback reinstalls it; on 11, download it from Microsoft's site.",
        ["Não altera configurações."] = "Doesn't change settings.", ["Não reversível (arquivos temporários)."] = "Not reversible (temporary files).",

        // ---------- Catálogo: evidência ----------
        ["Reduz a latência de troca de estados de energia da CPU. O ganho em FPS varia por jogo e processador; meça no Optimization Lab."] = "Reduces the latency of CPU power-state transitions. The FPS gain varies by game and processor; measure it in the Optimization Lab.",
        ["Ganho de espaço em disco, documentado pela Microsoft (powercfg /hibernate). Não muda desempenho."] = "Disk space gain, documented by Microsoft (powercfg /hibernate). Doesn't change performance.",
        ["Afeta principalmente processos em segundo plano; o jogo em foco já não é limitado. Benefício pequeno e variável."] = "Mainly affects background processes; the game in focus isn't throttled already. Small, variable benefit.",
        ["Recurso oficial do Windows 10/11."] = "Official Windows 10/11 feature.",
        ["A gravação contínua usa o codificador de vídeo da GPU o tempo todo. Desligar libera esse trabalho."] = "Continuous recording uses the GPU's video encoder all the time. Turning it off frees that work.",
        ["Necessário para o DLSS Frame Generation. Fora disso o efeito em FPS é pequeno e varia por driver."] = "Required for DLSS Frame Generation. Otherwise the FPS effect is small and varies by driver.",
        ["Recurso oficial do Windows 11 que reduz a latência de apresentação em janela."] = "Official Windows 11 feature that reduces presentation latency in windowed mode.",
        ["Solução conhecida para telas pretas e travadas ao sair do repouso em placas AMD. Sem efeito em FPS."] = "Known fix for black screens and stutters when waking from idle on AMD cards. No effect on FPS.",
        ["O padrão do Windows (2) já equivale a isso; o ajuste só corrige PCs alterados para \"serviços em segundo plano\"."] = "The Windows default (2) already does this; the tweak only fixes PCs changed to \"background services\".",
        ["Documentado pela Microsoft (MMCSS). O efeito em jogos modernos é pequeno; meça antes de manter."] = "Documented by Microsoft (MMCSS). The effect on modern games is small; measure before keeping it.",
        ["O limite foi criado para PCs antigos; em conexões rápidas o efeito é pequeno. Benefício não comprovado em todos os casos."] = "The limit was made for old PCs; on fast connections the effect is small. Benefit not proven in every case.",
        ["Sem esses valores o MMCSS pode não priorizar áudio e jogos."] = "Without these values MMCSS may not prioritize audio and games.",
        ["Movimento consistente é preferido em jogos de mira. Jogos com entrada direta (raw input) já ignoram a aceleração."] = "Consistent motion is preferred in aiming games. Games with raw input already ignore acceleration.",
        ["Ajuda em PCs com GPU integrada ou pouca memória; em PCs potentes a diferença é pequena."] = "Helps on PCs with integrated graphics or little memory; on powerful PCs the difference is small.",
        ["Recomendado pela Microsoft para resolver problemas de drivers e dual boot."] = "Recommended by Microsoft to solve driver and dual-boot issues.",
        ["Opção oficial da Otimização de Entrega. Evita uso de upload em segundo plano."] = "Official Delivery Optimization option. Avoids background upload.",
        ["Reduz a superfície de ataque; não muda desempenho."] = "Reduces the attack surface; doesn't change performance.",
        ["Reduz atividade em segundo plano e envio de dados. Ganho de desempenho pequeno."] = "Reduces background activity and data sending. Small performance gain.",
        ["Serviço raramente usado; desativar não muda desempenho de forma mensurável."] = "Rarely used service; disabling it doesn't change performance measurably.",
        ["Já vem desativado no Windows 10/11; reduz a superfície de ataque."] = "Already disabled on Windows 10/11; reduces the attack surface.",
        ["Serviço de uso raro; desativar não muda desempenho de forma mensurável."] = "Rarely used service; disabling it doesn't change performance measurably.",
        ["Tarefas opcionais de coleta de dados."] = "Optional data collection tasks.", ["Configurações oficiais do Gerenciador de Conteúdo do Windows."] = "Official Windows Content Delivery Manager settings.",
        ["Opção oficial de privacidade do Windows."] = "Official Windows privacy option.",
        ["Política oficial do Windows; deixa a pesquisa local mais rápida e sem envio do que você digita."] = "Official Windows policy; makes local search faster and doesn't send what you type.",
        ["Política oficial do Windows."] = "Official Windows policy.",
        ["Políticas oficiais. No Windows Home e Pro, AllowTelemetry = 0 é tratado como 1 (só obrigatório)."] = "Official policies. On Windows Home and Pro, AllowTelemetry = 0 is treated as 1 (required only).",
        ["Política oficial do Windows. No 24H2 o Copilot virou um app comum e esta política não se aplica."] = "Official Windows policy. On 24H2 Copilot became a regular app and this policy doesn't apply.",
        ["Política oficial (Windows 11 24H2 em PCs Copilot+)."] = "Official policy (Windows 11 24H2 on Copilot+ PCs).", ["Política oficial do Windows 11 24H2."] = "Official Windows 11 24H2 policy.",
        ["Libera espaço e tarefas em segundo plano desses apps."] = "Frees space and those apps' background tasks.", ["A Cortana foi descontinuada pela Microsoft."] = "Cortana was discontinued by Microsoft.",
        ["O painel carrega conteúdo da web em segundo plano."] = "The board loads web content in the background.",
        ["Remove a sincronização em segundo plano. Só faça se não usar o OneDrive."] = "Removes background sync. Only remove it if you don't use OneDrive.",
        ["Mesma tarefa que o Windows agenda semanalmente."] = "The same task Windows schedules weekly.",
        ["Resolve sites que não abrem depois de mudanças de DNS; não acelera a internet."] = "Fixes sites that don't open after DNS changes; doesn't speed up the internet.",
        ["Ferramenta oficial do Windows."] = "Official Windows tool.",

        // ---------- Catálogo: motivos de objetivo ----------
        ["Aumenta o consumo e reduz a autonomia."] = "Increases power draw and reduces battery life.", ["Consome mais energia sem ganho perceptível no uso comum."] = "Uses more power with no noticeable gain in everyday use.",
        ["Reduz a autonomia da bateria."] = "Reduces battery life.",
        ["Deixa o Windows com aparência mais simples sem ganho perceptível em PCs atuais."] = "Makes Windows look plainer with no noticeable gain on current PCs.",
        ["Em notebooks a inicialização rápida economiza tempo e bateria ao ligar."] = "On laptops Fast Startup saves time and battery when turning on.",
        ["O Relatório de Erros e os dumps ajudam a depurar programas que travam."] = "Error Reporting and dumps help debug programs that crash.",
        ["Remove o Teams e o Vincular ao Celular, usados em trabalho."] = "Removes Teams and Phone Link, used for work.", ["Pode remover apps que você usa (Teams, Clima, Celular)."] = "May remove apps you use (Teams, Weather, Phone Link).",
        ["Remove o clima e as notícias da barra de tarefas."] = "Removes the weather and news from the taskbar.",
        ["Muitos projetos e documentos ficam na pasta sincronizada."] = "Many projects and documents live in the synced folder.",
        ["Você pode depender da sincronização de fotos e documentos."] = "You may depend on photo and document sync.",

        // ---------- Catálogo: leituras ----------
        ["Ryzen X3D com dois CCDs: o Equilibrado é necessário para o jogo usar o CCD com 3D V-Cache."] = "Ryzen X3D with two CCDs: Balanced is needed for the game to use the CCD with 3D V-Cache.",
        ["Notebook: o plano atual é mantido para preservar a bateria."] = "Laptop: the current plan is kept to preserve the battery.", ["O plano Qrz está ativo."] = "The Qrz plan is active.",
        ["Outro plano personalizado está ativo (de outro programa ou do fabricante). Confira antes de trocar."] = "Another custom plan is active (from another program or the manufacturer). Check before changing it.",
        ["Plano padrão do Windows ativo."] = "Default Windows plan active.", ["Notebook: a hibernação é mantida."] = "Laptop: hibernation is kept.", ["A hibernação já está desligada."] = "Hibernation is already off.",
        ["A hibernação está ligada."] = "Hibernation is on.", ["Notebook: mantido para preservar a bateria."] = "Laptop: kept to preserve the battery.", ["Já desligado."] = "Already off.", ["Ligado (padrão do Windows)."] = "On (Windows default).",
        ["O Modo de Jogo está ligado."] = "Game Mode is on.", ["O Modo de Jogo está desligado."] = "Game Mode is off.",
        ["Ryzen X3D com dois CCDs: a Game Bar é usada pelo Windows para levar o jogo ao CCD com 3D V-Cache."] = "Ryzen X3D with two CCDs: Windows uses the Game Bar to move the game to the CCD with 3D V-Cache.",
        ["A gravação em segundo plano já está desligada."] = "Background recording is already off.", ["A gravação em segundo plano está ligada."] = "Background recording is on.",
        ["O HAGS já está ligado."] = "HAGS is already on.", ["O HAGS está desligado. O script confere se a GPU suporta antes de aplicar."] = "HAGS is off. The script checks whether the GPU supports it before applying.",
        ["Disponível apenas no Windows 11."] = "Available only on Windows 11.", ["Já ligado."] = "Already on.", ["Desligado."] = "Off.", ["Ligado."] = "On.",
        ["Sem placa de vídeo AMD."] = "No AMD graphics card.", ["O driver não usa ULPS."] = "The driver doesn't use ULPS.",
        ["O Windows já prioriza o programa em foco."] = "Windows already prioritizes the program in focus.", ["Configurado para priorizar serviços em segundo plano."] = "Set to prioritize background services.",
        ["Já configurado."] = "Already set.", ["Valores padrão do Windows."] = "Windows default values.", ["Limite padrão do Windows."] = "Windows default limit.",
        ["Os valores do MMCSS estão presentes."] = "The MMCSS values are present.", ["Faltam valores do MMCSS."] = "MMCSS values are missing.",
        ["A aceleração já está desligada."] = "Acceleration is already off.", ["A aceleração está ligada."] = "Acceleration is on.",
        ["Já ajustados."] = "Already adjusted.", ["Efeitos padrão do Windows."] = "Windows default effects.", ["Já desligada."] = "Already off.", ["Ligada."] = "On.",
        ["O envio pela internet já está bloqueado."] = "Sending over the internet is already blocked.", ["Padrão do Windows."] = "Windows default.",
        ["Os serviços não existem neste Windows."] = "The services don't exist on this Windows.", ["Serviços já desativados."] = "Services already disabled.",
        ["Não foi possível consultar os apps da Loja."] = "Could not query the Store apps.", ["Não foi possível consultar as tarefas agendadas."] = "Could not query the scheduled tasks.",
        ["As tarefas não existem neste Windows."] = "The tasks don't exist on this Windows.", ["As tarefas já estão desativadas."] = "The tasks are already disabled.",
        ["Já desligados."] = "Already off.", ["Sugestões e instalações automáticas ligadas."] = "Suggestions and automatic installs on.", ["Resultados da web ligados."] = "Web results on.",
        ["Já aplicadas."] = "Already applied.", ["Políticas não aplicadas."] = "Policies not applied.",
        ["A telemetria já está no nível obrigatório ou abaixo."] = "Telemetry is already at the required level or below.", ["Dados opcionais permitidos."] = "Optional data allowed.", ["Permitido."] = "Allowed.",
        ["Nenhum app da lista está instalado."] = "None of the listed apps is installed.", ["A Cortana não está instalada."] = "Cortana is not installed.", ["Os Widgets não estão instalados."] = "Widgets are not installed.",
        ["Instalado. Confira se você usa a sincronização antes de remover."] = "Installed. Check whether you use sync before removing it.", ["O OneDrive não está instalado."] = "OneDrive is not installed.",
        ["Não se aplica a este PC (versão do Windows, placa de vídeo ou tipo de PC)."] = "Doesn't apply to this PC (Windows version, graphics card or PC type).",

        // ---------- Performance Lab ----------
        ["Captura"] = "Capture", ["Histórico"] = "History", ["Comparar"] = "Compare", ["gravando"] = "recording",
        ["PresentMon não configurado"] = "PresentMon not configured", ["PresentMon pronto"] = "PresentMon ready", ["Escolher PresentMon"] = "Choose PresentMon", ["Trocar PresentMon"] = "Change PresentMon",
        ["Baixar no GitHub oficial"] = "Download from the official GitHub",
        ["FPS e frametime vêm do PresentMon, a ferramenta aberta da Intel que lê a apresentação real dos quadros. Sem ele, a captura grava só os sensores e não mostra FPS (nada é estimado)."] = "FPS and frametime come from PresentMon, Intel's open tool that reads the real frame presentation. Without it, the capture records only the sensors and shows no FPS (nothing is estimated).",
        ["FPS, 1% low, 0,1% low e frametime são calculados dos quadros reais do jogo. O PresentMon roda a partir de uma cópia na pasta protegida do app."] = "FPS, 1% low, 0.1% low and frametime are calculated from the game's real frames. PresentMon runs from a copy in the app's protected folder.",
        ["Pronto para capturar FPS e frametime."] = "Ready to capture FPS and frametime.",
        ["Nova captura"] = "New capture",
        ["Abra o jogo, escolha o processo e comece a gravar. Volte ao jogo: a captura continua em segundo plano e para sozinha no tempo escolhido."] = "Open the game, choose the process and start recording. Go back to the game: the capture keeps running in the background and stops by itself at the chosen time.",
        ["Atualizar lista"] = "Refresh list", ["Processo do jogo"] = "Game process", ["Duração"] = "Duration", ["Nome do teste (opcional)"] = "Test name (optional)", ["Iniciar captura"] = "Start capture", ["Parar captura"] = "Stop capture", ["Ao vivo"] = "Live",
        ["Valores lidos a cada segundo. FPS só aparece com o PresentMon capturando o processo escolhido."] = "Values read every second. FPS only shows with PresentMon capturing the chosen process.",
        ["Temperatura da GPU"] = "GPU temperature", ["Parado."] = "Stopped.", ["Gravando..."] = "Recording...", ["Nome de processo inválido."] = "Invalid process name.",
        ["Captura concluída e salva no histórico."] = "Capture finished and saved to history.", ["Captura salva (sem FPS: só sensores)."] = "Capture saved (no FPS: sensors only).",
        ["FPS médio"] = "Average FPS", ["FPS mínimo"] = "Minimum FPS", ["Frametime médio"] = "Average frametime", ["Frametime P95 / P99"] = "Frametime P95 / P99", ["Frametime P95"] = "Frametime P95", ["Frametime P99"] = "Frametime P99",
        ["CPU / GPU"] = "CPU / GPU", ["Clock / potência da GPU"] = "GPU clock / power", ["Clock da CPU (estimado)"] = "CPU clock (estimated)", ["Limite de desempenho"] = "Performance limit",
        ["não detectado"] = "not detected", ["indisponível"] = "unavailable", ["sem processo"] = "no process", ["Só sensores"] = "Sensors only", ["só sensores"] = "sensors only", ["CSV importado"] = "Imported CSV", ["sem FPS"] = "no FPS",
        ["Sem FPS: a captura não teve quadros do PresentMon (ferramenta não configurada, processo errado ou menos de 100 quadros). Os números de FPS não são estimados a partir de outras métricas."] = "No FPS: the capture had no PresentMon frames (tool not configured, wrong process or fewer than 100 frames). FPS numbers are not estimated from other metrics.",
        ["CPU sem temperatura: ler a temperatura da CPU exige um driver de kernel que o Qrztweaks não instala."] = "No CPU temperature: reading it requires a kernel driver that Qrztweaks doesn't install.",
        ["Exportar CSV"] = "Export CSV", ["Exportar JSON"] = "Export JSON", ["Relatório PDF"] = "PDF report", ["Exportado"] = "Exported", ["Exportação"] = "Export",
        ["Qrztweaks · Relatório do Performance Lab"] = "Qrztweaks · Performance Lab report", ["Métrica"] = "Metric", ["Valor"] = "Value", ["Antes"] = "Before", ["Depois"] = "After", ["Diferença"] = "Difference",
        ["FPS e frametime vêm de dados reais de apresentação de quadros (PresentMon). Métricas ausentes não foram medidas."] = "FPS and frametime come from real frame presentation data (PresentMon). Missing metrics were not measured.",
        ["Histórico de testes"] = "Test history", ["Nenhum teste salvo ainda."] = "No tests saved yet.", ["Importar CSV"] = "Import CSV", ["Ver"] = "View",
        ["Importar um log do PresentMon ou do CapFrameX"] = "Import a PresentMon or CapFrameX log", ["Importação"] = "Import",
        ["O log não tem quadros suficientes do processo principal."] = "The log doesn't have enough frames from the main process.",
        ["Comparação antes/depois"] = "Before/after comparison",
        ["Escolha dois testes. A comparação mostra a diferença absoluta e percentual e avisa quando as condições não são as mesmas."] = "Choose two tests. The comparison shows the absolute and percent difference and warns when the conditions aren't the same.",
        ["Grave pelo menos dois testes para comparar."] = "Record at least two tests to compare.", ["Condições diferentes"] = "Different conditions", ["Hardware diferente."] = "Different hardware.",
        ["Os dois testes não têm métricas em comum."] = "The two tests have no metrics in common.",
        ["Uma única gravação de cada lado não prova ganho: diferenças de poucos por cento estão dentro da variação normal. Para decidir sobre um ajuste, use o Optimization Lab (várias gravações e teste estatístico)."] = "A single recording on each side doesn't prove a gain: differences of a few percent are within normal variation. To decide on a tweak, use the Optimization Lab (several recordings and a statistical test).",
        ["Relatório PDF da comparação"] = "Comparison PDF report", ["Condições dos testes"] = "Test conditions",
        ["Uso de CPU"] = "CPU usage", ["Uso de GPU"] = "GPU usage", ["Temperatura da GPU (máx.)"] = "GPU temperature (max)", ["Clock da GPU"] = "GPU clock", ["Potência da GPU"] = "GPU power",

        // ---------- Optimization Lab ----------
        ["Mede o efeito de um ajuste por vez: grave a mesma cena algumas vezes, aplique o ajuste, grave de novo e compare. Uma diferença só conta como ganho se for consistente e maior que 3%."] = "Measures the effect of one tweak at a time: record the same scene a few times, apply the tweak, record again and compare. A difference only counts as a gain if it is consistent and larger than 3%.",
        ["1. Grave a referência  ·  2. Aplique um ajuste reversível  ·  3. Grave depois  ·  4. Mantenha ou reverta"] = "1. Record the baseline  ·  2. Apply a reversible tweak  ·  3. Record after  ·  4. Keep or revert",
        ["Sem o PresentMon, o Lab não mede FPS e o resultado fica limitado ao uso de CPU. Configure-o na aba Captura."] = "Without PresentMon, the Lab doesn't measure FPS and the result is limited to CPU usage. Set it up in the Capture tab.",
        ["Começar experimento"] = "Start experiment", ["Escolha o processo do jogo."] = "Choose the game process.",
        ["Ajuste aplicado"] = "Tweak applied", ["Ajuste ainda não aplicado"] = "Tweak not applied yet", ["Gravar referência"] = "Record baseline", ["Aplicar o ajuste"] = "Apply the tweak",
        ["Gravar depois"] = "Record after", ["Encerrar experimento"] = "End experiment", ["Gravando... volte ao jogo."] = "Recording... go back to the game.",
        ["Gravando... volte ao jogo e repita a mesma cena."] = "Recording... go back to the game and repeat the same scene.",
        ["Este ajuste só vale depois de reiniciar. Reinicie, abra o app e continue o experimento (ele fica guardado enquanto o app estiver aberto; gravações já feitas ficam no histórico)."] = "This tweak only takes effect after a restart. Restart, open the app and continue the experiment (it is kept while the app is open; recordings already made stay in history).",
        ["Resultado"] = "Result", ["Provável ganho"] = "Likely gain", ["Provável perda"] = "Likely loss", ["Sem diferença comprovada"] = "No proven difference", ["Dados insuficientes"] = "Not enough data",
        ["Manter"] = "Keep", ["Reverter o ajuste"] = "Revert the tweak", ["Atenção"] = "Attention",
        ["Grave mais vezes antes de decidir."] = "Record more times before deciding.",
        ["Sem quadros reais (PresentMon) em todas as gravações: o resultado usa só o uso de CPU e não diz nada sobre FPS."] = "No real frames (PresentMon) in every recording: the result uses only CPU usage and says nothing about FPS.",
        ["Nem todas as gravações são do mesmo processo."] = "Not all recordings are from the same process.",
        ["A resolução ou a taxa de atualização mudou entre as gravações."] = "The resolution or refresh rate changed between recordings.", ["O driver de vídeo mudou entre as gravações."] = "The graphics driver changed between recordings.",
        ["O Windows informou limite de desempenho da CPU (térmico ou de energia) em alguma gravação."] = "Windows reported a CPU performance limit (thermal or power) in some recording.",
        ["Manter o ajuste: a melhora foi consistente nas gravações."] = "Keep the tweak: the improvement was consistent across recordings.",
        ["Provável melhora, mas confira os avisos antes de considerar comprovado."] = "Likely improvement, but check the warnings before considering it proven.",
        ["Reverter o ajuste: o desempenho piorou de forma consistente."] = "Revert the tweak: performance got consistently worse.",

        // ---------- Diagnóstico inteligente ----------
        ["Diagnóstico inteligente"] = "Smart diagnostics", ["Analisar desempenho"] = "Analyze performance",
        ["Analisa o último teste do Performance Lab, o monitor ao vivo, discos, processos, energia e drivers. Cada conclusão mostra a evidência e o grau de confiança; sem dados suficientes, nada é afirmado."] = "Analyzes the last Performance Lab test, the live monitor, disks, processes, power and drivers. Each conclusion shows the evidence and the confidence level; without enough data, nothing is claimed.",
        ["Coletando dados (alguns segundos)..."] = "Collecting data (a few seconds)...", ["Nenhum problema encontrado"] = "No problems found",
        ["Com os dados disponíveis, nada indica gargalo ou problema. Veja abaixo o que não pôde ser avaliado."] = "With the available data, nothing indicates a bottleneck or problem. See below what couldn't be evaluated.",
        ["Não avaliado por falta de dados"] = "Not evaluated for lack of data", ["Abrir o Performance Lab"] = "Open the Performance Lab",
        ["Crítico"] = "Critical", ["Informativo"] = "Informational", ["Confiança alta"] = "High confidence", ["Confiança média"] = "Medium confidence", ["Confiança baixa"] = "Low confidence",
        ["Evidências"] = "Evidence", ["Possíveis causas"] = "Possible causes", ["Recomendações"] = "Recommendations", ["Como confirmar"] = "How to confirm", ["Riscos"] = "Risks",
        ["Sem um teste do Performance Lab de pelo menos 20 segundos: limitações de CPU e GPU não podem ser avaliadas."] = "No Performance Lab test of at least 20 seconds: CPU and GPU limits can't be evaluated.",
        ["O Windows não informou o uso da GPU no último teste: gargalo de GPU não avaliado."] = "Windows didn't report GPU usage in the last test: GPU bottleneck not evaluated.",
        ["Poucas leituras de memória: deixe o monitor ao vivo rodando por alguns segundos."] = "Few memory readings: leave the live monitor running for a few seconds.",
        ["Limitado pela placa de vídeo no último teste"] = "Limited by the graphics card in the last test",
        ["A GPU é o componente mais exigido nessa configuração do jogo (o esperado em jogos pesados)."] = "The GPU is the most demanded component in this game setup (expected in heavy games).",
        ["Reduza a resolução ou as opções gráficas mais pesadas, ou ative DLSS/FSR/XeSS."] = "Lower the resolution or the heaviest graphics options, or turn on DLSS/FSR/XeSS.",
        ["Otimizações do Windows quase não mudam esse cenário."] = "Windows optimizations barely change this scenario.",
        ["Baixe a resolução: se o FPS subir na mesma proporção, a GPU era o limite."] = "Lower the resolution: if FPS rises in proportion, the GPU was the limit.",
        ["Nenhum: é uma leitura, não um problema."] = "None: it's a reading, not a problem.", ["Nenhum: é uma leitura."] = "None: it's a reading.",
        ["Possível limitação de CPU no último teste"] = "Possible CPU limit in the last test", ["Jogo limitado por um núcleo da CPU."] = "Game limited by one CPU core.",
        ["Limite de FPS no jogo ou no driver."] = "FPS cap in the game or the driver.", ["Memória lenta (XMP/EXPO desligado) ou processos em segundo plano."] = "Slow memory (XMP/EXPO off) or background processes.",
        ["Confira se não há limite de FPS ou V-Sync ligado."] = "Check that there's no FPS cap or V-Sync on.", ["Feche programas em segundo plano (Modo Jogo)."] = "Close background programs (Game Mode).",
        ["Confira no BIOS Advisor se o perfil XMP/EXPO está ativo."] = "Check in the BIOS Advisor whether the XMP/EXPO profile is active.",
        ["Baixe a resolução: se o FPS não mudar, a CPU (ou um limite) é o gargalo."] = "Lower the resolution: if FPS doesn't change, the CPU (or a cap) is the bottleneck.",
        ["A CPU foi limitada durante o teste"] = "The CPU was limited during the test", ["Temperatura alta (cooler, pasta térmica, poeira)."] = "High temperature (cooler, thermal paste, dust).",
        ["Limite de energia da placa-mãe ou do plano de energia."] = "Power limit from the motherboard or the power plan.", ["Limpe o cooler e confira a pasta térmica."] = "Clean the cooler and check the thermal paste.",
        ["Confira o plano de energia e, no BIOS Advisor, os limites de energia."] = "Check the power plan and, in the BIOS Advisor, the power limits.",
        ["Repita o teste com o gabinete aberto ou ventoinhas no máximo: se o limite sumir, é térmico."] = "Repeat the test with the case open or fans at maximum: if the limit goes away, it's thermal.",
        ["Limpeza interna exige cuidado com eletricidade estática."] = "Internal cleaning requires care with static electricity.",
        ["A placa de vídeo reduziu o clock no teste"] = "The graphics card lowered its clock in the test", ["Temperatura ou limite de energia da placa."] = "Card temperature or power limit.",
        ["Melhore o fluxo de ar do gabinete e limpe a placa."] = "Improve case airflow and clean the card.", ["Confira se os cabos de energia da GPU estão bem conectados."] = "Check that the GPU power cables are firmly connected.",
        ["Acompanhe temperatura e clock no Performance Lab durante uma partida longa."] = "Watch temperature and clock in the Performance Lab during a long match.",
        ["Undervolt e mudanças de curva de ventoinha ficam por sua conta: o app não altera a GPU."] = "Undervolting and fan curve changes are up to you: the app doesn't change the GPU.",
        ["Memória RAM quase toda em uso"] = "RAM almost fully used", ["Programas demais abertos (navegador com muitas abas é comum)."] = "Too many programs open (a browser with many tabs is common).",
        ["Pouca memória instalada para o uso atual."] = "Too little memory installed for the current use.", ["Algum programa usando memória fora do normal."] = "Some program using an abnormal amount of memory.",
        ["Feche programas que não está usando; confira o Gerenciador de Tarefas por uso de memória."] = "Close programs you're not using; check Task Manager by memory usage.",
        ["Para jogos atuais, 16 GB é o mínimo confortável."] = "For current games, 16 GB is the comfortable minimum.", ["Reinicie o programa que mais consome."] = "Restart the program that uses the most.",
        ["Abra o Gerenciador de Tarefas → Memória e veja o que mais consome."] = "Open Task Manager → Memory and see what uses the most.",
        ["Pouco espaço livre no disco do Windows"] = "Little free space on the Windows drive", ["Arquivos temporários, jogos grandes ou atualizações antigas do Windows."] = "Temporary files, large games or old Windows updates.",
        ["Use a Limpeza rápida e a limpeza de componentes do Windows."] = "Use Quick cleanup and Windows component cleanup.", ["Mova jogos para outra unidade."] = "Move games to another drive.",
        ["Configurações → Sistema → Armazenamento mostra o que ocupa o disco."] = "Settings → System → Storage shows what takes up the disk.", ["Apagar arquivos é definitivo: revise antes."] = "Deleting files is permanent: review first.",
        ["Desgaste ou falha física do disco."] = "Disk wear or physical failure.", ["Faça backup dos seus arquivos agora."] = "Back up your files now.",
        ["Confira o SMART com a ferramenta do fabricante e planeje a troca."] = "Check SMART with the manufacturer's tool and plan a replacement.",
        ["Use a ferramenta do fabricante do disco (ou CrystalDiskInfo) para ver os atributos SMART."] = "Use the disk manufacturer's tool (or CrystalDiskInfo) to see the SMART attributes.",
        ["Continuar usando um disco com falha pode causar perda de dados."] = "Continuing to use a failing disk can cause data loss.",
        ["O Windows está num HD mecânico"] = "Windows is on a mechanical hard drive", ["HDs têm acesso aleatório muito mais lento que SSDs."] = "HDDs have much slower random access than SSDs.",
        ["Um SSD para o Windows e os jogos é a melhoria de maior impacto em inicialização e carregamentos."] = "An SSD for Windows and games is the highest-impact improvement for boot and loading times.",
        ["Gerenciador de Tarefas → Desempenho mostra o tipo de cada disco."] = "Task Manager → Performance shows each disk's type.", ["A migração exige clonar o disco ou reinstalar o Windows."] = "Migrating requires cloning the disk or reinstalling Windows.",
        ["Programas usando CPU em segundo plano"] = "Programs using CPU in the background", ["Atualizações, antivírus, sincronização na nuvem ou um programa travado."] = "Updates, antivirus, cloud sync or a stuck program.",
        ["Feche o que não precisa antes de jogar ou use o Modo Jogo, que pausa programas em segundo plano."] = "Close what you don't need before playing or use Game Mode, which pauses background programs.",
        ["Gerenciador de Tarefas → Processos, ordenado por CPU, por alguns minutos."] = "Task Manager → Processes, sorted by CPU, for a few minutes.",
        ["Encerrar processos do sistema pode travar o Windows; feche só programas conhecidos."] = "Ending system processes can crash Windows; close only programs you know.",
        ["Muitos programas iniciando com o Windows"] = "Many programs starting with Windows", ["Programas que se adicionam à inicialização ao serem instalados."] = "Programs that add themselves to startup when installed.",
        ["Desative os que não precisa na página Inicialização (é reversível)."] = "Disable the ones you don't need on the Startup page (it's reversible).", ["Página Inicialização lista cada item e o impacto."] = "The Startup page lists each item and its impact.",
        ["Desativar drivers ou antivírus pode tirar funções; o app avisa quais são do Windows."] = "Disabling drivers or antivirus can remove features; the app shows which ones belong to Windows.",
        ["Quantidade alta de processos"] = "High number of processes", ["Muitos programas abertos ou serviços de terceiros."] = "Many programs open or third-party services.",
        ["Confira o que está aberto e o que inicia com o Windows."] = "Check what's open and what starts with Windows.", ["Gerenciador de Tarefas → Detalhes."] = "Task Manager → Details.",
        ["Plano Economia de energia ativo na tomada"] = "Power saver plan active while plugged in", ["Plano escolhido manualmente ou por um programa do fabricante."] = "Plan chosen manually or by a manufacturer program.",
        ["Use Equilibrado (ou o plano Qrz em desktops) quando estiver na tomada."] = "Use Balanced (or the Qrz plan on desktops) when plugged in.", ["Painel de Controle → Opções de Energia."] = "Control Panel → Power Options.", ["Mais consumo de energia."] = "More power consumption.",
        ["Driver ausente, corrompido ou incompatível."] = "Missing, corrupted or incompatible driver.", ["Instale o driver do fabricante (página Drivers)."] = "Install the manufacturer's driver (Drivers page).",
        ["Remova dispositivos fantasmas que não usa mais."] = "Remove ghost devices you no longer use.", ["Gerenciador de Dispositivos mostra um aviso amarelo nesses itens."] = "Device Manager shows a yellow warning on these items.",
        ["Instale drivers só de fontes oficiais."] = "Install drivers only from official sources.",
        ["Driver de vídeo com mais de um ano"] = "Graphics driver older than one year", ["Driver não atualizado."] = "Driver not updated.",
        ["Atualize pelo site do fabricante (NVIDIA, AMD ou Intel). A página Drivers tem os links e a instalação limpa."] = "Update from the manufacturer's site (NVIDIA, AMD or Intel). The Drivers page has the links and the clean install.",
        ["Compare a versão instalada com a mais recente no site do fabricante."] = "Compare the installed version with the latest on the manufacturer's site.",
        ["Drivers novos às vezes trazem problemas; a instalação limpa ajuda a voltar."] = "New drivers sometimes bring problems; the clean install helps you go back.",
        ["A CPU está limitada agora"] = "The CPU is limited right now", ["Temperatura, limite de energia ou plano de economia."] = "Temperature, power limit or power-saving plan.",
        ["Grave um teste no Performance Lab durante uma carga real para confirmar."] = "Record a Performance Lab test under a real load to confirm.", ["Teste longo no Performance Lab."] = "Long test in the Performance Lab.",
        ["Windows sem reiniciar há muito tempo"] = "Windows hasn't restarted in a long time", ["Atualizações e vazamentos de memória se acumulam."] = "Updates and memory leaks pile up.",
        ["Reinicie (Reiniciar, não Desligar) de vez em quando."] = "Restart (Restart, not Shut down) now and then.", ["Gerenciador de Tarefas → Desempenho → CPU mostra o tempo ligado."] = "Task Manager → Performance → CPU shows the uptime.",
        ["sem FPS medido"] = "no FPS measured", ["processo não informado"] = "process not reported", ["Ação pontual."] = "One-off action.",
        // Motivos de redução de clock da NVIDIA (guardados em português no resultado)
        ["Limite de energia (power cap)"] = "Power limit (power cap)", ["Temperatura (software)"] = "Temperature (software)", ["Temperatura (hardware)"] = "Temperature (hardware)",
        ["Proteção de hardware"] = "Hardware slowdown", ["Freio de energia da fonte"] = "Power brake (PSU)", ["Outro motivo informado pelo driver"] = "Other reason reported by the driver",

        // ---------- Perfis ----------
        ["Perfis personalizados"] = "Custom profiles", ["Novo perfil"] = "New profile", ["Importar"] = "Import", ["Editar"] = "Edit", ["Duplicar"] = "Duplicate", ["Exportar"] = "Export", ["Excluir"] = "Delete", ["Aplicar"] = "Apply",
        ["Cada perfil guarda um objetivo, os ajustes do catálogo e os jogos. Perfis só contêm dados: nenhum script é salvo ou executado a partir deles."] = "Each profile stores a goal, catalog tweaks and games. Profiles contain only data: no script is saved in or run from them.",
        ["Ativar ao abrir um jogo"] = "Activate when a game opens",
        ["Quando um jogo de um perfil com \"Modo Jogo automático\" abrir, o Modo Jogo temporário liga sozinho e é restaurado quando o jogo fechar. O app só lê a lista de processos: nada é injetado no jogo."] = "When a game from a profile with \"Automatic Game Mode\" opens, temporary Game Mode turns on by itself and is restored when the game closes. The app only reads the process list: nothing is injected into the game.",
        ["Modo Jogo automático"] = "Automatic Game Mode", ["Restaurar"] = "Restore",
        ["Os ajustes de um perfil são aplicados pelo Smart Optimize, com backup de cada item. Para desfazer, use Atividade e reversão."] = "A profile's tweaks are applied by Smart Optimize, with a backup of each item. To undo, use Activity and rollback.",
        ["Abrir Atividade e reversão"] = "Open Activity and rollback", ["Editar perfil"] = "Edit profile", ["Nome"] = "Name", ["Até 60 caracteres."] = "Up to 60 characters.", ["Descrição"] = "Description", ["Opcional."] = "Optional.",
        ["Objetivo"] = "Goal", ["Usado nas recomendações do Smart Optimize."] = "Used in Smart Optimize recommendations.", ["Processos dos jogos"] = "Game processes",
        ["Nomes dos executáveis, separados por vírgula."] = "Executable names, separated by commas.",
        ["Liga o Modo Jogo temporário quando um dos jogos abrir (requer \"Ativar ao abrir um jogo\")."] = "Turns on temporary Game Mode when one of the games opens (requires \"Activate when a game opens\").",
        ["Fechar programas em segundo plano"] = "Close background programs", ["No Modo Jogo automático, fecha os programas da lista do Modo Jogo que estiverem abertos."] = "In automatic Game Mode, closes the open programs from the Game Mode list.",
        ["Pausar serviços"] = "Pause services", ["Pausa os serviços marcados por padrão no Modo Jogo."] = "Pauses the services checked by default in Game Mode.",
        ["Plano de alto desempenho"] = "High performance plan", ["Troca o plano de energia durante o jogo."] = "Switches the power plan while gaming.",
        ["Liberar memória em espera"] = "Free standby memory", ["Limpa a memória em espera ao iniciar."] = "Clears standby memory when starting.", ["Ajustes do perfil"] = "Profile tweaks",
        ["Salvar"] = "Save", ["Perfil salvo."] = "Profile saved.", ["Dê um nome ao perfil."] = "Give the profile a name.", ["Perfil exportado"] = "Profile exported", ["Perfil importado"] = "Profile imported",
        ["Nome encurtado."] = "Name shortened.", ["O perfil não tem nome."] = "The profile has no name.", ["Objetivo do perfil inválido."] = "Invalid profile goal.",
        ["Arquivo grande demais para ser um perfil."] = "File too large to be a profile.", ["O arquivo está vazio."] = "The file is empty.", ["Arquivo não encontrado."] = "File not found.",
        ["Modo Jogo restaurado"] = "Game Mode restored", ["Modo Jogo temporário ativado. Ele é restaurado quando o jogo fechar."] = "Temporary Game Mode turned on. It is restored when the game closes.",
        ["O jogo fechou e os ajustes temporários foram desfeitos."] = "The game closed and the temporary tweaks were undone.",
        ["Competitivo: Modo Jogo, sem gravação em segundo plano e entrada consistente."] = "Competitive: Game Mode, no background recording and consistent input.",
        ["Competitivo: os mesmos ajustes do Valorant para o Counter-Strike 2."] = "Competitive: the same tweaks as Valorant for Counter-Strike 2.",
        ["Competitivo, com HAGS (útil para Frame Generation)."] = "Competitive, with HAGS (useful for Frame Generation).", ["Streaming"] = "Streaming",
        ["Jogar e transmitir: mantém o codificador livre, sem fechar o OBS."] = "Play and stream: keeps the encoder free, without closing OBS.",
        ["Preserva Docker, WSL e Hyper-V; só privacidade e estabilidade."] = "Preserves Docker, WSL and Hyper-V; only privacy and stability.",
        ["Temperatura e bateria: sem ajustes que aumentam o consumo."] = "Temperature and battery: no tweaks that increase power draw.", ["Privacidade, menos anúncios e limpeza segura."] = "Privacy, fewer ads and safe cleanup.",

        // ---------- Command Center ----------
        ["Computador"] = "Computer", ["Perfil ativo"] = "Active profile", ["Nenhum objetivo analisado"] = "No goal analyzed", ["nenhum objetivo analisado"] = "no goal analyzed",
        ["OTIMIZAÇÕES ATIVAS"] = "ACTIVE OPTIMIZATIONS", ["ÚLTIMA ANÁLISE"] = "LAST ANALYSIS", ["ÚLTIMO TESTE"] = "LAST TEST", ["ALERTAS"] = "ALERTS", ["TEMPERATURAS"] = "TEMPERATURES",
        ["Analise o PC para ver"] = "Analyze the PC to see", ["Nenhuma ainda"] = "None yet", ["Nenhum teste no Performance Lab"] = "No test in the Performance Lab", ["Nenhum alerta"] = "No alerts",
        ["Abrir o Smart Optimize"] = "Open Smart Optimize", ["Restauração do Modo Jogo pendente"] = "Game Mode restore pending", ["A licença vence hoje"] = "The license expires today",
        ["Ações rápidas"] = "Quick actions", ["Diagnóstico"] = "Diagnostics", ["Modo compacto"] = "Compact mode",
        ["Analisar o PC e revisar os ajustes recomendados"] = "Analyze the PC and review the recommended tweaks", ["Sessão de jogo temporária, restaurada ao desativar"] = "Temporary game session, restored when turned off",
        ["Medir FPS, frametime e sensores"] = "Measure FPS, frametime and sensors", ["Backups, reversão e pontos de restauração"] = "Backups, rollback and restore points",
        ["Diagnóstico inteligente e verificação do Windows"] = "Smart diagnostics and Windows check",
        ["Janela pequena com CPU, GPU, RAM e temperaturas, para um segundo monitor"] = "Small window with CPU, GPU, RAM and temperatures, for a second monitor",
        ["GPU: sensor indisponível"] = "GPU: sensor unavailable", ["CPU: requer driver de kernel"] = "CPU: requires a kernel driver", ["Lendo..."] = "Reading...",
        ["Temperatura da GPU lida pelo driver NVIDIA. A da CPU exige um driver de kernel que o Qrztweaks não instala, por segurança."] = "GPU temperature read by the NVIDIA driver. The CPU's requires a kernel driver that Qrztweaks doesn't install, for safety.",
        ["Modo demonstração"] = "Demo mode", ["Ativar licença"] = "Activate license",
        ["Veja o hardware, o monitor, o diagnóstico, o Performance Lab e as recomendações do Smart Optimize. Para aplicar qualquer ajuste, ative uma licença."] = "See the hardware, the monitor, diagnostics, the Performance Lab and Smart Optimize recommendations. To apply any tweak, activate a license.",

        // ---------- Aparência ----------
        ["Meia-noite"] = "Midnight", ["Seguir a redução de movimento do Windows"] = "Follow Windows reduced motion",
        ["Desliga as animações quando \"Mostrar animações no Windows\" estiver desligado. Fica desligado por padrão porque o ajuste de efeitos visuais do próprio app desliga essa opção do Windows."] = "Turns animations off when \"Show animations in Windows\" is off. Off by default because the app's own visual effects tweak turns that Windows option off.",
        ["Barra lateral compacta"] = "Compact sidebar", ["Mostra só os ícones; o nome de cada página aparece ao passar o mouse. Também alterna com Ctrl+B."] = "Shows only the icons; each page's name appears on hover. Also toggles with Ctrl+B.",
        ["Escolha o que aparece na página inicial."] = "Choose what appears on the home page.", ["Status e alertas"] = "Status and alerts",
        ["Otimizações ativas, última análise, último teste e alertas."] = "Active optimizations, last analysis, last test and alerts.",
        ["Smart Optimize, Modo Jogo, Performance Lab, Restaurar e Diagnóstico."] = "Smart Optimize, Game Mode, Performance Lab, Restore and Diagnostics.",
        ["Monitor em tempo real"] = "Real-time monitor", ["Gráficos de CPU, GPU, memória e rede."] = "CPU, GPU, memory and network charts.",
        ["Cards de hardware"] = "Hardware cards", ["Processador, memória, disco, placa de vídeo e temperaturas."] = "Processor, memory, disk, graphics card and temperatures.",
        ["Atividade recente"] = "Recent activity", ["Leitura rápida e as últimas operações."] = "Quick reading and the latest operations.",

        // ---------- Modo compacto ----------
        ["Temp."] = "Temp.", ["Sempre no topo"] = "Always on top", ["Fechar"] = "Close", ["Modo Jogo desligado"] = "Game Mode off", ["Modo Jogo: restauração pendente"] = "Game Mode: restore pending",
        ["FPS só aparece durante uma captura do Performance Lab com o PresentMon."] = "FPS only shows during a Performance Lab capture with PresentMon.",
        ["Sem sensor de temperatura disponível (só GPUs NVIDIA pelo driver)."] = "No temperature sensor available (only NVIDIA GPUs through the driver).", ["Qrztweaks · Modo compacto"] = "Qrztweaks · Compact mode",

        // ---------- Licença e ativação ----------
        ["Planos"] = "Plans", ["Ver planos no site"] = "See plans on the website", ["Troquei de PC / reinstalei o Windows"] = "I changed PCs / reinstalled Windows",
        ["Explorar sem licença"] = "Explore without a license", ["Esta chave pertence a outro computador."] = "This key belongs to another computer.",
        ["Se você trocou de PC ou reinstalou o Windows, o ID mudou. Clique em \"Troquei de PC / reinstalei o Windows\" para copiar o pedido de transferência e envie no Discord."] = "If you changed PCs or reinstalled Windows, the ID changed. Click \"I changed PCs / reinstalled Windows\" to copy the transfer request and send it on Discord.",
        ["Pedido de transferência copiado. No Discord, abra um ticket, cole o pedido e informe o motivo."] = "Transfer request copied. On Discord, open a ticket, paste the request and give the reason.",
        ["A compra e a ativação são feitas pelo Discord, com pagamento via Pix."] = "Purchase and activation happen on Discord, with payment via Pix.",
        ["Copia um pedido de transferência com o novo ID deste computador"] = "Copies a transfer request with this computer's new ID",
        ["Modo demonstração: veja o hardware, o monitor, o diagnóstico e as recomendações. Nada é aplicado sem licença."] = "Demo mode: see the hardware, the monitor, diagnostics and the recommendations. Nothing is applied without a license.",
        ["Aberto em modo demonstração (sem licença)"] = "Opened in demo mode (no license)",

        // ---------- Patch notes 2.0.0 ----------
        ["Smart Optimize: analisa o PC, lê o estado de cada ajuste e recomenda pelo objetivo (gaming competitivo, notebook, programação, uso diário ou personalizado), com risco, reversão e evidência de cada item."] = "Smart Optimize: analyzes the PC, reads the state of each tweak and recommends by goal (competitive gaming, laptop, development, daily use or custom), with the risk, rollback and evidence of each item.",
        ["Depois de aplicar, o estado é lido de novo no Windows: um ajuste só aparece como concluído quando a mudança é confirmada."] = "After applying, the state is read again from Windows: a tweak only shows as done when the change is confirmed.",
        ["Performance Lab: FPS médio, mínimo, 1% low, 0,1% low e frametime P95/P99 pelo PresentMon, sensores a cada segundo, histórico, comparação antes/depois e exportação em CSV, JSON e PDF."] = "Performance Lab: average, minimum, 1% low and 0.1% low FPS and P95/P99 frametime through PresentMon, per-second sensors, history, before/after comparison and CSV, JSON and PDF export.",
        ["Optimization Lab: testa um ajuste por vez com várias gravações; diferenças pequenas aparecem como sem diferença comprovada."] = "Optimization Lab: tests one tweak at a time with several recordings; small differences show as no proven difference.",
        ["Diagnóstico inteligente com evidências e grau de confiança, Command Center com alertas e ações rápidas, modo compacto para segundo monitor e perfis por jogo."] = "Smart diagnostics with evidence and confidence level, Command Center with alerts and quick actions, compact mode for a second monitor and per-game profiles.",
        ["Segurança: atualizações com hash assinado, exclusões amplas do Defender recusadas, BIOS validada antes de gravar e aviso de operação interrompida."] = "Security: updates with a signed hash, broad Defender exclusions refused, BIOS validated before writing and a notice for interrupted operations.",
        ["Modo demonstração sem licença (só leitura) e pedido de transferência para quem trocou de PC ou reinstalou o Windows."] = "Demo mode without a license (read-only) and a transfer request for anyone who changed PCs or reinstalled Windows.",

        // ---------- Atualizações ----------
        ["Instalador verificado por SHA256 e pela assinatura do Qrztweaks, pronto para atualizar."] = "Installer verified by SHA256 and the Qrztweaks signature, ready to update.",
        ["Instalador verificado por SHA256 e assinatura; configurações preservadas."] = "Installer verified by SHA256 and signature; settings preserved.",
        ["Esta versão não publica o hash assinado do instalador. Baixe pela página de releases."] = "This version doesn't publish the installer's signed hash. Download it from the releases page.",
        ["A assinatura do arquivo de hashes não confere com a chave do Qrztweaks. A atualização foi cancelada; baixe pela página oficial se tiver certeza da origem."] = "The hash file's signature doesn't match the Qrztweaks key. The update was cancelled; download from the official page if you're sure of its origin.",
        ["Atualização concluída"] = "Update complete", ["Atualização não concluída"] = "Update not completed",
    };

    private static readonly (Regex Regex, Func<Match, string> Build)[] V2Patterns =
    {
        P(@"^Análise de (.+)\. Dados lidos do Windows \(WMI e registro\)\.$", m => $"Analysis of {m.Groups[1].Value}. Data read from Windows (WMI and registry)."),
        P(@"^Smart Optimize: análise concluída \((\d+) recomendados, (\d+) já aplicados\)$", m => $"Smart Optimize: analysis finished ({m.Groups[1].Value} recommended, {m.Groups[2].Value} already applied)"),
        P(@"^Smart Optimize: (\d+) de (\d+) ajustes confirmados pelo Windows$", m => $"Smart Optimize: {m.Groups[1].Value} of {m.Groups[2].Value} tweaks confirmed by Windows"),
        P(@"^Recomendações para (.+)$", m => $"Recommendations for {T(m, 1)}"),
        P(@"^(Recomendado|Já aplicado|Não aplicável|Incompatível|Requer revisão|Falha na leitura): (\d+)$", m => $"{T(m, 1)}: {m.Groups[2].Value}"),
        P(@"^(.+) livres de (.+)$", m => $"{m.Groups[1].Value} free of {m.Groups[2].Value}"),
        P(@"^Plano (Base|Intermediário|Avançado)$", m => $"{T(m, 1)} plan"),
        P(@"^(.+) \(faltam: (.+)\)$", m => $"{T(m, 1)} (missing: {m.Groups[2].Value})"),
        P(@"^(\d+) tarefa\(s\) ativa\(s\)\.$", m => $"{m.Groups[1].Value} task(s) enabled."),
        P(@"^Ativos: (.+)$", m => $"Active: {m.Groups[1].Value}"),
        P(@"^Instalado: (.+?)( e mais (\d+))?$", m => $"Installed: {m.Groups[1].Value}" + (m.Groups[3].Success ? $" and {m.Groups[3].Value} more" : "")),
        P(@"^Não foi possível ler( o estado)?: (.+)$", m => $"Could not read{(m.Groups[1].Success ? " the state" : "")}: {m.Groups[2].Value}"),
        P(@"^Estado continua: (.+) O script pode ter pulado a etapa \(veja o registro da execução\)\.$", m => $"State unchanged: {T(m, 1)} The script may have skipped the step (see the run log)."),
        P(@"^(.+) Reinicie para valer\.$", m => $"{T(m, 1)} Restart for it to take effect."),
        P(@"^(\d+) de (\d+) ajustes confirmados$", m => $"{m.Groups[1].Value} of {m.Groups[2].Value} tweaks confirmed"),
        P(@"^Verificação: (\d+) de (\d+) confirmados$", m => $"Verification: {m.Groups[1].Value} of {m.Groups[2].Value} confirmed"),
        P(@"^(Confirmado|Não confirmado) · (.+?)( — (.+))?$", m => $"{(m.Groups[1].Value == "Confirmado" ? "Confirmed" : "Not confirmed")} · {T(m, 2)}" + (m.Groups[4].Success ? " — " + T(m, 4) : "")),
        P(@"^Cada ajuste foi conferido lendo o estado do Windows depois da execução; a saída do script não basta\.( (\d+) ajuste\(s\) não rodaram porque a execução foi cancelada ou não começou\.)?$",
            m => "Each tweak was checked by reading the Windows state after the run; the script output isn't enough." + (m.Groups[2].Success ? $" {m.Groups[2].Value} tweak(s) didn't run because the run was cancelled or didn't start." : "")),
        P(@"^Aplicar (\d+) ajustes em (\d+) etapa\(s\)\? Um ponto de restauração é criado antes, e cada alteração fica no backup\.$", m => $"Apply {m.Groups[1].Value} tweaks in {m.Groups[2].Value} step(s)? A restore point is created first, and each change is backed up."),

        // Command Center
        P(@"^(\d+) ajustes do catálogo aplicados( · (\d+) confirmados na última execução)?$", m => $"{m.Groups[1].Value} catalog tweaks applied" + (m.Groups[3].Success ? $" · {m.Groups[3].Value} confirmed in the last run" : "")),
        P(@"^(.+) · (.+) · (\d+) recomendados$", m => $"{m.Groups[1].Value} · {T(m, 2)} · {m.Groups[3].Value} recommended"),
        P(@"^(\d+) · (.+)$", m => $"{m.Groups[1].Value} · {T(m, 2)}"),
        P(@"^Pouco espaço livre no disco \((\d+)%\)$", m => $"Low free disk space ({m.Groups[1].Value}%)"),
        P(@"^A licença vence em (\d+) dia\(s\)$", m => $"The license expires in {m.Groups[1].Value} day(s)"),
        P(@"^(.+) °C máx\.$", m => $"{m.Groups[1].Value} °C max"),
        P(@"^(\d+) s com limite$", m => $"{m.Groups[1].Value} s limited"),
        P(@"^Opacidade (\d+)%$", m => $"Opacity {m.Groups[1].Value}%"),

        // Performance Lab
        P(@"^(.+) · (\d+) s · (.+) · fonte: (.+)$", m => $"{m.Groups[1].Value} · {m.Groups[2].Value} s · {T(m, 3)} · source: {T(m, 4)}"),
        P(@"^Gravando (\d+) de (\d+) s( · aguardando quadros do processo| · só sensores \(sem PresentMon ou sem processo\))?$",
            m => $"Recording {m.Groups[1].Value} of {m.Groups[2].Value} s" + (m.Groups[3].Value.Contains("aguardando") ? " · waiting for frames from the process" : m.Groups[3].Success && m.Groups[3].Length > 0 ? " · sensors only (no PresentMon or no process)" : "")),
        P(@"^FPS médio (\d+) · 1% low (\d+)$", m => $"Average FPS {m.Groups[1].Value} · 1% low {m.Groups[2].Value}"),
        P(@"^FPS médio (\d+)$", m => $"Average FPS {m.Groups[1].Value}"),
        P(@"^Importado: (\d+) FPS médio\.$", m => $"Imported: {m.Groups[1].Value} average FPS."),
        P(@"^A captura não pôde ser salva: (.+)$", m => $"The capture couldn't be saved: {m.Groups[1].Value}"),
        P(@"^Excluir o teste ""(.+)""\?$", m => $"Delete the test \"{m.Groups[1].Value}\"?"),
        P(@"^Redução de clock informada pelo driver: (.+)$", m => "Clock reduction reported by the driver: " + string.Join(", ", m.Groups[1].Value.Split(", ").Select(Tr))),
        P(@"^(▲ melhor|▼ pior|=) (.+)$", m => (m.Groups[1].Value.StartsWith("▲") ? "▲ better" : m.Groups[1].Value.StartsWith("▼") ? "▼ worse" : "=") + " " + m.Groups[2].Value),
        P(@"^Processos diferentes \((.+) e (.+)\)\.$", m => $"Different processes ({m.Groups[1].Value} and {m.Groups[2].Value})."),
        P(@"^Driver de vídeo diferente \((.+) e (.+)\)\.$", m => $"Different graphics driver ({m.Groups[1].Value} and {m.Groups[2].Value})."),
        P(@"^Versão do Windows diferente \(build (.+) e (.+)\)\.$", m => $"Different Windows version (build {m.Groups[1].Value} and {m.Groups[2].Value})."),
        P(@"^Resolução ou taxa de atualização diferente \((.+) e (.+)\)\.$", m => $"Different resolution or refresh rate ({m.Groups[1].Value} and {m.Groups[2].Value})."),
        P(@"^Plano de energia diferente \((.+) e (.+)\)\.$", m => $"Different power plan ({T(m, 1)} and {T(m, 2)})."),
        P(@"^Performance Lab: captura iniciada \((.+), (\d+) s\)$", m => $"Performance Lab: capture started ({T(m, 1)}, {m.Groups[2].Value} s)"),
        P(@"^Performance Lab: captura salva \((.+?)(, (\d+) FPS médio)?\)$", m => $"Performance Lab: capture saved ({T(m, 1)}" + (m.Groups[3].Success ? $", {m.Groups[3].Value} average FPS" : "") + ")"),
        P(@"^Escolha o executável do PresentMon \(PresentMon-2\.x-x64\.exe\)\.$", _ => "Choose the PresentMon executable (PresentMon-2.x-x64.exe)."),
        P(@"^Arquivo grande demais para ser o PresentMon\.$", _ => "File too large to be PresentMon."),
        P(@"^Não foi possível iniciar o PresentMon\.$", _ => "Could not start PresentMon."),

        // Optimization Lab
        P(@"^Antes: (\d+)/(\d+)$", m => $"Before: {m.Groups[1].Value}/{m.Groups[2].Value}"),
        P(@"^Depois: (\d+)/(\d+)$", m => $"After: {m.Groups[1].Value}/{m.Groups[2].Value}"),
        P(@"^Experimento: (.+)$", m => $"Experiment: {T(m, 1)}"),
        P(@"^Processo (.+) · (\d+) s por gravação · mínimo de (\d+) gravações em cada fase\. Repita sempre a mesma cena, com as mesmas configurações do jogo\.$",
            m => $"Process {m.Groups[1].Value} · {m.Groups[2].Value} s per recording · at least {m.Groups[3].Value} recordings per phase. Always repeat the same scene, with the same game settings."),
        P(@"^Aplicar ""(.+)""\? Ele fica no backup e pode ser revertido no fim do experimento\.$", m => $"Apply \"{T(m, 1)}\"? It stays in the backup and can be reverted at the end of the experiment."),
        P(@"^Faça pelo menos (\d+) gravações antes e (\d+) depois\.$", m => $"Make at least {m.Groups[1].Value} recordings before and {m.Groups[2].Value} after."),
        P(@"^Variação alta entre gravações \(CV (.+)% antes e (.+)% depois\): repita a mesma cena, com a mesma duração\.$", m => $"High variation between recordings (CV {m.Groups[1].Value}% before and {m.Groups[2].Value}% after): repeat the same scene, with the same duration."),
        P(@"^Temperatura da GPU diferente entre as fases \((.+) °C e (.+) °C\): o aquecimento muda o clock\.$", m => $"Different GPU temperature between phases ({m.Groups[1].Value} °C and {m.Groups[2].Value} °C): heat changes the clock."),
        P(@"^Uso de CPU muito diferente \((.+)% e (.+)%\): pode haver outro programa interferindo\.$", m => $"Very different CPU usage ({m.Groups[1].Value}% and {m.Groups[2].Value}%): another program may be interfering."),
        P(@"^Sem diferença comprovada \(mínimo prático: (\d+)% com p < 0,05\)\. Se o ajuste não tem outro motivo, reverter é o mais simples\.$", m => $"No proven difference (practical minimum: {m.Groups[1].Value}% with p < 0.05). If the tweak has no other reason, reverting is simplest."),
        P(@"^Optimization Lab: ajuste mantido \((.+), (.+)%\)$", m => $"Optimization Lab: tweak kept ({T(m, 1)}, {m.Groups[2].Value}%)"),
        P(@"^Optimization Lab: ajuste revertido \((.+)\)$", m => $"Optimization Lab: tweak reverted ({T(m, 1)})"),

        // Diagnóstico
        P(@"^Abrir (.+)$", m => $"Open {T(m, 1)}"),
        P(@"^Diagnóstico inteligente: (\d+) achado\(s\)$", m => $"Smart diagnostics: {m.Groups[1].Value} finding(s)"),
        P(@"^Não foi possível concluir: (.+)$", m => $"Could not finish: {m.Groups[1].Value}"),
        P(@"^GPU em (\d+)% em média e CPU em (\d+)% durante (\d+) s \((.+), (.+)\)\.$", m => $"GPU at {m.Groups[1].Value}% on average and CPU at {m.Groups[2].Value}% over {m.Groups[3].Value} s ({T(m, 4)}, {T(m, 5)})."),
        P(@"^GPU em só (\d+)% com (\d+) FPS, abaixo dos (\d+) Hz do monitor\.$", m => $"GPU at only {m.Groups[1].Value}% with {m.Groups[2].Value} FPS, below the monitor's {m.Groups[3].Value} Hz."),
        P(@"^CPU total em (\d+)% \(um único núcleo saturado não aparece no total\)\.$", m => $"Total CPU at {m.Groups[1].Value}% (a single saturated core doesn't show in the total)."),
        P(@"^O contador ""% Performance Limit"" do Windows ficou acima de zero em (\d+) de (\d+) s \((\d+)%\)\.$", m => $"Windows' \"% Performance Limit\" counter was above zero for {m.Groups[1].Value} of {m.Groups[2].Value} s ({m.Groups[3].Value}%)."),
        P(@"^O driver NVIDIA informou: (.+?)(\. Temperatura máxima (\d+) °C\.|\.)$", m => "The NVIDIA driver reported: " + string.Join(", ", m.Groups[1].Value.Split(", ").Select(Tr)) + (m.Groups[3].Success ? $". Maximum temperature {m.Groups[3].Value} °C." : ".")),
        P(@"^Uso médio de (\d+)% em (\d+) leituras, com (.+) GB instalados\.$", m => $"Average usage of {m.Groups[1].Value}% over {m.Groups[2].Value} readings, with {m.Groups[3].Value} GB installed."),
        P(@"^Arquivo de paginação em (\d+)% de uso\.$", m => $"Page file at {m.Groups[1].Value}% usage."),
        P(@"^(.+) GB livres de (.+) GB \((\d+)%\)\.$", m => $"{m.Groups[1].Value} GB free of {m.Groups[2].Value} GB ({m.Groups[3].Value}%)."),
        P(@"^Disco com alerta de saúde: (.+)$", m => $"Disk with a health alert: {m.Groups[1].Value}"),
        P(@"^O Windows informa o estado ""(.+)"" para este disco\.$", m => $"Windows reports the state \"{m.Groups[1].Value}\" for this disk."),
        P(@"^(.+) é informado como HDD\.$", m => $"{m.Groups[1].Value} is reported as an HDD."),
        P(@"^(.+): (\d+)% da CPU no momento da análise\.$", m => $"{m.Groups[1].Value}: {m.Groups[2].Value}% of CPU at the time of the analysis."),
        P(@"^(\d+) itens ativos na inicialização\.$", m => $"{m.Groups[1].Value} items enabled at startup."),
        P(@"^(\d+) processos em execução\.$", m => $"{m.Groups[1].Value} processes running."),
        P(@"^O plano ativo é Economia de energia (com o notebook na tomada|num desktop)\.$", m => "The active plan is Power saver " + (m.Groups[1].Value.StartsWith("com") ? "with the laptop plugged in." : "on a desktop.")),
        P(@"^(\d+) dispositivo\(s\) com problema de driver$", m => $"{m.Groups[1].Value} device(s) with a driver problem"),
        P(@"^Com erro no Gerenciador de Dispositivos: (.+)$", m => $"With an error in Device Manager: {m.Groups[1].Value}"),
        P(@"^(.+): driver de (.+)\.$", m => $"{T(m, 1)}: driver from {m.Groups[2].Value}."),
        P(@"^""% Performance Limit"" em (\d+)% no momento da análise\.$", m => $"\"% Performance Limit\" at {m.Groups[1].Value}% at the time of the analysis."),
        P(@"^Ligado há (\d+) dias \(a inicialização rápida mantém o kernel entre desligamentos\)\.$", m => $"On for {m.Groups[1].Value} days (Fast Startup keeps the kernel between shutdowns)."),

        // Perfis
        P(@"^(\d+) ajustes$", m => $"{m.Groups[1].Value} tweaks"),
        P(@"^Nome de processo inválido: (.+)$", m => $"Invalid process name: {m.Groups[1].Value}"),
        P(@"^Excluir o perfil ""(.+)""\? Os ajustes já aplicados continuam no backup\.$", m => $"Delete the profile \"{m.Groups[1].Value}\"? Tweaks already applied stay in the backup."),
        P(@"^Ajustes desconhecidos ignorados: (.+)$", m => $"Unknown tweaks ignored: {m.Groups[1].Value}"),
        P(@"^Processos inválidos ignorados: (.+)$", m => $"Invalid processes ignored: {m.Groups[1].Value}"),
        P(@"^Formato de perfil desconhecido \((.+)\)\.$", m => $"Unknown profile format ({m.Groups[1].Value})."),
        P(@"^O arquivo não é um perfil do Qrztweaks: (.+)$", m => $"The file isn't a Qrztweaks profile: {m.Groups[1].Value}"),
        P(@"^Perfil (.+): Modo Jogo ativado ao abrir o jogo$", m => $"Profile {m.Groups[1].Value}: Game Mode turned on when the game opened"),
        P(@"^Perfil (.+): não foi possível ativar o Modo Jogo: (.+)$", m => $"Profile {m.Groups[1].Value}: could not turn on Game Mode: {m.Groups[2].Value}"),
        P(@"^Jogo fechado: Modo Jogo restaurado \((\d+) item\(ns\)\)$", m => $"Game closed: Game Mode restored ({m.Groups[1].Value} item(s))"),
        P(@"^Não foi possível restaurar o Modo Jogo automaticamente: (.+)$", m => $"Could not restore Game Mode automatically: {m.Groups[1].Value}"),
        P(@"^(.+) \(cópia\)$", m => $"{m.Groups[1].Value} (copy)"),

        // Atualizações
        P(@"^Qrztweaks (.+) instalado\.$", m => $"Qrztweaks {m.Groups[1].Value} installed."),
        P(@"^O app continua na versão (.+)\. Tente atualizar de novo em Configurações → Atualizações ou baixe pelo site\.$", m => $"The app is still on version {m.Groups[1].Value}. Try updating again in Settings → Updates or download it from the website."),
        P(@"^Atualizado de (.+) para (.+)$", m => $"Updated from {m.Groups[1].Value} to {m.Groups[2].Value}"),
        P(@"^A atualização para (.+) não foi concluída \(versão atual (.+)\)$", m => $"The update to {m.Groups[1].Value} didn't finish (current version {m.Groups[2].Value})"),
    };
}
