using System.Text.RegularExpressions;

namespace PQueirozOptimizer.Services;

public static partial class Translator
{
    private static readonly Dictionary<string, string> Exact = new(StringComparer.Ordinal)
    {
        // ---------- Janela, navegação e barra de status ----------
        ["SEU COMPUTADOR, SOB CONTROLE"] = "YOUR PC, UNDER CONTROL",
        ["MONITORAR"] = "MONITOR", ["OTIMIZAÇÕES"] = "OPTIMIZATIONS", ["SISTEMA"] = "SYSTEM", ["OPTIMIZER"] = "OPTIMIZER",
        ["Visão geral"] = "Overview", ["Otimizações"] = "Optimizations", ["Otimização"] = "Optimization", ["Drivers"] = "Drivers",
        ["Imagens do Windows"] = "Windows images", ["Ferramentas"] = "Tools", ["Atividade e reversão"] = "Activity & restore",
        ["Configurações"] = "Settings", ["BIOS / UEFI"] = "BIOS / UEFI", ["Patch notes"] = "Patch notes", ["Sobre"] = "About",
        ["Chave de administrador"] = "Administrator key", ["Inicialização"] = "Startup", ["Inicialização do Windows"] = "Windows startup",
        ["Aplicativo empacotado"] = "Packaged app", ["Tarefa de inicialização do pacote"] = "Package startup task",
        ["Controlado pela política do Windows"] = "Controlled by Windows policy",
        ["Sistema ativo"] = "System active", ["Sem licença ativa"] = "No active license", ["Licença sem data de expiração"] = "License without expiration date",
        ["Pronto"] = "Ready", ["Pronto para começar"] = "Ready to start", ["Ver atividade"] = "View activity", ["Verificando"] = "Checking",
        ["Administrador"] = "Administrator", ["Usuário"] = "User", ["Indisponível"] = "Unavailable",
        ["Em execução"] = "Running", ["Concluído"] = "Done", ["Verificar resultado"] = "Check result", ["Concluído com falhas"] = "Finished with failures",
        ["Minimizar"] = "Minimize", ["Maximizar"] = "Maximize", ["Restaurar"] = "Restore", ["Fechar"] = "Close",
        ["Alternar para tema claro"] = "Switch to light theme", ["Alternar para tema escuro"] = "Switch to dark theme",
        ["Aguarde a operação em andamento."] = "Please wait for the current operation.",
        ["Aguarde a operação terminar antes de fechar."] = "Wait for the operation to finish before closing.",
        ["Aguarde a alteração em andamento terminar antes de fechar."] = "Wait for the current change to finish before closing.",
        ["Aguarde a operação em andamento terminar antes de atualizar."] = "Wait for the current operation to finish before updating.",
        ["Aguarde a operação em andamento terminar antes de reiniciar."] = "Wait for the current operation to finish before restarting.",
        ["Acesso restrito"] = "Restricted access",
        ["A Proteção contra Adulteração está ativa; o Windows gerencia esta configuração. Use a Segurança do Windows para revisar a proteção."] = "Tamper Protection is active; Windows manages this setting. Use Windows Security to review protection.",
        ["A Proteção contra Adulteração está ativa. Altere esta opção na Segurança do Windows."] = "Tamper Protection is active. Change this setting in Windows Security.",
        ["A Proteção contra Adulteração impede esta alteração. Use a Segurança do Windows."] = "Tamper Protection prevents this change. Use Windows Security.",
        ["Aplicativo empacotado"] = "Packaged app",
        ["Tarefa de inicialização do pacote"] = "Package startup task",
        ["Controlado pela política do Windows"] = "Controlled by Windows policy",
        ["Configuração do Windows não permitida."] = "Windows setting is not allowed.",
        ["As imagens personalizadas do Windows estão disponíveis somente para licenças de administrador."] = "Custom Windows images are only available with administrator licenses.",
        ["ERRO DE INICIALIZAÇÃO"] = "STARTUP ERROR",
        ["O aplicativo abriu, mas não conseguiu consultar todas as informações do sistema."] = "The app opened, but could not read all system information.",
        ["Erro"] = "Error", ["Aviso"] = "Warning", ["Copiado"] = "Copied", ["Salvo"] = "Saved", ["Excluído"] = "Deleted",
        ["Cancelar"] = "Cancel", ["Cancelado"] = "Cancelled", ["Cancelando..."] = "Cancelling...", ["Cancelar operação"] = "Cancel operation",
        ["Cancelar a operação agora? O que já foi aplicado continua registrado no backup e pode ser revertido em Atividade e reversão."] = "Cancel the operation now? What was already applied stays recorded in the backup and can be undone in Activity & restore.",
        ["Há uma operação em andamento. Deseja cancelá-la e fechar o aplicativo? O que já foi aplicado continua registrado no backup e pode ser revertido em Atividade e reversão."] = "An operation is running. Cancel it and close the app? What was already applied stays recorded in the backup and can be undone in Activity & restore.",
        ["Ocorreu um erro inesperado, mas o aplicativo continua aberto. Os detalhes foram salvos em Atividade e reversão."] = "An unexpected error occurred, but the app is still open. The details were saved in Activity & restore.",
        ["A área de transferência está em uso por outro programa. Tente novamente."] = "The clipboard is being used by another program. Try again.",

        // ---------- Dashboard ----------
        ["Consultando seu computador..."] = "Checking your computer...",
        ["Lendo processador, memória, armazenamento e sistema."] = "Reading processor, memory, storage and system.",
        ["Saudável"] = "Healthy", ["Atenção"] = "Attention", ["Crítico"] = "Critical", ["SAÚDE"] = "HEALTH",
        ["Seu PC está em ótima forma"] = "Your PC is in great shape",
        ["Seu PC está bem, com alguns pontos de atenção"] = "Your PC is fine, with a few things to watch",
        ["Seu PC precisa de atenção"] = "Your PC needs attention",
        ["Analisar limpeza"] = "Analyze cleanup", ["Revisar ajustes"] = "Review tweaks", ["Diagnóstico"] = "Diagnostics",
        ["PROCESSADOR"] = "PROCESSOR", ["MEMÓRIA"] = "MEMORY", ["ESPAÇO LIVRE"] = "FREE SPACE", ["PLACA DE VÍDEO"] = "GRAPHICS CARD",
        ["Leitura rápida"] = "Quick read", ["Indicadores que mais influenciam o desempenho do dia a dia."] = "Indicators that most affect everyday performance.",
        ["Espaço livre no disco"] = "Free disk space", ["Tempo desde o último reinício"] = "Time since last restart", ["Memória instalada"] = "Installed memory",
        ["Recente"] = "Recent", ["Reinicie em breve"] = "Restart soon", ["Ideal para jogos"] = "Great for gaming", ["Suficiente"] = "Enough", ["Limitada"] = "Limited",
        ["Atividade recente"] = "Recent activity", ["Ver tudo"] = "View all", ["Suas próximas execuções aparecerão aqui."] = "Your next runs will show up here.",
        ["NÃO FOI POSSÍVEL CONSULTAR O SISTEMA"] = "COULD NOT READ THE SYSTEM",

        // ---------- Atualização ----------
        ["Baixando instalador..."] = "Downloading installer...", ["Atualização disponível"] = "Update available",
        ["O instalador é verificado por SHA256 e o aplicativo reabre sozinho ao terminar."] = "The installer is verified with SHA256 and the app reopens by itself when done.",
        ["Esta versão será baixada pela página de releases."] = "This version will be downloaded from the releases page.",
        ["Instalador verificado. Atualizando — o aplicativo será reaberto automaticamente..."] = "Installer verified. Updating — the app will reopen automatically...",
        ["Esta versão não publica o hash do instalador. Baixe pela página de releases."] = "This version does not publish the installer hash. Download it from the releases page.",
        ["O instalador baixado não confere com o hash publicado na release. A atualização foi cancelada."] = "The downloaded installer does not match the published hash. The update was cancelled.",
        ["O hash do instalador não foi encontrado na release."] = "The installer hash was not found in the release.",
        ["Endereço de download inesperado."] = "Unexpected download address.",

        // ---------- Otimizações ----------
        ["Todas"] = "All", ["Desempenho"] = "Performance", ["Limpeza"] = "Cleanup", ["Manutenção"] = "Maintenance", ["Segurança"] = "Safety",
        ["Personalizar"] = "Customize", ["Revisar"] = "Review", ["Abrir"] = "Open", ["Ver todas"] = "View all",
        ["Nenhuma otimização nesta categoria"] = "No optimizations in this category",
        ["Ative mais otimizações em Configurações ou veja todas as categorias."] = "Enable more optimizations in Settings or view all categories.",
        ["Versão Padrão"] = "Standard Mode", ["Versão Avançada"] = "Advanced Mode", ["Debloat & Privacidade"] = "Debloat & Privacy",
        ["Limpeza Rápida"] = "Quick Cleanup", ["Diagnóstico / Análise"] = "Diagnostics / Analysis", ["Benchmark do Sistema"] = "System Benchmark",
        ["Verificador de Arquivos (SFC)"] = "System File Checker (SFC)", ["Reparo de Imagem (DISM)"] = "Image Repair (DISM)",
        ["Verificação de Disco (CHKDSK)"] = "Disk Check (CHKDSK)", ["Estado do Windows Update"] = "Windows Update Status",
        ["Reverter Última Otimização"] = "Undo Last Optimization", ["Reparar Configurações do Windows"] = "Repair Windows Settings",
        ["Revise ajustes de energia, fila de impressão, cache DNS e armazenamento."] = "Review power, print queue, DNS cache and storage tweaks.",
        ["Desempenho, latência de periféricos, modo MSI da GPU, políticas do Editor de Política de Grupo, privacidade e desativação de componentes em segundo plano."] = "Performance, peripheral latency, GPU MSI mode, Group Policy settings, privacy and disabling background components.",
        ["Remove bloatware do Windows, aplicativos desnecessários e reduz telemetria."] = "Removes Windows bloatware and unnecessary apps and reduces telemetry.",
        ["Analisa temporários do usuário e do Windows, preservando arquivos recentes."] = "Analyzes user and Windows temporary files, keeping recent files.",
        ["Analisa a integridade de CPU, memória, armazenamento e saúde geral do sistema."] = "Checks CPU, memory, storage and overall system health.",
        ["Testa velocidade do processador, tempo de resposta e latência do sistema operacional."] = "Measures processor load, disk speed and boot time.",
        ["Examina e repara arquivos corrompidos ou ausentes do Windows (sfc /scannow)."] = "Scans and repairs corrupted or missing Windows files (sfc /scannow).",
        ["Restaura e corrige a imagem do sistema usando o repositório oficial da Microsoft."] = "Restores and fixes the system image using Microsoft's official repository.",
        ["Executa uma verificação online do sistema de arquivos no disco principal."] = "Runs an online file system check on the main drive.",
        ["Consulta o serviço, as últimas atualizações e reinicializações pendentes."] = "Checks the service, latest updates and pending restarts.",
        ["Restaura o snapshot de configurações para o estado anterior à última execução."] = "Restores settings to the state before the last run.",
        ["Restaura os padrões do agendador multimídia (áudio e jogos) apagados por versões antigas do otimizador. Só adiciona o que estiver faltando."] = "Restores the multimedia scheduler defaults (audio and games) erased by older optimizer versions. Only adds what is missing.",

        // ---------- Revisar ajustes / execução ----------
        ["Escolha exatamente o que deseja aplicar"] = "Choose exactly what to apply",
        ["Um ponto de restauração é criado antes dos ajustes; se ele falhar, nada é alterado. Alterações de energia, registro e serviços têm backup e podem ser revertidas em “Atividade e reversão”."] = "A restore point is created before any tweak; if it fails, nothing is changed. Power, registry and service changes are backed up and can be undone in “Activity & restore”.",
        ["Remoções de apps e arquivos não são desfeitas pelo backup. Alguns ajustes só valem depois de reiniciar o Windows."] = "App and file removals are not undone by the backup. Some tweaks only take effect after restarting Windows.",
        ["Não reversível"] = "Not reversible", ["Com backup"] = "Backed up", ["Nenhum ajuste selecionado"] = "No tweaks selected",
        ["Ação pontual"] = "One-off action", ["Remove arquivos ou apps: não é desfeito pela reversão."] = "Removes files or apps: not undone by restore.",
        ["Não altera configurações, então não precisa de backup."] = "Doesn't change settings, so no backup is needed.",
        ["Selecionar todos"] = "Select all", ["Aplicar selecionados"] = "Apply selected", ["Aplicar ajustes"] = "Apply tweaks",
        ["Saída da execução"] = "Run output", ["Copiar resultado"] = "Copy result", ["Resultado copiado para a área de transferência."] = "Result copied to the clipboard.",
        ["Ver backup e reversão"] = "View backup & restore", ["Voltar às otimizações"] = "Back to optimizations",
        ["Restaurar configurações"] = "Restore settings", ["Desfazendo as alterações registradas no último backup."] = "Undoing the changes recorded in the last backup.",
        ["Reverter configurações"] = "Restore settings",

        // ---------- Limpeza ----------
        ["Limpeza rápida"] = "Quick cleanup", ["Analisando arquivos temporários..."] = "Analyzing temporary files...",
        ["Isso leva poucos segundos. Nada é apagado nesta etapa."] = "This takes a few seconds. Nothing is deleted at this step.",
        ["Arquivos alterados nas últimas 48 horas, links e itens sem acesso são preservados. A exclusão é permanente."] = "Files changed in the last 48 hours, links and inaccessible items are kept. Deletion is permanent.",
        ["Excluir selecionados"] = "Delete selected", ["Temporários do usuário"] = "User temporary files", ["Temporários do Windows"] = "Windows temporary files",
        ["Analisar temporários"] = "Analyze temporary files", ["Limpeza de temporários"] = "Temporary file cleanup",
        ["Removendo arquivos temporários..."] = "Removing temporary files...", ["Limpeza rápida concluída"] = "Quick cleanup finished",

        // ---------- Histórico ----------
        ["Histórico arquivado"] = "Archived history", ["Nenhuma reversão pendente"] = "No pending restore",
        ["Quando você aplicar ajustes, o backup aparecerá aqui para ser restaurado com um clique."] = "When you apply tweaks, the backup shows up here to be restored with one click.",
        ["Tudo o que o aplicativo executou, incluindo falhas."] = "Everything the app ran, including failures.",
        ["Exportar"] = "Export", ["Atividade exportada."] = "Activity exported.", ["revertido"] = "restored", ["Não foi possível ler o backup"] = "Could not read the backup",
        ["Versao Padrao"] = "Standard Mode", ["Versao Avancada"] = "Advanced Mode", ["Versao Gamer"] = "Gamer Mode", ["Debloat"] = "Debloat",
        ["Otimizacao Inteligente"] = "Smart Optimization", ["Modo Empresa"] = "Business Mode",

        // ---------- Inicialização ----------
        ["Muitos programas abrindo com o Windows"] = "Many programs start with Windows", ["Inicialização sob controle"] = "Startup under control",
        ["Desative o que você não precisa logo ao ligar o PC. O programa continua instalado e pode ser reativado aqui a qualquer momento — é o mesmo mecanismo do Gerenciador de Tarefas."] = "Disable what you don't need right when the PC starts. The program stays installed and can be re-enabled here at any time — it's the same mechanism Task Manager uses.",
        ["Filtrar por nome ou fabricante…"] = "Filter by name or publisher…", ["Nenhum programa de inicialização encontrado."] = "No startup programs found.",
        ["Ativo"] = "Enabled", ["Desativado"] = "Disabled", ["Ativo ao iniciar o Windows"] = "Runs when Windows starts",
        ["Todos os usuários"] = "All users", ["Todos os usuários (32 bits)"] = "All users (32-bit)", ["Pasta Inicializar"] = "Startup folder", ["Pasta Inicializar (todos)"] = "Startup folder (all users)",
        ["NÃO FOI POSSÍVEL LER A INICIALIZAÇÃO"] = "COULD NOT READ STARTUP ITEMS",
        ["Tudo o que inicia com o Windows"] = "Everything that starts with Windows",
        ["Itens de logon, tarefas agendadas e serviços, como no Autoruns. Desmarcar desativa sem apagar nada: marque de novo para reativar."] = "Logon items, scheduled tasks and services, like Autoruns. Unchecking disables without deleting anything: check it again to re-enable.",
        ["Filtrar por nome, editor ou caminho…"] = "Filter by name, publisher or path…", ["Atualizar"] = "Refresh",
        ["Ocultar itens do Windows"] = "Hide Windows entries",
        ["Esconde o que é assinado pela Microsoft como parte do Windows, como a opção do Autoruns."] = "Hides what Microsoft signs as part of Windows, like the Autoruns option.",
        ["Lendo o que inicia com o Windows…"] = "Reading what starts with Windows…", ["Itens de logon, tarefas agendadas e serviços."] = "Logon items, scheduled tasks and services.",
        ["Verificando assinaturas digitais…"] = "Checking digital signatures…", ["Assinaturas verificadas"] = "Signatures verified",
        ["Tudo"] = "Everything", ["Logon"] = "Logon", ["Tarefas agendadas"] = "Scheduled tasks", ["Serviços"] = "Services",
        ["Nenhum item fora do Windows nesta categoria."] = "No non-Windows entries in this category.", ["Nenhum item encontrado com esses filtros."] = "No entries match these filters.",
        ["Este item não pode ser desativado por aqui"] = "This entry can't be disabled here", ["Este item não pode ser desativado por aqui."] = "This entry can't be disabled here.",
        ["Abrir local do arquivo"] = "Open file location", ["Ir para a entrada"] = "Jump to entry", ["Pesquisar na internet"] = "Search online",
        ["Arquivo não encontrado"] = "File not found", ["Verificado"] = "Verified", ["Sem assinatura"] = "Not signed", ["Assinatura inválida"] = "Invalid signature", ["Verificando…"] = "Checking…",
        ["Executa uma vez no próximo logon"] = "Runs once at next logon", ["Definido por política do Windows"] = "Set by Windows policy", ["Parte do logon do Windows"] = "Part of Windows logon",
        ["Automático"] = "Automatic", ["Automático (atraso na inicialização)"] = "Automatic (delayed start)", ["Manual (desativado aqui)"] = "Manual (disabled here)",
        ["Em um evento"] = "On an event", ["Uma vez"] = "One time", ["Diariamente"] = "Daily", ["Semanalmente"] = "Weekly", ["Mensalmente"] = "Monthly",
        ["Com o PC ocioso"] = "When the PC is idle", ["Ao ser criada"] = "When registered", ["Ao iniciar o Windows"] = "At startup", ["Ao fazer logon"] = "At logon",
        ["Ao bloquear ou desbloquear"] = "On lock or unlock", ["Gatilho personalizado"] = "Custom trigger", ["Sem gatilho (só manual)"] = "No trigger (manual only)",
        ["Agendador de Tarefas"] = "Task Scheduler", ["O Agendador de Tarefas não está disponível."] = "Task Scheduler is not available.",
        ["as tarefas agendadas"] = "the scheduled tasks", ["os serviços"] = "the services", ["o Winlogon"] = "Winlogon",

        // ---------- Modo de energia ----------
        ["MODO DE ENERGIA DO WINDOWS"] = "WINDOWS POWER MODE", ["PLANOS DE ENERGIA"] = "POWER PLANS",
        ["Melhor eficiência energética"] = "Best power efficiency", ["Equilibrado"] = "Balanced", ["Melhor desempenho"] = "Best performance",
        ["Mais bateria e menos calor; o desempenho diminui."] = "More battery and less heat; performance drops.",
        ["Padrão do Windows: equilibra desempenho e consumo."] = "Windows default: balances performance and power use.",
        ["Mais desempenho em jogos e programas pesados; ideal na tomada."] = "More performance in games and heavy apps; best when plugged in.",
        ["Criado pelo Qrztweaks"] = "Created by Qrztweaks", ["Plano de energia instalado neste PC"] = "Power plan installed on this PC",
        ["O modo de energia vale para o plano Equilibrado; os planos substituem o modo."] = "The power mode applies to the Balanced plan; the plans replace the mode.",
        ["Computador sem bateria (desktop)"] = "No battery (desktop)", ["Na tomada"] = "Plugged in", ["Na bateria"] = "On battery", ["Economia de bateria ativa"] = "Battery saver on",
        ["Atalho de modo de energia"] = "Power mode shortcut",
        ["Cria um atalho na Área de Trabalho que abre um seletor rápido: economia de energia, equilibrado, melhor desempenho ou outro plano de energia. Abre sem pedir permissão de administrador."] = "Creates a Desktop shortcut that opens a quick picker: power saving, balanced, best performance or another power plan. It opens without asking for administrator permission.",
        ["Criar atalho na Área de Trabalho"] = "Create Desktop shortcut", ["Remover atalho"] = "Remove shortcut", ["Abrir seletor"] = "Open picker",
        ["Atalho criado"] = "Shortcut created", ["Recomendado para este PC"] = "Recommended for this PC", ["Recomendado para notebooks"] = "Recommended for laptops",
        ["Atalho de modo de energia removido."] = "Power mode shortcut removed.", ["Atalho de modo de energia removido"] = "Power mode shortcut removed",
        ["Atalho 'Modo de Energia' criado na Área de Trabalho. Ele abre o seletor sem pedir permissão de administrador."] = "'Power Mode' shortcut created on the Desktop. It opens the picker without asking for administrator permission.",
        ["Atalho de modo de energia criado na Área de Trabalho"] = "Power mode shortcut created on the Desktop",

        // ---------- Ferramentas ----------
        ["Barra de tarefas All Black"] = "All Black taskbar", ["Aplicar All Black"] = "Apply All Black", ["Restaurar padrão"] = "Restore default", ["Copiar comando"] = "Copy command",
        ["Aplica uma paleta de acentuação preta e desativa a transparência, deixando a barra de tarefas em preto puro."] = "Applies a black accent palette and turns off transparency, making the taskbar pure black.",
        ["Ativa"] = "Active", ["Padrão do Windows"] = "Windows default",
        ["Limpeza rápida em um clique"] = "One-click quick cleanup", ["Remover atalhos"] = "Remove shortcuts", ["Criar atalho de limpeza"] = "Create cleanup shortcut",
        ["Limpar agora"] = "Clean now", ["Atalhos criados"] = "Shortcuts created", ["Sem atalhos"] = "No shortcuts",
        ["Cria atalhos na Área de Trabalho e no Menu Iniciar que limpam arquivos temporários sem abrir o aplicativo."] = "Creates Desktop and Start Menu shortcuts that clean temporary files without opening the app.",
        ["Utilitários do Windows"] = "Windows utilities", ["Atalhos para as ferramentas administrativas mais usadas."] = "Shortcuts to the most used administrative tools.",
        ["Gerenciador de Tarefas"] = "Task Manager", ["Gerenciador de Dispositivos"] = "Device Manager", ["Serviços do Windows"] = "Windows Services",
        ["Configurações do Sistema"] = "System Settings", ["Prompt de Comando"] = "Command Prompt", ["Editor do Registro"] = "Registry Editor",
        ["Informações do Sistema"] = "System Information", ["Gerenciamento de Disco"] = "Disk Management", ["Visualizador de Eventos"] = "Event Viewer",
        ["Comando PowerShell copiado para a área de transferência."] = "PowerShell command copied to the clipboard.",
        ["Barra de Tarefas All Black"] = "All Black Taskbar",
        ["Barra de tarefas All Black aplicada com sucesso!\nO Windows Explorer foi reiniciado para atualizar o visual."] = "All Black taskbar applied!\nWindows Explorer was restarted to refresh the look.",
        ["Barra de tarefas padrão restaurada com sucesso!\nO Windows Explorer foi reiniciado."] = "Default taskbar restored!\nWindows Explorer was restarted.",
        ["Atalhos de Limpeza Rápida removidos com sucesso."] = "Quick Cleanup shortcuts removed.",
        ["Atalho 'Limpeza Rápida' criado na sua Área de Trabalho e no Menu Iniciar.\n\nPara fixá-lo na barra de tarefas, clique com o botão direito no atalho e escolha 'Fixar na barra de tarefas' (o Windows 11 não permite que aplicativos façam isso sozinhos)."] = "The 'Quick Cleanup' shortcut was created on your Desktop and Start Menu.\n\nTo pin it to the taskbar, right-click the shortcut and choose 'Pin to taskbar' (Windows 11 doesn't let apps do this themselves).",
        ["Atalho Criado"] = "Shortcut created",

        // ---------- BIOS, patch notes, sobre ----------
        ["Assistente seguro de BIOS"] = "Safe BIOS assistant", ["Reiniciar na BIOS/UEFI"] = "Restart into BIOS/UEFI",
        ["O Qrztweaks não grava firmware. Aqui estão os ajustes que costumam trazer ganho real — faça-os manualmente, conferindo o manual da sua placa-mãe."] = "Qrztweaks never writes firmware. These are the settings that usually bring real gains — change them manually, checking your motherboard manual.",
        ["XMP / EXPO"] = "XMP / EXPO", ["Faz a memória rodar na velocidade anunciada. Costuma dar o maior ganho em jogos."] = "Runs your memory at its rated speed. Usually the biggest gain in games.",
        ["Resizable BAR"] = "Resizable BAR", ["Permite à placa de vídeo acessar toda a VRAM de uma vez. Exige CSM desativado."] = "Lets the GPU access all VRAM at once. Requires CSM to be disabled.",
        ["Modo de energia"] = "Power mode", ["Mantenha C-States habilitados em notebooks; em desktops, o perfil padrão da placa já é bom."] = "Keep C-States enabled on laptops; on desktops the board's default profile is already good.",
        ["Atualização de BIOS"] = "BIOS update", ["Use apenas o atualizador oficial da fabricante e nunca desligue o PC durante o processo."] = "Only use the manufacturer's official updater and never turn the PC off during the process.",
        ["O computador será reiniciado AGORA e abrirá diretamente as configurações de firmware (BIOS/UEFI).\n\nSalve seus trabalhos e feche outros programas antes de continuar.\n\nDeseja reiniciar agora?"] = "The computer will restart NOW and open the firmware settings (BIOS/UEFI) directly.\n\nSave your work and close other programs before continuing.\n\nRestart now?",
        ["Mais recente"] = "Latest",
        ["Visual novo: tema escuro/claro redesenhado, ícones na navegação e painel com pontuação de saúde."] = "New look: redesigned dark/light theme, navigation icons and a dashboard with a health score.",
        ["Atualização automática verificada por SHA256; o aplicativo reabre sozinho ao terminar."] = "Automatic updates verified with SHA256; the app reopens by itself when done.",
        ["Backups de reversão protegidos contra alteração por outros usuários do Windows."] = "Restore backups protected against changes by other Windows users.",
        ["Rodar várias otimizações seguidas agora reverte para o estado original."] = "Running several optimizations in a row now restores to the original state.",
        ["TRIM só em SSDs, GPU Scheduling só em placas compatíveis e SysMain preservado em HDs."] = "TRIM only on SSDs, GPU Scheduling only on compatible cards and SysMain kept on HDDs.",
        ["Ponto de restauração criado mesmo quando o Windows já criou um nas últimas 24h."] = "Restore point created even when Windows already made one in the last 24h.",
        ["Licença vinculada ao ID do Windows (chaves antigas continuam válidas)."] = "License tied to the Windows ID (old keys keep working).",
        ["Ativação por chave assinada vinculada ao computador."] = "Activation with a signed key tied to the computer.",
        ["Plano de energia com nome Qrztweaks."] = "Power plan named Qrztweaks.",
        ["Redução de latência para mouse, teclado e USB."] = "Lower latency for mouse, keyboard and USB.",
        ["Melhorias nas políticas avançadas de privacidade e desempenho."] = "Improved advanced privacy and performance policies.",
        ["Modo Avançado com políticas de privacidade e desempenho."] = "Advanced Mode with privacy and performance policies.",
        ["Backups, histórico e reversão de alterações."] = "Backups, history and change restore.",
        ["Verificação de atualização ao abrir o aplicativo."] = "Update check when the app opens.",
        ["Análise do PC mostra placa-mãe, BIOS, memória (XMP/EXPO e dual channel), temperatura e Integridade de Memória."] = "PC analysis shows motherboard, BIOS, memory (XMP/EXPO and dual channel), temperature and Memory Integrity.",
        ["Nova medição de latência DPC e interrupções na análise e no benchmark, com comparação antes → depois."] = "New DPC latency and interrupt measurement in the analysis and benchmark, with before → after comparison.",
        ["Versão Avançada ativa o modo MSI na placa de vídeo (reversível)."] = "Advanced Mode enables MSI mode on the graphics card (reversible).",
        ["Efeitos visuais e precisão do ponteiro agora são aplicados na hora; antes só mudavam o registro."] = "Visual effects and pointer precision are now applied immediately; before they only changed the registry.",
        ["Serviços já removidos do Windows não geram mais falha, e o plano Desempenho Máximo não é mais duplicado."] = "Services already removed from Windows no longer cause failures, and the Ultimate Performance plan is no longer duplicated.",
        ["O aplicativo abre uma única vez: clicar de novo traz a janela já aberta para frente."] = "The app opens only once: clicking again brings the open window to the front.",
        ["Nova página Inicialização no estilo do Autoruns: itens de logon, tarefas agendadas e serviços, com editor, assinatura digital verificada e liga/desliga reversível."] = "New Autoruns-style Startup page: logon items, scheduled tasks and services, with publisher, verified digital signature and reversible on/off.",
        ["Atalho de modo de energia na Área de Trabalho (Ferramentas): troca entre eficiência, equilibrado e desempenho sem pedir administrador — ideal para notebooks."] = "Power mode shortcut on the Desktop (Tools): switches between efficiency, balanced and performance without administrator rights — ideal for laptops.",
        ["Operações longas podem ser canceladas, e erros inesperados não fecham mais o aplicativo."] = "Long operations can be cancelled, and unexpected errors no longer close the app.",
        ["Painel: discos grandes não aparecem mais com 0% livre, e a memória mostra o valor instalado (16 GB, não 15,9 GB)."] = "Dashboard: large disks no longer show 0% free, and memory shows the installed amount (16 GB, not 15.9 GB).",
        ["Debloat: tarefas de telemetria ausentes no Windows 11 não interrompem mais a etapa, e o OneDrive é removido de verdade no Windows 11."] = "Debloat: telemetry tasks missing on Windows 11 no longer stop the step, and OneDrive is actually removed on Windows 11.",
        ["Versão Padrão: mantém um plano de energia de desempenho já ativo, recria o Alto Desempenho quando apagado e a limpeza de disco agora limpa de fato."] = "Standard Mode: keeps an active performance power plan, recreates High Performance when it was deleted, and disk cleanup now actually cleans.",
        ["A revisão de ajustes mostra o que tem backup, o que não é reversível e o que é ação pontual; a análise ficou colorida e mais precisa."] = "Tweak review shows what is backed up, what is not reversible and what is a one-off action; the analysis is now colored and more accurate.",
        ["Ativação mais fácil: \"Copiar pedido\" gera a mensagem com o ID do computador, e a chave copiada é colada sozinha."] = "Easier activation: \"Copy request\" builds the message with the computer ID, and a copied key is pasted automatically.",
        ["Todo o aplicativo agora muda de idioma, incluindo mensagens e a saída das operações."] = "The whole app now switches language, including messages and operation output.",
        ["Saída completa das operações ao vivo, com cores, contadores e botão para copiar o resultado."] = "Full live output for operations, with colors, counters and a copy-result button.",
        ["Nova página Inicialização do Windows para ativar e desativar programas que abrem com o PC."] = "New Windows startup page to enable and disable programs that start with the PC.",
        ["Corrige a Versão Avançada, que apagava configurações do agendador multimídia; nova ferramenta Reparar Configurações do Windows."] = "Fixes Advanced Mode erasing multimedia scheduler settings; new Repair Windows Settings tool.",
        ["Novos ajustes reversíveis: anúncios e apps automáticos, Delivery Optimization, jogos em janela, Power Throttling, ID de publicidade, Bing, histórico de atividades e Copilot."] = "New reversible tweaks: ads and auto-installed apps, Delivery Optimization, windowed games, Power Throttling, advertising ID, Bing, activity history and Copilot.",
        ["SFC, DISM e CHKDSK exibem a saída corretamente; benchmark de disco usa o winsat (sem cache)."] = "SFC, DISM and CHKDSK output shown correctly; disk benchmark uses winsat (no cache).",
        ["Desenvolvido por Pedro Queiroz"] = "Developed by Pedro Queiroz",
        ["Otimização, manutenção e gerenciamento do Windows em um só lugar — com revisão de cada ajuste antes de aplicar, backup automático e reversão com um clique."] = "Windows optimization, maintenance and management in one place — every change is reviewed before applying, with automatic backup and one-click restore.",
        ["SEGURANÇA"] = "SAFETY", ["TRANSPARÊNCIA"] = "TRANSPARENCY", ["ATUALIZAÇÕES"] = "UPDATES",
        ["Ponto de restauração e backup antes de cada ajuste"] = "Restore point and backup before every change",
        ["Você escolhe item por item o que aplicar"] = "You choose exactly what to apply", ["Instalador verificado por SHA256"] = "SHA256-verified installer",
        ["Precisa de um serviço ou automação?"] = "Need a service or automation?", ["Visitar site"] = "Visit website",
        ["Remoções de arquivos e aplicativos não são desfeitas pelo backup de configurações; consulte os detalhes antes de aplicar."] = "File and app removals cannot be undone by the configuration backup; review the details before applying.",
        ["Chave ativada. Os recursos de administrador já estão disponíveis."] = "Key activated. Administrator features are now available.",
        ["Ativação concluída"] = "Activation complete",

        // ---------- Ativação ----------
        ["Ativar Qrztweaks"] = "Activate Qrztweaks", ["Ative sua licença"] = "Activate your license",
        ["Cole abaixo a chave de acesso recebida. Ela fica vinculada a este computador."] = "Paste the access key you received below. It is tied to this computer.",
        ["Chave de acesso"] = "Access key", ["ID deste computador"] = "This computer's ID", ["Copiar"] = "Copy",
        ["Envie esse ID ao solicitar uma chave."] = "Send this ID when requesting a key.", ["Sair"] = "Exit", ["Ativar e continuar"] = "Activate and continue",
        ["ID copiado. Envie-o ao solicitar uma chave vinculada a este computador."] = "ID copied. Send it when requesting a key for this computer.",
        ["Copiar pedido"] = "Copy request",
        ["Copie o pedido e envie para receber sua chave. Ao copiar a chave recebida, ela é colada aqui automaticamente."] = "Copy the request and send it to get your key. When you copy the key you received, it is pasted here automatically.",
        ["Pedido copiado. Cole e envie na conversa em que você solicita a chave."] = "Request copied. Paste and send it in the chat where you ask for the key.",
        ["Chave encontrada na área de transferência. Clique em \"Ativar e continuar\"."] = "Key found in the clipboard. Click \"Activate and continue\".",
        ["Nenhuma chave de acesso foi ativada neste computador."] = "No access key has been activated on this computer.",
        ["Não foi possível ler a licença local."] = "Could not read the local license.",
        ["A chave é válida, mas não foi possível salvá-la neste perfil do Windows."] = "The key is valid, but it could not be saved to this Windows profile.",
        ["Chave de acesso inválida."] = "Invalid access key.", ["A assinatura da chave não é válida."] = "The key signature is not valid.",
        ["A chave não informa o titular."] = "The key does not include the holder.", ["Esta chave de acesso expirou."] = "This access key has expired.",
        ["Esta chave não está vinculada a um computador."] = "This key is not tied to a computer.",
        ["Esta chave foi emitida para outro computador."] = "This key was issued for another computer.", ["O formato da chave está inválido."] = "The key format is invalid.",
        ["Licença perto de vencer: o painel avisa nos últimos 7 dias, com \"Copiar pedido de renovação\" e \"Ativar nova chave\"."] = "License about to expire: the dashboard warns in the last 7 days, with \"Copy renewal request\" and \"Activate new key\".",
        ["Licença vencida ou recusada: a tela de ativação explica o motivo e já gera o pedido de renovação com o titular."] = "Expired or rejected license: the activation screen explains why and builds the renewal request with the holder's name.",
        ["Chaves revogadas pelo suporte deixam de funcionar ao abrir o aplicativo com internet."] = "Keys revoked by support stop working when the app opens with an internet connection.",
        ["Atrasar o relógio do Windows não estende mais licenças com validade; a hora da internet corrige relógios adiantados."] = "Setting the Windows clock back no longer extends licenses with an expiry date; internet time fixes clocks that were ahead.",
        ["Os campos da chave e do ID na tela de ativação não cortam mais o texto."] = "The key and ID fields on the activation screen no longer cut off the text.",
        ["Planos Mensal e Vitalício: o plano vem na chave e aparece no rodapé e em Configurações → Minha licença."] = "Monthly and Lifetime plans: the plan comes in the key and shows in the footer and in Settings → My license.",
        ["Minha licença mostra titular, plano, validade e ID do computador, com atalhos para renovar, ativar outra chave e pedir suporte."] = "My license shows the holder, plan, expiry and computer ID, with shortcuts to renew, activate another key and get support.",
        ["Renovar pelo Discord: copia o pedido de renovação e abre o servidor; é só abrir um ticket e pagar via Pix."] = "Renew on Discord: copies the renewal request and opens the server; just open a ticket and pay via Pix.",
        ["\"Quero o Vitalício\" gera o pedido de upgrade com o plano desejado."] = "\"I want Lifetime\" builds the upgrade request with the desired plan.",
        ["Animação de abertura: o logo aparece e a interface entra suavemente."] = "Opening animation: the logo appears and the interface slides in smoothly.",
        ["Configurações → Atualizações: mostra a versão instalada e verifica novas versões na hora, com instalação em um clique."] = "Settings → Updates: shows the installed version and checks for new versions on demand, with one-click install.",
        ["A animação de abertura agora aparece também em PCs com os efeitos visuais do Windows reduzidos (como após a otimização do próprio app)."] = "The opening animation now also plays on PCs with reduced Windows visual effects (such as after the app's own optimization).",
        ["Minha licença"] = "My license", ["Titular"] = "Holder", ["Plano"] = "Plan", ["Validade"] = "Valid until", ["Tipo"] = "Type",
        ["ID do computador"] = "Computer ID", ["Vitalícia"] = "Lifetime", ["Mensal"] = "Monthly", ["Vitalício"] = "Lifetime", ["Personalizado"] = "Custom",
        ["Admin"] = "Admin", ["Standard"] = "Standard",
        ["Plano Vitalício: sem data de vencimento, com reemissão da chave após formatar e suporte prioritário."] = "Lifetime plan: no expiration date, with key reissue after formatting and priority support.",
        ["Plano com validade: quando estiver perto de vencer, abra um ticket de renovação no Discord e pague via Pix."] = "Plan with an expiration date: when it is about to expire, open a renewal ticket on Discord and pay via Pix.",
        ["Renovar pelo Discord"] = "Renew on Discord",
        ["Copia o pedido de renovação e abre o Discord: abra um ticket de renovação, cole o pedido e pague via Pix"] = "Copies the renewal request and opens Discord: open a renewal ticket, paste the request and pay via Pix",
        ["Pedido de renovação copiado. No Discord, abra um ticket de renovação, cole o pedido e pague via Pix."] = "Renewal request copied. On Discord, open a renewal ticket, paste the request and pay via Pix.",
        ["Clique em \"Copiar pedido\", abra um ticket de renovação no Discord e cole o pedido lá. O pagamento é via Pix; ao copiar a nova chave, ela é colada aqui sozinha."] = "Click \"Copy request\", open a renewal ticket on Discord and paste the request there. Payment is via Pix; when you copy the new key, it is pasted here automatically.",
        ["Quero o Vitalício"] = "I want Lifetime", ["Ativar outra chave"] = "Activate another key",
        ["Copia um pedido de upgrade: pague uma vez e não precisa mais renovar"] = "Copies an upgrade request: pay once and never renew again",
        ["Pedido de upgrade para o Vitalício copiado. No Discord, abra um ticket, cole o pedido e pague via Pix."] = "Lifetime upgrade request copied. On Discord, open a ticket, paste the request and pay via Pix.",
        ["Suporte prioritário (Discord)"] = "Priority support (Discord)", ["Suporte (Discord)"] = "Support (Discord)",
        ["Renovar Qrztweaks"] = "Renew Qrztweaks", ["Renove sua licença"] = "Renew your license",
        ["A licença salva neste computador não é mais válida."] = "The license saved on this computer is no longer valid.",
        ["Clique em \"Copiar pedido\" e envie na conversa em que você comprou a licença. Ao copiar a nova chave, ela é colada aqui sozinha."] = "Click \"Copy request\" and send it in the chat where you bought the license. When you copy the new key, it is pasted here automatically.",
        ["Copiar pedido de renovação"] = "Copy renewal request", ["Ativar nova chave"] = "Activate new key",
        ["Pedido de renovação copiado. Envie na conversa em que você comprou a licença."] = "Renewal request copied. Send it in the chat where you bought the license.",
        ["Sua licença vence hoje"] = "Your license expires today", ["Sua licença vence amanhã"] = "Your license expires tomorrow",
        ["Chave ativada. Sua licença foi atualizada."] = "Key activated. Your license has been updated.",
        ["A área de transferência está ocupada. Tente novamente."] = "The clipboard is busy. Try again.",
        ["Esta chave foi revogada. Fale com o suporte para mais informações."] = "This key has been revoked. Contact support for more information.",
        ["A data e a hora do Windows estão atrasadas em relação ao último uso do Qrztweaks. Acerte o relógio para continuar."] = "Windows' date and time are earlier than the last time Qrztweaks was used. Fix the clock to continue.",
        ["Confira a data e a hora do Windows."] = "Check Windows' date and time.",
        ["O Qrztweaks será fechado. Ao abrir de novo, você poderá ativar uma nova chave."] = "Qrztweaks will close. When you open it again, you can activate a new key.",
        ["Termine a operação em andamento e feche o Qrztweaks: na próxima abertura, será preciso ativar uma nova chave."] = "Finish the current operation and close Qrztweaks: the next time it opens, a new key will be required.",

        // ---------- Configurações e perfis ----------
        ["Modos & Perfis de Visualização"] = "Modes & display profiles",
        ["Personalize quais otimizações deseja visualizar no aplicativo. Você pode alternar entre os perfis prontos ou salvar seus próprios modos personalizados."] = "Choose which optimizations the app shows. Switch between ready-made profiles or save your own custom modes.",
        ["Perfil Selecionado"] = "Selected profile", ["Ativar Este Perfil"] = "Activate this profile", ["Excluir Perfil"] = "Delete profile",
        ["Otimizações exibidas neste modo"] = "Optimizations shown in this mode", ["Marcar Todas"] = "Check all", ["Desmarcar Todas"] = "Uncheck all",
        ["Salvar alterações no perfil"] = "Save profile changes", ["Salvar como novo modo"] = "Save as new mode", ["Nome do novo modo…"] = "New mode name…",
        ["Digite o nome do novo perfil"] = "Type the new profile name",
        ["Aparência & Tema"] = "Appearance & theme", ["Modo Escuro (Dark)"] = "Dark mode", ["Modo Claro (Light)"] = "Light mode",
        ["Escolha o esquema de cores para o aplicativo. Todas as janelas e componentes se adaptam instantaneamente."] = "Choose the app's color scheme. Every window and component adapts instantly.",
        ["Idioma"] = "Language", ["Idioma / Language"] = "Language / Idioma", ["Português (PT)"] = "Portuguese (PT)", ["English (EN)"] = "English (EN)",
        ["Traduz todo o aplicativo (menus, páginas, drivers e mensagens) para o idioma selecionado."] = "Translates the entire app (menus, pages, drivers and messages) to the selected language.",
        ["Perfil Ativado"] = "Profile activated", ["Perfil Criado"] = "Profile created", ["Confirmar Exclusão"] = "Confirm deletion",
        ["Por favor, digite um nome para o novo perfil."] = "Please type a name for the new profile.",
        ["Perfis padrão do sistema não podem ser excluídos."] = "Built-in profiles cannot be deleted.",
        ["Perfil personalizado do usuário"] = "Custom user profile", ["Personalizada"] = "Custom", ["Ativo)"] = "Active)",
        ["Este modo sempre exibe todas as otimizações. Para personalizar, marque o que quiser e salve como novo modo."] = "This mode always shows every optimization. To customize it, check what you want and save it as a new mode.",
        ["Já existe um modo pronto com esse nome. Escolha outro nome."] = "A built-in mode already has this name. Choose another name.",
        ["Padrão"] = "Default", ["Modo Avançado"] = "Advanced Mode", ["Modo Minimalista"] = "Minimal Mode", ["Modo Completo"] = "Full Mode",
        ["Modo Manutenção"] = "Maintenance Mode", ["Modo Debloat & Privacidade"] = "Debloat & Privacy Mode",
        ["Modo padrão completo: exibe todas as otimizações e ferramentas disponíveis no aplicativo."] = "Full default mode: shows every optimization and tool available in the app.",
        ["Foco em jogos: latência reduzida, Game Mode, energia de alto desempenho e limpeza rápida."] = "Gaming focus: lower latency, Game Mode, high-performance power and quick cleanup.",
        ["Apenas o essencial: visual limpo com otimização padrão, limpeza de temporários e reversão."] = "Just the essentials: clean view with standard optimization, temp cleanup and restore.",
        ["Exibe todas as otimizações, testes de benchmark e ferramentas de manutenção do Windows."] = "Shows every optimization, benchmark and Windows maintenance tool.",
        ["Ferramentas de integridade e diagnósticos: SFC, DISM, CHKDSK, Updates e análise de saúde."] = "Integrity and diagnostic tools: SFC, DISM, CHKDSK, Updates and health analysis.",
        ["Remoção de bloatwares, serviços em segundo plano desnecessários e preservação de privacidade."] = "Removes bloatware and unnecessary background services and protects privacy.",

        // ---------- Drivers e ISOs ----------
        ["Drivers & Utilitários"] = "Drivers & utilities", ["Todos"] = "All", ["Placas de Vídeo"] = "Graphics cards", ["Chipset & CPU"] = "Chipset & CPU",
        ["Áudio"] = "Audio", ["Rede"] = "Network", ["Utilitários"] = "Utilities", ["Vídeo / GPU"] = "Video / GPU",
        ["Filtrar drivers por nome, fabricante ou categoria"] = "Filter drivers by name, vendor or category",
        ["Filtrar por nome, fabricante ou categoria…"] = "Filter by name, vendor or category…", ["Download Alternativo"] = "Alternative download",
        ["Baixar"] = "Download", ["Desmontar"] = "Unmount",
        ["Nenhum driver encontrado para os filtros selecionados."] = "No drivers found for the selected filters.",
        ["Recomendado para o seu PC"] = "Recommended for your PC", ["Disponível para download oficial"] = "Available for official download",
        ["Baixar (Site Oficial)"] = "Download (official site)", ["Baixar via Google Drive (Driver Clean)"] = "Download via Google Drive (Driver Clean)",
        ["Baixar via Google Drive"] = "Download via Google Drive", ["Executar Instalador"] = "Run installer", ["Abrir Pasta"] = "Open folder",
        ["Download Direto"] = "Direct download", ["Iniciando download..."] = "Starting download...", ["Download Concluído"] = "Download complete",
        ["Falha no download direto. Abrindo página oficial no navegador..."] = "Direct download failed. Opening the official page in the browser...",
        ["Driver Clean Otimizado"] = "Optimized Clean Driver",
        ["Pacote oficial de driver limpo fornecido por Pedro Queiroz. Configurado sem telemetria, com foco em menor latência de quadros e máximo FPS em jogos."] = "Official clean driver package by Pedro Queiroz. No telemetry, focused on lower frame latency and maximum FPS in games.",
        ["Monta um instalador customizado do driver NVIDIA, removendo telemetria e componentes desnecessários (ex.: GeForce Experience). Ideal para instalação limpa de verdade e menor latência."] = "Builds a custom NVIDIA driver installer, stripping telemetry and unneeded components (e.g., GeForce Experience). Ideal for a truly clean install with lower latency.",
        ["Ferramenta avançada para editar perfis ocultos do driver NVIDIA por jogo: modos de latência, LOD bias, limite de FPS, flags de compatibilidade e muito mais."] = "Advanced tool to edit hidden NVIDIA driver profiles per game: latency modes, LOD bias, FPS limits, compatibility flags and more.",
        ["Baixe e atualize os drivers essenciais de vídeo, chipset, rede e áudio para máxima taxa de quadros e menor latência."] = "Download and update essential video, chipset, network and audio drivers for maximum frame rate and lower latency.",
        ["ISOs do Windows"] = "Windows ISOs", ["Central de Instalação & Download do Windows 11"] = "Windows 11 install & download center",
        ["Qualquer usuário pode baixar a ISO oficial do Windows 11 diretamente dos servidores da Microsoft ou utilizar a versão personalizada Pedro Queiroz para máxima performance."] = "Anyone can download the official Windows 11 ISO straight from Microsoft's servers or use the custom Pedro Queiroz edition for maximum performance.",
        ["Imagem original e limpa direto da Microsoft. Permite gerar pendrive bootável via Media Creation Tool ou baixar a imagem ISO oficial para instalação limpa."] = "Original, clean image straight from Microsoft. Create a bootable USB with the Media Creation Tool or download the official ISO for a clean install.",
        ["ISO personalizada do Windows 11 com ajustes de latência, telemetria desativada e máxima performance para jogos."] = "Custom Windows 11 ISO with latency tweaks, telemetry disabled and maximum gaming performance.",
        ["Otimizações de registro, debloat de UWP, plano de alto desempenho e Game Mode pré-configurados."] = "Registry optimizations, UWP debloat, high-performance plan and Game Mode preconfigured.",
        ["Imagem ISO personalizada adicionada pelo usuário."] = "Custom ISO image added by the user.",
        ["Adicionar Imagem ISO"] = "Add ISO image", ["Montar ISO"] = "Mount ISO", ["Copiar Caminho"] = "Copy path", ["Copiar Link"] = "Copy link",
        ["Localizar no Meu PC"] = "Find on my PC", ["Baixar ISO Oficial"] = "Download official ISO", ["Oficial 24H2"] = "Official 24H2",
        ["Disponível para Download Gratuito"] = "Free download available", ["Imagem disponível para download / associação"] = "Image available to download / link",
        ["Download & Gerenciamento"] = "Download & management", ["Selecionar Imagem ISO do Windows"] = "Select a Windows ISO image",
        ["ISO Adicionada"] = "ISO added", ["ISO Montada"] = "ISO mounted", ["ISO Desmontada"] = "ISO unmounted",
        ["A imagem ISO foi desmontada com sucesso."] = "The ISO image was unmounted.",
        ["A imagem ISO foi montada com sucesso. Acesse 'Este Computador' para visualizar a unidade."] = "The ISO image was mounted. Open 'This PC' to see the drive.",
        ["Caminho copiado para a área de transferência!"] = "Path copied to the clipboard!", ["Link oficial copiado para a área de transferência!"] = "Official link copied to the clipboard!",

        // ---------- Saída do script (sem acentos, como o script escreve) ----------
        ["Criando ponto de restauracao"] = "Creating restore point", ["CRIANDO PONTO DE RESTAURACAO"] = "CREATING RESTORE POINT",
        ["Habilitando restauracao do sistema no disco"] = "Enabling System Restore on the drive",
        ["APLICANDO OTIMIZACOES GERAIS"] = "APPLYING GENERAL OPTIMIZATIONS", ["APLICANDO OTIMIZACOES DE DESEMPENHO MAXIMO PARA JOGOS"] = "APPLYING MAXIMUM GAMING PERFORMANCE TWEAKS",
        ["DEBLOAT DO WINDOWS"] = "WINDOWS DEBLOAT", ["REVERTER ULTIMA OTIMIZACAO"] = "UNDO LAST OPTIMIZATION", ["ANALISANDO O PC (NAO ALTERA NADA)"] = "ANALYZING THE PC (CHANGES NOTHING)",
        ["VERIFICANDO ARQUIVOS DO SISTEMA (SFC)"] = "CHECKING SYSTEM FILES (SFC)", ["REPARANDO IMAGEM DO WINDOWS (DISM)"] = "REPAIRING WINDOWS IMAGE (DISM)",
        ["VERIFICANDO O DISCO (CHKDSK)"] = "CHECKING THE DISK (CHKDSK)", ["VERIFICANDO O WINDOWS UPDATE"] = "CHECKING WINDOWS UPDATE",
        ["TESTE DE DESEMPENHO (BENCHMARK)"] = "PERFORMANCE TEST (BENCHMARK)", ["REPARANDO CONFIGURACOES DO WINDOWS"] = "REPAIRING WINDOWS SETTINGS",
        ["OTIMIZACAO PADRAO CONCLUIDA!"] = "STANDARD OPTIMIZATION FINISHED!", ["OTIMIZACAO AVANCADA CONCLUIDA!"] = "ADVANCED OPTIMIZATION FINISHED!",
        ["DEBLOAT CONCLUIDO!"] = "DEBLOAT FINISHED!", ["REVERSAO CONCLUIDA"] = "RESTORE FINISHED", ["PROBLEMAS ENCONTRADOS"] = "ISSUES FOUND",
        ["RECOMENDACOES"] = "RECOMMENDATIONS", ["ANTES -> DEPOIS (DESDE O ULTIMO BENCHMARK)"] = "BEFORE -> AFTER (SINCE THE LAST BENCHMARK)",
        ["PC HEALTH SCORE"] = "PC HEALTH SCORE",
        ["Seu PC deve estar mais leve e rapido."] = "Your PC should now be lighter and faster.",
        ["Reinicie o PC para aplicar todas as mudancas."] = "Restart the PC to apply all changes.",
        ["Plano de energia 'Alto Desempenho'"] = "Power plan 'High Performance'", ["Plano de energia 'Desempenho Maximo'"] = "Power plan 'Ultimate Performance'",
        ["Plano de energia Qrz"] = "Qrz power plan",
        ["Limpando fila de impressao"] = "Clearing the print queue", ["Otimizando/TRIM das unidades de disco"] = "Optimizing/TRIM of disk drives",
        ["Limpando cache DNS"] = "Clearing DNS cache", ["Executando limpeza de disco (cleanmgr)"] = "Running Disk Cleanup (cleanmgr)",
        ["Desativando sugestoes, anuncios e apps instalados automaticamente"] = "Disabling suggestions, ads and auto-installed apps",
        ["Limitando o upload de atualizacoes a rede local (Delivery Optimization)"] = "Limiting update uploads to the local network (Delivery Optimization)",
        ["Verificando agendador multimidia do Windows (MMCSS)"] = "Checking the Windows multimedia scheduler (MMCSS)",
        ["Desativando gravacao de jogos em segundo plano"] = "Disabling background game recording",
        ["Priorizando CPU para o jogo em foco"] = "Prioritizing the CPU for the focused game", ["Reduzindo latencia de rede/multimidia"] = "Reducing network/multimedia latency",
        ["Desativando limitacao de rede (Throttling)"] = "Disabling network throttling", ["Desativando Xbox Game Bar / Game DVR"] = "Disabling Xbox Game Bar / Game DVR",
        ["Ativando Modo de Jogo do Windows"] = "Enabling Windows Game Mode", ["Habilitando GPU Scheduling por hardware"] = "Enabling hardware GPU scheduling",
        ["Ajustando efeitos visuais p/ desempenho"] = "Adjusting visual effects for performance", ["Desativando aceleracao do ponteiro do mouse"] = "Disabling mouse pointer acceleration",
        ["Ajustando SysMain e Windows Search"] = "Adjusting SysMain and Windows Search", ["Otimizando unidades de disco"] = "Optimizing disk drives",
        ["Desativando experiencias personalizadas com dados de diagnostico"] = "Disabling personalized experiences using diagnostic data",
        ["Ativando otimizacoes para jogos em janela"] = "Enabling optimizations for windowed games",
        ["Desativando limitacao de energia de processos (Power Throttling)"] = "Disabling process power throttling (Power Throttling)",
        ["Telemetria e diagnostico desativados"] = "Telemetry and diagnostics disabled", ["Cortana removida"] = "Cortana removed", ["Widgets removidos"] = "Widgets removed",
        ["OneDrive removido"] = "OneDrive removed", ["Servico de impressao desativado"] = "Print service disabled", ["Bluetooth desativado"] = "Bluetooth disabled",
        ["Servico de Fax desativado"] = "Fax service disabled", ["Remote Registry desativado"] = "Remote Registry disabled", ["Assistencia Remota desativada"] = "Remote Assistance disabled",
        ["Servico de Mapas desativado"] = "Maps service disabled", ["Servicos adicionais de diagnostico desativados"] = "Additional diagnostic services disabled",
        ["Tarefas de telemetria desativadas"] = "Telemetry tasks disabled", ["Desativando tarefas opcionais de CEIP e feedback"] = "Disabling optional CEIP and feedback tasks", ["Apps desnecessarios removidos"] = "Unnecessary apps removed",
        ["ID de publicidade desativado"] = "Advertising ID disabled", ["Pesquisa na web removida do menu Iniciar"] = "Web search removed from the Start menu",
        ["Historico de atividades desativado"] = "Activity history disabled", ["Desativando Copilot integrado do Windows"] = "Disabling integrated Windows Copilot",
        ["Limitando dados de diagnostico ao nivel obrigatorio"] = "Limiting diagnostic data to the required level",
        ["Efeitos visuais ajustados"] = "Visual effects adjusted", ["Indexacao do Windows Search desativada"] = "Windows Search indexing disabled",
        ["Arquivos temporarios removidos"] = "Temporary files removed",
        ["[ i] Xbox/Game Bar: mantido (nao e alterado nesta secao)."] = "[ i] Xbox/Game Bar: kept (not changed in this section).",
        ["Isso pode demorar alguns minutos..."] = "This may take a few minutes...", ["Isso pode demorar varios minutos e precisa de internet..."] = "This may take several minutes and needs internet...",
        ["Executando uma verificacao online (sem precisar reiniciar)..."] = "Running an online check (no restart needed)...",
        ["Coletando informacoes..."] = "Collecting information...", ["Medindo CPU, RAM, disco, tempo de boot e latencia..."] = "Measuring CPU, RAM, disk, boot time and latency...",
        ["(estimativa com base no diagnostico atual - nao e um benchmark)"] = "(estimate based on the current diagnostics - not a benchmark)",
        ["Nenhum problema relevante encontrado. Seu PC esta em bom estado!"] = "No relevant issues found. Your PC is in good shape!",
        ["Nenhuma acao recomendada no momento"] = "No action recommended right now", ["Modo de Jogo: Ativo"] = "Game Mode: On", ["TRIM: Ativo"] = "TRIM: On",
        ["Windows Search ativo (pode consumir recursos em HDs mais lentos)"] = "Windows Search running (may use resources on slower HDDs)",
        ["TRIM parece desativado no SSD"] = "TRIM seems to be disabled on the SSD", ["Ha uma reinicializacao pendente"] = "A restart is pending",
        ["Pouco espaco livre em disco"] = "Low free disk space",
        ["Desative programas desnecessarios em Ferramentas > Inicializacao do Windows"] = "Disable unnecessary programs in Optimizations > Windows startup",
        ["Desative programas desnecessarios na pagina Inicializacao do aplicativo"] = "Disable unnecessary programs on the app's Startup page",
        ["Ja ha um plano de energia de desempenho ativo; nenhuma mudanca necessaria."] = "A performance power plan is already active; no change needed.",
        ["Este PC so oferece o plano Equilibrado (comum em notebooks com Modern Standby); plano atual mantido."] = "This PC only offers the Balanced plan (common on laptops with Modern Standby); current plan kept.",
        ["Servico de impressao desativado ou ausente; nada a limpar."] = "Print service disabled or missing; nothing to clear.",
        ["Suspensao seletiva de USB mantida: ela so e alterada junto com o plano de energia do otimizador."] = "USB selective suspend kept: it only changes together with the optimizer's power plan.",
        ["OneDrive nao esta instalado; nada a fazer."] = "OneDrive is not installed; nothing to do.",
        ["OneDrive (reinstale pelo site da Microsoft se precisar)"] = "OneDrive (reinstall from Microsoft's website if needed)",
        ["Desinstalador do OneDrive nao encontrado ou sem assinatura da Microsoft"] = "OneDrive uninstaller not found or not signed by Microsoft",
        ["A limpeza de disco passou de 15 minutos e foi interrompida."] = "Disk cleanup took over 15 minutes and was stopped.",
        ["CPU E MEMORIA"] = "CPU AND MEMORY",
        ["Aplique a Versao Padrao para usar o plano de energia de alto desempenho"] = "Apply Standard Mode to use the high-performance power plan",
        ["Reinicie o computador para concluir atualizacoes pendentes"] = "Restart the computer to finish pending updates",
        ["Ultimas atualizacoes instaladas"] = "Latest installed updates", ["Nenhuma reinicializacao pendente."] = "No pending restart.",
        ["Ha reinicializacao pendente relacionada a atualizacoes."] = "There is a pending restart related to updates.",
        ["Nao foi possivel checar o servico do Windows Update."] = "Could not check the Windows Update service.",
        ["winsat indisponivel: leitura estimada (pode estar acima do real por causa do cache)"] = "winsat unavailable: estimated read speed (may be higher than real because of caching)",
        ["Este e o primeiro benchmark salvo. Rode novamente depois de"] = "This is the first saved benchmark. Run it again after",
        ["otimizar o PC para ver a comparacao antes -> depois."] = "optimizing the PC to see the before -> after comparison.",
        ["Obs: isso NAO garante ganho de FPS - mede CPU/RAM/disco, boot e latencia."] = "Note: this does NOT guarantee FPS gains - it measures CPU/RAM/disk, boot and latency.",
        ["Ativando modo MSI (interrupcoes por mensagem) na placa de video"] = "Enabling MSI mode (message-signaled interrupts) on the graphics card",
        ["Nenhuma placa de video PCI encontrada; ajuste ignorado."] = "No PCI graphics card found; tweak skipped.",
        ["Medindo latencia DPC e interrupcoes (5 s)..."] = "Measuring DPC latency and interrupts (5 s)...",
        ["LATENCIA (DPC / INTERRUPCOES)"] = "LATENCY (DPC / INTERRUPTS)",
        ["Placa de video sem modo MSI (interrupcoes por linha IRQ)"] = "Graphics card without MSI mode (line-based IRQ interrupts)",
        ["Timer HPET forcado no boot (useplatformclock) - aumenta a latencia"] = "HPET timer forced at boot (useplatformclock) - increases latency",
        ["Memoria em single channel (1 pente) - 2 pentes dobram a largura de banda"] = "Memory in single channel (1 stick) - 2 sticks double the bandwidth",
        ["Aplique a Versao Avancada para ativar o modo MSI da placa de video"] = "Apply Advanced Mode to enable MSI mode on the graphics card",
        ["Ative o perfil XMP/EXPO na BIOS (menu BIOS / UEFI > Reiniciar na BIOS/UEFI)"] = "Enable the XMP/EXPO profile in the BIOS (BIOS / UEFI menu > Restart into BIOS/UEFI)",
        ["Remova o HPET forcado: bcdedit /deletevalue useplatformclock (como administrador)"] = "Remove the forced HPET: bcdedit /deletevalue useplatformclock (as administrator)",
        ["O Windows ja prioriza o programa em foco; nenhuma mudanca necessaria."] = "Windows already prioritizes the focused program; no change needed.",
        ["Integridade de Memoria (HVCI) ativa - pode custar de 5% a 10% de FPS em alguns jogos"] = "Memory Integrity (HVCI) on - may cost 5% to 10% FPS in some games",
        ["Se o PC e so para jogos, avalie desligar a Integridade de Memoria em Seguranca do Windows > Seguranca do dispositivo (reduz a protecao)"] = "If the PC is only for gaming, consider turning off Memory Integrity in Windows Security > Device security (reduces protection)",
        ["Falha ao desativar a animacao de janelas"] = "Failed to disable window animation",
        ["Placa-mae"] = "Motherboard", ["Nucleos"] = "Cores", ["Memoria"] = "Memory", ["Temperatura"] = "Temperature", ["Latencia DPC"] = "DPC latency", ["Modo MSI"] = "MSI mode",
        ["Nao ha nenhuma otimizacao registrada para reverter no momento."] = "There is no recorded optimization to restore right now.",
        ["(Isso acontece se voce ainda nao rodou a Padrao/Gamer/Debloat nesta"] = "(This happens if you haven't run Standard/Advanced/Debloat on this",
        ["instalacao, ou se a ultima ja foi revertida)."] = "installation, or if the last one was already restored).",
        ["Nao foi possivel ler o registro da ultima otimizacao (arquivo corrompido)."] = "Could not read the last optimization record (corrupted file).",
        ["Os itens abaixo fazem parte da otimizacao revertida, mas NAO podem"] = "The items below are part of the restored optimization but CANNOT",
        ["ser desfeitos automaticamente:"] = "be undone automatically:",
        ["Arquivos excluidos exigem backup proprio; apps podem exigir reinstalacao."] = "Deleted files need their own backup; apps may need reinstalling.",
        ["Nenhuma alteracao foi feita."] = "No changes were made.",
        ["Modo rapido ativado: todas as etapas abaixo serao aplicadas automaticamente."] = "Quick mode on: all steps below will be applied automatically.",
        ["Agendador multimidia (MMCSS): nenhuma correcao necessaria."] = "Multimedia scheduler (MMCSS): no fix needed.",
        ["Disco do sistema nao e SSD; SysMain mantido."] = "System drive is not an SSD; SysMain kept.",
        ["GPU/driver sem suporte a agendamento por hardware (HAGS); ajuste ignorado."] = "GPU/driver doesn't support hardware scheduling (HAGS); tweak skipped.",
        ["Notebook detectado; Power Throttling mantido para preservar a bateria."] = "Laptop detected; Power Throttling kept to save battery.",
        ["Recurso disponivel apenas no Windows 11; ajuste ignorado."] = "Feature only available on Windows 11; tweak skipped.",
        ["Use a Limpeza rapida para liberar espaco"] = "Use Quick cleanup to free space",
        ["Cortana (app removido - reinstale pela Microsoft Store se precisar)"] = "Cortana (app removed - reinstall from the Microsoft Store if needed)",
        ["Widgets/Web Experience (app removido - reinstale pela Microsoft Store se precisar)"] = "Widgets/Web Experience (app removed - reinstall from the Microsoft Store if needed)",
        ["OneDrive (instalador nao encontrado para reinstalacao automatica)"] = "OneDrive (installer not found for automatic reinstall)",
        ["Apps pre-instalados removidos (Bing News/Weather, Solitaire, Teams, Skype, YourPhone, etc - reinstale pela Microsoft Store se precisar)"] = "Preinstalled apps removed (Bing News/Weather, Solitaire, Teams, Skype, YourPhone, etc - reinstall from the Microsoft Store if needed)",
        ["Cortana"] = "Cortana", ["Widgets/Web Experience"] = "Widgets/Web Experience", ["Apps pre-instalados removidos"] = "Preinstalled apps removed", ["OneDrive"] = "OneDrive",
        ["Abra o aplicativo como administrador."] = "Open the app as administrator.",
        ["Nao disponivel"] = "Not available", ["Desconhecido"] = "Unknown", ["DISCO"] = "DISK", ["INICIALIZACAO"] = "STARTUP", ["Disco"] = "Disk",
        ["Atalho de Limpeza Rápida configurado"] = "Quick Cleanup shortcut configured", ["Atalhos de Limpeza Rápida removidos"] = "Quick Cleanup shortcuts removed",
        ["Barra de tarefas All Black aplicada"] = "All Black taskbar applied", ["Barra de tarefas padrão restaurada"] = "Default taskbar restored",
        ["Reinício para a BIOS/UEFI solicitado pelo usuário."] = "Restart into BIOS/UEFI requested by the user.",
        ["Temporários do usuário e do Windows processados."] = "User and Windows temporary files processed.",
        ["Concluídos"] = "Done", ["Falhas"] = "Failures", ["Avisos"] = "Warnings",
        ["Ignorada"] = "Skipped", ["Pulado"] = "Skipped", ["Leitura"] = "Read", ["Escrita"] = "Write",
    };

    private static readonly (Regex Regex, Func<Match, string> Build)[] Patterns =
    {
        // Interface
        P(@"^(\d+) ajustes disponíveis$", m => $"{m.Groups[1].Value} tweaks available"),
        P(@"^(\d+) de (\d+) ajustes selecionados$", m => $"{m.Groups[1].Value} of {m.Groups[2].Value} tweaks selected"),
        P(@"^(\d+) ajustes selecionados\. Um ponto de restauração é criado antes de qualquer alteração\.$", m => $"{m.Groups[1].Value} tweaks selected. A restore point is created before any change."),
        P(@"^(.+) MB podem ser liberados$", m => $"{m.Groups[1].Value} MB can be freed"),
        P(@"^(\d+) arquivos$", m => $"{m.Groups[1].Value} files"),
        P(@"^([\d.,]+ [KMGT]B) de ([\d.,]+ [KMGT]B)$", m => $"{m.Groups[1].Value} of {m.Groups[2].Value}"),
        P(@"^(\d+)% livre$", m => $"{m.Groups[1].Value}% free"),

        // Linhas do log de atividade: "[data] [NIVEL] mensagem"
        P(@"^(\[\d{4}-\d{2}-\d{2} [\d:]+\] \[\w+\]) (.+)$", m => $"{m.Groups[1].Value} {T(m, 2)}"),
        P(@"^Limpeza: (\d+) removidos, (\d+) preservados/ignorados, (.+) MB liberados\.$", m => $"Cleanup: {m.Groups[1].Value} removed, {m.Groups[2].Value} kept/skipped, {m.Groups[3].Value} MB freed."),
        P(@"^\[(OK|!!|FALHA|INFO|AVISO|IGNORADA|IGNORADO|ERRO)\] (.+)$", m => $"[{m.Groups[1].Value switch { "FALHA" => "FAILED", "ERRO" => "ERROR", "AVISO" => "WARNING", "IGNORADA" or "IGNORADO" => "SKIPPED", var v => v }}] {T(m, 2)}"),
        P(@"^(\[\d+/\d+\])\s+(.+)$", m => $"{m.Groups[1].Value} {T(m, 2)}"),
        P(@"^([\d.,]+) arquivos removidos$", m => $"{m.Groups[1].Value} files removed"),
        P(@"^([\d.,]+) ignorados$", m => $"{m.Groups[1].Value} skipped"),
        P(@"^([\d.,]+) MB liberados$", m => $"{m.Groups[1].Value} MB freed"),
        P(@"^Iniciando: (.+)$", m => $"Starting: {m.Groups[1].Value}"),
        P(@"^Execução concluída: (.+)$", m => $"Run finished: {m.Groups[1].Value}"),
        P(@"^Inicialização: (.+) (ativado|desativado)$", m => $"Startup: {m.Groups[1].Value} {(m.Groups[2].Value == "ativado" ? "enabled" : "disabled")}"),
        P(@"^Atualização (.+) verificada por SHA256; iniciando instalação silenciosa\.$", m => $"Update {m.Groups[1].Value} verified with SHA256; starting silent install."),
        P(@"^Não foi possível verificar atualizações: (.+)$", m => $"Could not check for updates: {m.Groups[1].Value}"),
        P(@"^Download direto de (.+) falhou: (.+)$", m => $"Direct download of {m.Groups[1].Value} failed: {m.Groups[2].Value}"),
        P(@"^Selecionado: (.+) MB$", m => $"Selected: {m.Groups[1].Value} MB"),
        P(@"^Previsto: (.+) MB → liberado: (.+) MB · (\d+) removidos · (\d+) preservados$", m => $"Expected: {m.Groups[1].Value} MB → freed: {m.Groups[2].Value} MB · {m.Groups[3].Value} removed · {m.Groups[4].Value} kept"),
        P(@"^ligado há (.+)$", m => $"up for {m.Groups[1].Value}"),
        P(@"^Perfil selecionado: (.+)\. Você sempre revisa os ajustes antes de aplicar\.$", m => $"Selected profile: {T(m, 1)}. You always review the tweaks before applying."),
        P(@"^Perfil ativo: (.+)$", m => $"Active profile: {T(m, 1)}"),
        P(@"^Backup pendente: (.+)$", m => $"Pending backup: {T(m, 1)}"),
        P(@"^(\d+) itens registrados$", m => $"{m.Groups[1].Value} items recorded"),
        P(@"^(.+) · (\d+) ativas$", m => $"{T(m, 1)} · {m.Groups[2].Value} active"),
        P(@"^(.+)  (\d+)$", m => $"{T(m, 1)}  {m.Groups[2].Value}"),
        P(@"^(.+) \((\d+)\)$", m => $"{T(m, 1)} ({m.Groups[2].Value})"),
        P(@"^Exibindo (\d+) de (\d+) otimizações configuradas\.$", m => $"Showing {m.Groups[1].Value} of {m.Groups[2].Value} configured optimizations."),
        P(@"^(.+) — concluído\. Confira os resultados na atividade\.$", m => $"{T(m, 1)} — done. Check the results in the activity log."),
        P(@"^(.+) — cancelado\. O que já foi aplicado aparece em Atividade e reversão\.$", m => $"{T(m, 1)} — cancelled. What was already applied shows up in Activity & restore."),
        P(@"^Operação cancelada pelo usuário: (.+)$", m => $"Operation cancelled by the user: {m.Groups[1].Value}"),
        P(@"^Erro inesperado: (.+)$", m => $"Unexpected error: {m.Groups[1].Value}"),
        P(@"^Erro em segundo plano: (.+)$", m => $"Background error: {m.Groups[1].Value}"),
        P(@"^Erro fatal: (.+)$", m => $"Fatal error: {m.Groups[1].Value}"),
        P(@"^Link inválido: (.*)$", m => $"Invalid link: {m.Groups[1].Value}"),
        P(@"^Link ignorado \(não é um endereço da web\): (.*)$", m => $"Link ignored (not a web address): {m.Groups[1].Value}"),
        P(@"^Não foi possível abrir o navegador: (.+)$", m => $"Could not open the browser: {m.Groups[1].Value}"),
        P(@"^Não foi possível abrir a pasta: (.+)$", m => $"Could not open the folder: {m.Groups[1].Value}"),
        P(@"^Não foi possível abrir a entrada: (.+)$", m => $"Could not open the entry: {m.Groups[1].Value}"),
        P(@"^Agendador de Tarefas (\\.*)$", m => $"Task Scheduler {m.Groups[1].Value}"),
        P(@"^(\d+) ativos?$", m => $"{m.Groups[1].Value} enabled"),
        P(@"^(\d+) desativados?$", m => $"{m.Groups[1].Value} disabled"),
        P(@"^(\d+) (?:item do Windows oculto|itens do Windows ocultos)$", m => $"{m.Groups[1].Value} Windows {(m.Groups[1].Value == "1" ? "entry" : "entries")} hidden"),
        P(@"^(\d+) sem assinatura válida$", m => $"{m.Groups[1].Value} without a valid signature"),
        P(@"^(\d+) (?:arquivo não encontrado|arquivos não encontrados)$", m => $"{m.Groups[1].Value} {(m.Groups[1].Value == "1" ? "file" : "files")} not found"),
        P(@"^Desativar o início automático de ""(.+)""\?\s+O serviço passa para Manual: só inicia quando algum programa precisar dele\. Drivers, antitrapaças e jogos podem depender de serviços; se algo parar de funcionar, marque o item de novo\.$",
            m => $"Disable automatic start for \"{m.Groups[1].Value}\"?\n\nThe service becomes Manual: it only starts when a program needs it. Drivers, anti-cheats and games may depend on services; if something stops working, check the entry again."),
        P(@"^""(.+)"" faz parte do Windows\. Desativar pode afetar recursos do sistema\.\s+Deseja continuar\?$", m => $"\"{m.Groups[1].Value}\" is part of Windows. Disabling it may affect system features.\n\nContinue?"),
        P(@"^Inicialização: não foi possível verificar as assinaturas digitais: (.+)$", m => $"Startup: could not verify digital signatures: {m.Groups[1].Value}"),
        P(@"^Inicialização: não foi possível ler (.+?): (.+)$", m => $"Startup: could not read {T(m, 1)}: {m.Groups[2].Value}"),
        P(@"^cerca de (.+) restantes$", m => $"about {m.Groups[1].Value} left"),
        P(@"^Ativado: (.+)$", m => $"Activated: {T(m, 1)}"),
        P(@"^Modo de energia alterado: (.+)$", m => $"Power mode changed: {T(m, 1)}"),
        P(@"^O Windows recusou a troca do (plano|modo) de energia \(código (\d+)\)\.$", m => $"Windows refused to change the power {(m.Groups[1].Value == "plano" ? "plan" : "mode")} (code {m.Groups[2].Value})."),
        P(@"^Atalho de modo de energia: (.+)$", m => $"Power mode shortcut: {m.Groups[1].Value}"),
        P(@"^Modo de energia: (.+)$", m => $"Power mode: {T(m, 1)}"),
        P(@"^Não foi possível detectar a placa de vídeo: (.+)$", m => $"Could not detect the graphics card: {m.Groups[1].Value}"),
        P(@"^Não foi possível salvar suas preferências: (.+)$", m => $"Could not save your preferences: {m.Groups[1].Value}"),
        P(@"^Preferências não foram salvas: (.+)$", m => $"Preferences were not saved: {m.Groups[1].Value}"),
        P(@"^(\d+) concluídos$", m => $"{m.Groups[1].Value} done"),
        P(@"^(\d+) falhas$", m => $"{m.Groups[1].Value} failures"),
        P(@"^(\d+) avisos$", m => $"{m.Groups[1].Value} warnings"),
        P(@"^(\d+) de (\d+) ativos$", m => $"{m.Groups[1].Value} of {m.Groups[2].Value} enabled"),
        P(@"^(.+): (ativado|desativado) na inicialização\.$", m => $"{m.Groups[1].Value}: {(m.Groups[2].Value == "ativado" ? "enabled" : "disabled")} at startup."),
        P(@"^Não foi possível alterar este item: (.+)$", m => $"Could not change this item: {m.Groups[1].Value}"),
        P(@"^Versão (v[\d.]+)$", m => $"Version {m.Groups[1].Value}"),
        P(@"^Versão atual (v[\d.]+)$", m => $"Current version {m.Groups[1].Value}"),
        P(@"^Válida até (.+)$", m => $"Valid until {m.Groups[1].Value}"),
        P(@"^Sua licença expirou em (.+)\.$", m => $"Your license expired on {m.Groups[1].Value}."),
        P(@"^Até (\S+) \((\d+) dias\)$", m => $"Until {m.Groups[1].Value} ({m.Groups[2].Value} days)"),
        P(@"^Até (\S+) \(vence hoje\)$", m => $"Until {m.Groups[1].Value} (expires today)"),
        P(@"^Até (\S+) \(vence amanhã\)$", m => $"Until {m.Groups[1].Value} (expires tomorrow)"),
        P(@"^Sua licença vence em (\d+) dias$", m => $"Your license expires in {m.Groups[1].Value} days"),
        P(@"^A chave atual vale até (.+)\. Para renovar, abra um ticket de renovação no Discord e pague via Pix\.$", m => $"The current key is valid until {m.Groups[1].Value}. To renew, open a renewal ticket on Discord and pay via Pix."),
        P(@"^Nova versão disponível: (.+)$", m => $"New version available: {m.Groups[1].Value}"),
        P(@"^Atualizar para (.+)$", m => $"Update to {m.Groups[1].Value}"),
        P(@"^Baixar (v?[\d.]+)$", m => $"Download {m.Groups[1].Value}"),
        P(@"^Atualização disponível: (.+)$", m => $"Update available: {m.Groups[1].Value}"),
        P(@"^A versão (.+) está disponível\. Deseja atualizar agora\?$", m => $"Version {m.Groups[1].Value} is available. Update now?"),
        P(@"^Baixando instalador\.\.\. (.+)$", m => $"Downloading installer... {m.Groups[1].Value}"),
        P(@"^Baixando\.\.\. (.+)$", m => $"Downloading... {m.Groups[1].Value}"),
        P(@"^Falha na atualização: (.+)$", m => $"Update failed: {m.Groups[1].Value}"),
        P(@"^Placa de vídeo detectada: (.+) • Todos os drivers com links oficiais e opção de download\.$", m => $"Detected graphics card: {m.Groups[1].Value} • All drivers with official links and download option."),
        P(@"^Disponível Localmente(.*)$", m => $"Available locally{m.Groups[1].Value}"),
        P(@"^Instalador disponível: (.+)$", m => $"Installer available: {m.Groups[1].Value}"),
        P(@"^Concluído! Salvo em: (.+)$", m => $"Done! Saved to: {m.Groups[1].Value}"),
        P(@"^Download de '(.+)' concluído com sucesso!\s*Salvo em:\s*(.+?)\s*Deseja executar o instalador agora\?$", m => $"'{m.Groups[1].Value}' downloaded!\n\nSaved to:\n{m.Groups[2].Value}\n\nRun the installer now?"),
        P(@"^Perfil '(.+)' ativado com sucesso!$", m => $"Profile '{T(m, 1)}' activated!"),
        P(@"^Perfil '(.+)' atualizado com sucesso!$", m => $"Profile '{T(m, 1)}' updated!"),
        P(@"^Perfil '(.+)' excluído\.$", m => $"Profile '{T(m, 1)}' deleted."),
        P(@"^Novo perfil '(.+)' criado e ativado com sucesso!$", m => $"New profile '{m.Groups[1].Value}' created and activated!"),
        P(@"^Deseja realmente excluir o perfil '(.+)'\?$", m => $"Do you really want to delete the profile '{m.Groups[1].Value}'?"),
        P(@"^(.+) \(Ativo\)$", m => $"{T(m, 1)} (Active)"),
        P(@"^ISO '(.+)' adicionada com sucesso!$", m => $"ISO '{m.Groups[1].Value}' added!"),
        P(@"^A imagem ISO foi montada na unidade (.+) e aberta no Explorador de Arquivos\.$", m => $"The ISO image was mounted as drive {m.Groups[1].Value} and opened in File Explorer."),
        P(@"^O arquivo ISO não foi localizado:\s*(.+)$", m => $"The ISO file was not found:\n{m.Groups[1].Value}"),
        P(@"^Localizar arquivo para (.+)$", m => $"Find file for {m.Groups[1].Value}"),
        P(@"^Falha ao (abrir navegador|aplicar alteração|desmontar ISO|montar ISO|iniciar o instalador): (.+)$", m => $"Failed to {m.Groups[1].Value switch { "abrir navegador" => "open the browser", "aplicar alteração" => "apply the change", "desmontar ISO" => "unmount the ISO", "montar ISO" => "mount the ISO", _ => "start the installer" }}: {m.Groups[2].Value}"),
        P(@"^Não foi possível abrir (.+)\.$", m => $"Could not open {T(m, 1)}."),
        P(@"^Não foi possível (alterar os atalhos|reiniciar na BIOS): (.+)$", m => $"{(m.Groups[1].Value.StartsWith("alterar") ? "Could not change the shortcuts" : "Could not restart into BIOS")}: {m.Groups[2].Value}"),
        P(@"^Limpeza concluída\. (.+) MB liberados$", m => $"Cleanup finished. {m.Groups[1].Value} MB freed"),
        P(@"^(.+) — (.+) MB · (\d+) arquivos$", m => $"{T(m, 1)} — {m.Groups[2].Value} MB · {m.Groups[3].Value} files"),

        // Saída do script
        P(@"^(.+) \(falhou ou nao se aplica neste PC\)$", m => $"{T(m, 1)} (failed or doesn't apply to this PC)"),
        P(@"^Resumo: (\d+) aplicado\(s\), (\d+) pulado\(s\), (\d+) falha\(s\)$", m => $"Summary: {m.Groups[1].Value} applied, {m.Groups[2].Value} skipped, {m.Groups[3].Value} failed"),
        P(@"^Resumo: (\d+) aplicado\(s\), (\d+) falha\(s\)$", m => $"Summary: {m.Groups[1].Value} applied, {m.Groups[2].Value} failed"),
        P(@"^(\d+) item\(ns\) revertido\(s\), (\d+) falha\(s\)$", m => $"{m.Groups[1].Value} item(s) restored, {m.Groups[2].Value} failed"),
        P(@"^Ultima acao executada: (.+)$", m => $"Last action: {T(m, 1)}"),
        P(@"^Realizada em: (.+)$", m => $"Run on: {m.Groups[1].Value}"),
        P(@"^Itens que serao verificados: (\d+)$", m => $"Items to check: {m.Groups[1].Value}"),
        P(@"^Registro restaurado: (.+)$", m => $"Registry restored: {m.Groups[1].Value}"),
        P(@"^Servico restaurado: (.+)$", m => $"Service restored: {m.Groups[1].Value}"),
        P(@"^Plano de energia restaurado$", _ => "Power plan restored"),
        P(@"^Tarefa reativada: (.+)$", m => $"Task re-enabled: {m.Groups[1].Value}"),
        P(@"^OneDrive: reinstalacao iniciada$", _ => "OneDrive: reinstall started"),
        P(@"^Falha ao reverter: (.*)$", m => $"Failed to restore: {m.Groups[1].Value}"),
        P(@"^Item de backup nao reconhecido ou fora da lista permitida: (.*)$", m => $"Unrecognized backup item or outside the allowlist: {m.Groups[1].Value}"),
        P(@"^Arquivo de backup de origem desconhecida isolado: (.+)$", m => $"Backup file of unknown origin quarantined: {m.Groups[1].Value}"),
        P(@"^Backup anterior ilegivel; arquivado em (.+)$", m => $"Previous backup unreadable; archived at {m.Groups[1].Value}"),
        P(@"^Plano Qrz: (\d+) valor\(es\) nao existem neste PC e ficaram no padrao do Windows\.$", m => $"Qrz plan: {m.Groups[1].Value} value(s) don't exist on this PC and kept the Windows default."),
        P(@"^Comando retornou codigo (-?\d+)$", m => $"Command returned code {m.Groups[1].Value}"),
        P(@"^Comando terminou com codigo (-?\d+)\. Consulte a saida para detalhes\.$", m => $"Command ended with code {m.Groups[1].Value}. See the output for details."),
        P(@"^A execução terminou com falhas \(código (-?\d+)\)\. Consulte a atividade e a reversão para alterações parciais\.$", m => $"The run finished with failures (code {m.Groups[1].Value}). Check activity and restore for partial changes."),
        P(@"^Ignorada: (.+)$", m => $"Skipped: {T(m, 1)}"),
        P(@"^Pulado: (.+)$", m => $"Skipped: {T(m, 1)}"),
        P(@"^Não reversível$", _ => "Not reversible"),
        P(@"^([A-Z]:) ignorada \((.+)\) - o Windows ja agenda a otimizacao desta unidade\.$", m => $"{m.Groups[1].Value} skipped ({m.Groups[2].Value}) - Windows already schedules optimization for this drive."),
        P(@"^TRIM executado em ([A-Z]:)$", m => $"TRIM run on {m.Groups[1].Value}"),
        P(@"^Agendador multimidia \(MMCSS\): (\d+) valores padrao do Windows restaurados\.$", m => $"Multimedia scheduler (MMCSS): {m.Groups[1].Value} Windows default values restored."),
        P(@"^(.+) de arquivos temporarios acumulados$", m => $"{m.Groups[1].Value} of accumulated temporary files"),
        P(@"^(\d+) programas iniciando junto com o Windows$", m => $"{m.Groups[1].Value} programs starting with Windows"),
        P(@"^Plano de energia atual: (.+)$", m => $"Current power plan: {m.Groups[1].Value}"),
        P(@"^Use a Limpeza rapida para liberar (.+)$", m => $"Use Quick cleanup to free {m.Groups[1].Value}"),
        P(@"^Servico Windows Update: (.+) \(StartType: (.+)\)$", m => $"Windows Update service: {m.Groups[1].Value} (StartType: {m.Groups[2].Value})"),
        P(@"^Ultima inicializacao: (.+) s$", m => $"Last boot: {m.Groups[1].Value} s"),
        P(@"^Espaco usado: (\d+)%$", m => $"Used space: {m.Groups[1].Value}%"),
        P(@"^(SSD|HDD) - (\d+)% livre de (.+)$", m => $"{m.Groups[1].Value} - {m.Groups[2].Value}% free of {m.Groups[3].Value}"),
        P(@"^Data anterior : (.+)$", m => $"Previous date : {m.Groups[1].Value}"),
        P(@"^RAM em uso    : (.+)$", m => $"RAM in use    : {m.Groups[1].Value}"),
        P(@"^Disco usado   : (.+)$", m => $"Disk used     : {m.Groups[1].Value}"),
        P(@"^Leitura disco : (.+)$", m => $"Disk read     : {m.Groups[1].Value}"),
        P(@"^Escrita disco : (.+)$", m => $"Disk write    : {m.Groups[1].Value}"),
        P(@"^Boot          : (.+)$", m => $"Boot          : {m.Groups[1].Value}"),
        P(@"^Servico (.+) nao existe neste Windows; nada a fazer\.$", m => $"Service {m.Groups[1].Value} doesn't exist on this Windows; nothing to do."),
        P(@"^Tarefa (.+) nao existe neste Windows; nada a fazer\.$", m => $"Task {m.Groups[1].Value} doesn't exist on this Windows; nothing to do."),
        P(@"^O desinstalador do OneDrive retornou codigo (-?\d+)$", m => $"The OneDrive uninstaller returned code {m.Groups[1].Value}"),
        P(@"^(CPU|RAM) em uso agora: (\d+)%$", m => $"{m.Groups[1].Value} in use now: {m.Groups[2].Value}%"),
        P(@"^(.+): modo MSI ja ativo\.$", m => $"{m.Groups[1].Value}: MSI mode already on."),
        P(@"^(.+): modo MSI ativado \(vale apos reiniciar\)\.$", m => $"{m.Groups[1].Value}: MSI mode enabled (takes effect after restart)."),
        P(@"^Latencia DPC/interrupcoes alta \((.+)% da CPU\)$", m => $"High DPC/interrupt latency ({m.Groups[1].Value}% of CPU)"),
        P(@"^Temperatura alta: (\d+) C - verifique cooling e pasta termica$", m => $"High temperature: {m.Groups[1].Value} C - check cooling and thermal paste"),
        P(@"^Memoria rodando a (\d+) MT/s, mas o kit suporta (\d+) MT/s \(XMP/EXPO desligado na BIOS\)$", m => $"Memory running at {m.Groups[1].Value} MT/s, but the kit supports {m.Groups[2].Value} MT/s (XMP/EXPO off in the BIOS)"),
        P(@"^BIOS com (.+) anos - pode haver versao mais nova no site da placa-mae$", m => $"BIOS is {m.Groups[1].Value} years old - a newer version may be on the motherboard's website"),
        P(@"^DPC: (.+)% da CPU$", m => $"DPC: {m.Groups[1].Value}% of CPU"),
        P(@"^Interrupcoes: (.+)% da CPU \((.+)/s\)$", m => $"Interrupts: {m.Groups[1].Value}% of CPU ({m.Groups[2].Value}/s)"),
        P(@"^Temperatura: (\d+) C \(sensor ACPI\)$", m => $"Temperature: {m.Groups[1].Value} C (ACPI sensor)"),
        P(@"^Latencia DPC  : (.+)$", m => $"DPC latency   : {m.Groups[1].Value}"),
        P(@"^Interrupcoes  : (.+)$", m => $"Interrupts    : {m.Groups[1].Value}"),
        P(@"^Temperatura   : (.+)$", m => $"Temperature   : {m.Groups[1].Value}"),
        P(@"^(Latencia DPC|Modo MSI|Placa-mae|Nucleos|Memoria|Temperatura)(\s+)(.+)$", m => $"{Tr(m.Groups[1].Value)}{m.Groups[2].Value}{m.Groups[3].Value.Replace(" nucleos / ", " cores / ").Replace("pente(s)", "stick(s)").Replace("Interrupcoes", "Interrupts").Replace(": desativado", ": off").Replace(": ativo", ": on").Replace("(sensor ACPI)", "(ACPI sensor)")}"),
        P(@"^(CPU|RAM|DISCO|INICIALIZACAO|WINDOWS|Disco|GPU)(\s+)(.+)$", m => $"{Tr(m.Groups[1].Value)}{m.Groups[2].Value}{m.Groups[3].Value}"),
    };
}
