using System.Text.RegularExpressions;

namespace PQueirozOptimizer.Services;

/// <summary>Traduções das páginas novas (Recursos, Correções, Restauração, Serviços, Apps), do tutorial e da Aparência.</summary>
public static partial class Translator
{
    private static readonly Dictionary<string, string> ParagonExact = new(StringComparer.Ordinal)
    {
        // ---------- Navegação e cabeçalhos ----------
        ["MANUTENÇÃO"] = "MAINTENANCE", ["Recursos"] = "Resources", ["Correções"] = "Fixes", ["Pontos de restauração"] = "Restore points",
        ["Serviços"] = "Services", ["Apps"] = "Apps",
        ["Crie e restaure pontos de restauração para proteger o sistema."] = "Create and restore restore points to protect your system.",
        ["Automação, atalhos, downloads e testes para preparar qualquer PC."] = "Automation, shortcuts, downloads and tests to prepare any PC.",
        ["Correções rápidas para problemas comuns do Windows."] = "Quick fixes for common Windows problems.",
        ["Desligue serviços e tarefas em segundo plano para liberar o sistema."] = "Turn off background services and tasks to free up the system.",
        ["Ajuste Discord, navegadores e outros apps e remova o que não usa."] = "Tune Discord, browsers and other apps and remove what you don't use.",

        // ---------- Tutorial ----------
        ["Bem-vindo ao PQueiroz Optimizer!"] = "Welcome to PQueiroz Optimizer!",
        ["Em menos de um minuto você conhece o essencial. Use Próximo para avançar ou Pular para começar a usar agora."] = "In less than a minute you'll know the essentials. Use Next to continue or Skip to start right away.",
        ["A saúde do PC, o monitor ao vivo e os atalhos para limpar e otimizar ficam aqui."] = "Your PC's health, the live monitor and shortcuts to clean and optimize are here.",
        ["Recursos — comece por aqui"] = "Resources — start here",
        ["Verificação de arquivos corrompidos do Windows, instalação de runtimes para jogos e reinstalação limpa do driver de vídeo."] = "Windows corrupted file check, game runtime installation and clean graphics driver reinstall.",
        ["Soluções rápidas para problemas comuns: Windows Update travado, Loja, áudio, pesquisa, ícones e mais."] = "Quick solutions for common problems: stuck Windows Update, Store, audio, search, icons and more.",
        ["Crie um ponto de restauração antes de grandes mudanças e volte a ele quando quiser."] = "Create a restore point before big changes and go back to it whenever you want.",
        ["Os ajustes de desempenho, privacidade e manutenção. Você revisa cada item antes de aplicar, e o que tem backup pode ser revertido."] = "Performance, privacy and maintenance tweaks. You review each item before applying, and anything with a backup can be undone.",
        ["Desligue grupos de serviços em segundo plano — Windows Update, telemetria, Bluetooth, Xbox — e ligue de volta quando quiser."] = "Turn off groups of background services — Windows Update, telemetry, Bluetooth, Xbox — and turn them back on whenever you want.",
        ["Ajuste Discord, navegadores e Spotify para não disputarem a placa de vídeo com o jogo, e desinstale o que não usa."] = "Tune Discord, browsers and Spotify so they don't compete with your game for the graphics card, and uninstall what you don't use.",
        ["Sessão de jogo temporária, perfis por jogo, presets dos jogos, perfil NVIDIA, plano de energia Qrz e Defender."] = "Temporary game session, per-game profiles, game presets, NVIDIA profile, Qrz power plan and Defender.",
        ["Ajustes de BIOS por grupos (memória, Resizable BAR, energia) aplicados pelo Windows, com cópia original para voltar."] = "BIOS tweaks by group (memory, Resizable BAR, power) applied from Windows, with an original copy to go back to.",
        ["Busca rápida"] = "Quick search", ["Pressione Ctrl+K e digite o que procura para abrir qualquer página ou recurso."] = "Press Ctrl+K and type what you're looking for to open any page or feature.",
        ["CPU, placa de vídeo, memória e ping em tempo real, em qualquer página."] = "CPU, graphics card, memory and ping in real time, on any page.",
        ["Tudo o que foi feito fica registrado aqui, com a opção de desfazer."] = "Everything that was done is recorded here, with the option to undo it.",
        ["Tudo pronto!"] = "All set!", ["Você pode rever os tutoriais quando quiser em Configurações → Tutoriais. Bom jogo!"] = "You can replay the tutorials anytime in Settings → Tutorials. Have a good game!",
        ["Verificação do sistema"] = "System check",
        ["Comece aqui! A verificação de corrupção encontra e repara arquivos danificados do Windows (ChkDsk, SFC e DISM)."] = "Start here! The corruption check finds and repairs damaged Windows files (ChkDsk, SFC and DISM).",
        ["Depois, instale o DirectX, o Visual C++ e o .NET que os jogos exigem."] = "Next, install the DirectX, Visual C++ and .NET that games require.",
        ["Atualizar o driver de vídeo"] = "Update the graphics driver", ["Por fim, reinstale o driver de vídeo do zero com o DDU."] = "Finally, reinstall the graphics driver from scratch with DDU.",
        ["Abas do Modo Jogo"] = "Game Mode tabs",
        ["Modo Jogo para a sessão temporária, Jogos para presets e perfis, NVIDIA para o driver e Sistema para energia e Defender."] = "Game Mode for the temporary session, Games for presets and profiles, NVIDIA for the driver and System for power and Defender.",
        ["Ativar o Modo Jogo"] = "Turn on Game Mode",
        ["Escolha o que fechar e pausar e clique aqui antes de jogar. Desative quando terminar: tudo volta como estava."] = "Choose what to close and pause and click here before playing. Turn it off when you're done: everything goes back as it was.",
        ["Mede download, upload, ping, jitter e perda de pacotes. Rode antes e depois dos ajustes para comparar."] = "Measures download, upload, ping, jitter and packet loss. Run it before and after tweaks to compare.",
        ["Meça e troque o servidor DNS por um mais rápido em um clique."] = "Measure and switch to a faster DNS server in one click.",
        ["Reparos"] = "Repairs", ["Se a internet der problema, limpe o DNS, sincronize o relógio ou redefina a rede."] = "If the internet acts up, clear DNS, sync the clock or reset the network.",
        ["Grupos de serviços"] = "Service groups",
        ["Cada grupo desliga um conjunto de serviços. O estado original é guardado: desmarque para voltar ao que era."] = "Each group turns off a set of services. The original state is saved: uncheck to go back to how it was.",
        ["Grupos de BIOS"] = "BIOS groups", ["Escolha quais grupos o app vai modificar. Cada grupo mostra o valor atual e o novo antes de gravar."] = "Choose which groups the app will modify. Each group shows the current and new value before writing.",
        ["Próximo"] = "Next", ["Concluir"] = "Finish", ["Voltar"] = "Back", ["Pular tutorial"] = "Skip tutorial",
        ["Tutorial concluído"] = "Tutorial complete", ["Reveja quando quiser em Configurações → Tutoriais."] = "Replay it anytime in Settings → Tutorials.",
        ["Tutoriais"] = "Tutorials", ["Rever tutoriais"] = "Replay tutorials", ["Guia"] = "Guide",
        ["Mostra de novo o tour da primeira abertura e libera os tutoriais curtos de cada página (Recursos, Modo Jogo, Rede, Serviços e BIOS)."] = "Shows the first-launch tour again and re-enables each page's short tutorial (Resources, Game Mode, Network, Services and BIOS).",

        // ---------- Pontos de restauração ----------
        ["Criar ponto de restauração"] = "Create restore point", ["Um retrato das configurações do Windows para voltar caso algo dê errado."] = "A snapshot of Windows settings to go back to if something goes wrong.",
        ["Nome"] = "Name", ["Ex.: Antes de otimizar"] = "E.g.: Before optimizing", ["Descrição (opcional)"] = "Description (optional)", ["O que você vai mudar"] = "What you're going to change",
        ["Etiquetas (separadas por vírgula)"] = "Tags (comma separated)", ["Ex.: drivers, jogos"] = "E.g.: drivers, games", ["Cor:"] = "Color:",
        ["Criar ponto"] = "Create point", ["Ponto de restauração"] = "Restore point", ["Dê um nome antes de criar."] = "Add a name before creating.",
        ["Criando ponto de restauração"] = "Creating restore point",
        ["Por que criar um ponto de restauração?"] = "Why create a restore point?",
        ["Desfazer qualquer mudança no sistema, inclusive as feitas pelo app, a qualquer momento."] = "Undo any system change, including the app's, at any time.",
        ["Proteger as configurações caso a energia caia no meio de uma alteração."] = "Protect your settings if the power goes out in the middle of a change.",
        ["Testar drivers e ajustes novos sabendo que dá para voltar ao estado anterior."] = "Try new drivers and tweaks knowing you can go back to the previous state.",
        ["Catálogo"] = "Catalog", ["Pontos de restauração existentes neste PC, do mais recente ao mais antigo."] = "Restore points on this PC, newest first.",
        ["Lendo os pontos de restauração..."] = "Reading restore points...", ["Nenhum ponto de restauração ainda"] = "No restore points yet",
        ["Crie o primeiro acima. A proteção do sistema é ativada automaticamente no disco do Windows."] = "Create the first one above. System protection is turned on automatically on the Windows drive.",
        ["Restaurar sistema"] = "Restore system", ["Restaurando o sistema"] = "Restoring the system",

        // ---------- Recursos ----------
        ["Automação"] = "Automation", ["Atalhos"] = "Shortcuts", ["Downloads"] = "Downloads", ["Benchmark"] = "Benchmark",
        ["Manutenção sem esforço"] = "Hands-free maintenance", ["Siga a ordem: verifique o sistema, instale os runtimes e reinstale o driver de vídeo."] = "Follow the order: check the system, install runtimes and reinstall the graphics driver.",
        ["Passo 1"] = "Step 1", ["Passo 2"] = "Step 2", ["Passo 3"] = "Step 3",
        ["Verificação de corrupção"] = "Corruption check", ["Verifique e repare os arquivos do Windows"] = "Scan and repair Windows files",
        ["Roda ChkDsk, SFC e DISM para encontrar e reparar arquivos corrompidos do Windows, e uma verificação final do SFC."] = "Runs ChkDsk, SFC and DISM to find and repair corrupted Windows files, plus a final SFC check.",
        ["Verificação do disco (ChkDsk)"] = "Disk check (ChkDsk)", ["Arquivos do sistema (SFC)"] = "System files (SFC)", ["Imagem do Windows (DISM)"] = "Windows image (DISM)",
        ["Iniciar verificação"] = "Start check",
        ["A verificação completa pode levar 30 minutos ou mais. Você pode continuar usando o PC, mas evite jogos pesados enquanto ela roda. Iniciar?"] = "The full check can take 30 minutes or more. You can keep using the PC, but avoid heavy games while it runs. Start?",
        ["Verificação de corrupção do sistema"] = "System corruption check", ["ChkDsk, SFC, DISM e uma verificação final do SFC. Pode levar mais de 30 minutos."] = "ChkDsk, SFC, DISM and a final SFC check. It can take over 30 minutes.",
        ["Runtimes e DirectX"] = "Runtimes and DirectX", ["Tudo o que jogos e apps precisam"] = "Everything games and apps need",
        ["Baixa e instala o Visual C++, o DirectX e o .NET Desktop Runtime pelo winget. Corrige erros de DLL faltando."] = "Downloads and installs Visual C++, DirectX and the .NET Desktop Runtime via winget. Fixes missing DLL errors.",
        ["Visual C++ 2010–2022"] = "Visual C++ 2010–2022", ["DirectX (runtime)"] = "DirectX (runtime)", ["Instalar runtimes"] = "Install runtimes",
        ["Reinstalação limpa do driver"] = "Clean driver reinstall", ["Driver de vídeo do zero, com DDU"] = "Graphics driver from scratch, with DDU",
        ["Remove o driver de vídeo atual com o DDU, reinicia e abre o instalador do driver novo assim que você entrar no Windows."] = "Removes the current graphics driver with DDU, restarts and opens the new driver's installer as soon as you sign in to Windows.",
        ["Remoção completa com DDU"] = "Complete removal with DDU", ["Ponto de restauração antes"] = "Restore point first", ["Instalador abre sozinho"] = "Installer opens by itself",
        ["Abrir instalação limpa"] = "Open clean install",
        ["Depois de reinstalar o driver, os jogos recompilam os shaders: as primeiras partidas podem travar um pouco até o cache ser refeito."] = "After reinstalling the driver, games recompile shaders: the first matches may stutter a little until the cache is rebuilt.",
        ["Essenciais para preparar qualquer PC"] = "Essentials to prepare any PC",
        ["Atalhos de um clique para as configurações e ferramentas do Windows que mais importam para desempenho."] = "One-click shortcuts to the Windows settings and tools that matter most for performance.",
        ["Antes de qualquer mudança grande"] = "Before any big change", ["Arquivos temporários e caches"] = "Temporary files and caches",
        ["Modo de Jogo do Windows"] = "Windows Game Mode", ["Configurações → Jogos"] = "Settings → Gaming",
        ["Gráficos (GPU por app)"] = "Graphics (GPU per app)", ["Configurações → Vídeo → Gráficos"] = "Settings → Display → Graphics",
        ["Taxa de atualização do monitor"] = "Monitor refresh rate", ["Configurações → Vídeo avançado"] = "Settings → Advanced display",
        ["Opções de energia"] = "Power options", ["Planos de energia do Windows"] = "Windows power plans",
        ["Opções de desempenho"] = "Performance options", ["Efeitos visuais e memória virtual"] = "Visual effects and virtual memory",
        ["Otimizar unidades"] = "Optimize drives", ["TRIM e desfragmentação"] = "TRIM and defragmentation",
        ["Limpeza de disco"] = "Disk Cleanup", ["Ferramenta do Windows"] = "Windows tool", ["Verificar atualizações"] = "Check for updates",
        ["Programas instalados"] = "Installed programs", ["Desinstalar programas"] = "Uninstall programs",
        ["Aplicativos de inicialização"] = "Startup apps", ["O que abre com o Windows"] = "What opens with Windows",
        ["Não foi possível abrir"] = "Could not open",
        ["Downloads recomendados"] = "Recommended downloads", ["Ferramentas gratuitas e confiáveis para drivers, monitoramento e manutenção. Todos os links levam ao site oficial."] = "Free, trusted tools for drivers, monitoring and maintenance. Every link goes to the official site.",
        ["Site oficial"] = "Official site", ["Diagnóstico"] = "Diagnostics", ["Monitoramento"] = "Monitoring", ["Sistema"] = "System", ["CPU"] = "CPU", ["GPU"] = "GPU",
        ["Remove completamente drivers de vídeo e áudio."] = "Completely removes graphics and audio drivers.",
        ["Instalador do driver NVIDIA sem telemetria e componentes extras."] = "NVIDIA driver installer without telemetry and extra components.",
        ["Configurações avançadas e ocultas do driver NVIDIA por jogo."] = "Advanced and hidden NVIDIA driver settings per game.",
        ["Mede a latência DPC e aponta drivers que causam travadas e estalos."] = "Measures DPC latency and points out drivers that cause stutters and audio pops.",
        ["Sensores de temperatura, clocks e voltagens de todo o hardware."] = "Temperature, clock and voltage sensors for all hardware.",
        ["Overclock da placa de vídeo e contador de FPS na tela (com o RTSS)."] = "Graphics card overclocking and on-screen FPS counter (with RTSS).",
        ["Detalhes do processador, da memória e da placa-mãe."] = "Processor, memory and motherboard details.",
        ["Saúde e temperatura de SSDs e HDs."] = "SSD and HDD health and temperature.", ["Velocidade de leitura e gravação do disco."] = "Disk read and write speed.",
        ["Gerenciador de tarefas avançado da Microsoft (Sysinternals)."] = "Microsoft's advanced task manager (Sysinternals).",
        ["Compactador de arquivos gratuito e leve."] = "Free, lightweight file archiver.", ["Cria pendrives de instalação do Windows."] = "Creates Windows installation USB drives.",
        ["Benchmark do PQueiroz Optimizer"] = "PQueiroz Optimizer benchmark", ["Integrado"] = "Built in", ["Rodar benchmark"] = "Run benchmark",
        ["Mede CPU, disco e tempo de inicialização para comparar antes e depois das otimizações. Os resultados ficam em Atividade e reversão."] = "Measures CPU, disk and boot time to compare before and after optimizing. Results go to Activity & restore.",
        ["Ferramentas de estresse e benchmark"] = "Stress and benchmark tools", ["Use para testar estabilidade depois de overclock ou para comparar com outros PCs."] = "Use them to test stability after overclocking or to compare with other PCs.",
        ["Teste de estresse da CPU e da memória: estabilidade e temperatura máxima."] = "CPU and memory stress test: stability and peak temperature.",
        ["Estresse de CPU, GPU, memória e fonte com detecção de erros."] = "CPU, GPU, memory and PSU stress with error detection.",
        ["Teste curto e pesado para validar overclock da CPU e da memória."] = "Short, heavy test to validate CPU and memory overclocks.",
        ["Benchmark de memória e cache, estresse e sensores."] = "Memory and cache benchmark, stress and sensors.",
        ["Pontuação de desempenho em um e em vários núcleos."] = "Single- and multi-core performance score.",
        ["Benchmark de placa de vídeo usado como referência mundial."] = "Graphics card benchmark used as a worldwide reference.",

        // ---------- Correções ----------
        ["Executar correção"] = "Run fix", ["Reinicia o PC"] = "Restarts the PC", ["Windows"] = "Windows", ["Explorer"] = "Explorer", ["Hardware"] = "Hardware", ["Rede"] = "Network", ["Jogos"] = "Games",
        ["Reparar o Windows Update"] = "Repair Windows Update",
        ["Para os serviços de atualização, renomeia as pastas de cache (SoftwareDistribution e catroot2) e inicia tudo de novo. Resolve atualizações travadas ou com erro."] = "Stops the update services, renames the cache folders (SoftwareDistribution and catroot2) and starts everything again. Fixes stuck or failing updates.",
        ["Parando serviços de atualização"] = "Stopping update services", ["Renomeando o cache de atualizações"] = "Renaming the update cache", ["Iniciando serviços de atualização"] = "Starting update services",
        ["Reparar a Microsoft Store"] = "Repair Microsoft Store", ["Limpa o cache da Loja e registra de novo o aplicativo. Resolve downloads parados e a Loja que não abre."] = "Clears the Store cache and re-registers the app. Fixes stalled downloads and a Store that won't open.",
        ["Limpando o cache da Loja"] = "Clearing the Store cache", ["Registrando a Loja novamente"] = "Re-registering the Store",
        ["Reconstruir cache de ícones e miniaturas"] = "Rebuild icon and thumbnail cache", ["Apaga os caches de ícones e miniaturas do Explorer e o reinicia. Resolve ícones em branco, trocados ou miniaturas erradas."] = "Deletes Explorer's icon and thumbnail caches and restarts it. Fixes blank, swapped icons or wrong thumbnails.",
        ["Fechando o Explorer"] = "Closing Explorer", ["Apagando os caches"] = "Deleting the caches", ["Abrindo o Explorer"] = "Opening Explorer",
        ["Reiniciar o Explorer"] = "Restart Explorer", ["Reinicia a barra de tarefas, o menu Iniciar e as janelas de pastas. Resolve barra de tarefas travada ou que não responde."] = "Restarts the taskbar, Start menu and folder windows. Fixes a frozen or unresponsive taskbar.",
        ["Reiniciando o Explorer"] = "Restarting Explorer",
        ["Reparar o áudio"] = "Repair audio", ["Reinicia os serviços de áudio do Windows. Resolve som que sumiu, chiado depois de suspender ou dispositivo que não aparece."] = "Restarts the Windows audio services. Fixes missing sound, crackling after sleep or a device that doesn't show up.",
        ["Reiniciando os serviços de áudio"] = "Restarting audio services",
        ["Reparar a pesquisa do Windows"] = "Repair Windows Search", ["Reinicia o serviço de pesquisa e reconstrói o índice. Resolve a pesquisa do menu Iniciar que não encontra arquivos ou programas."] = "Restarts the search service and rebuilds the index. Fixes Start menu search that can't find files or programs.",
        ["Parando a pesquisa"] = "Stopping search", ["Pedindo a reconstrução do índice"] = "Requesting an index rebuild", ["Iniciando a pesquisa"] = "Starting search",
        ["Limpar a fila de impressão"] = "Clear the print queue", ["Remove trabalhos de impressão travados. Resolve a impressora que não imprime nada."] = "Removes stuck print jobs. Fixes a printer that won't print anything.",
        ["Limpando a fila"] = "Clearing the queue",
        ["Sincronizar o relógio"] = "Sync the clock", ["Sincroniza a data e a hora com a internet. Resolve erros de certificado, de login em jogos e de anti-cheat."] = "Syncs date and time with the internet. Fixes certificate, game login and anti-cheat errors.",
        ["Sincronizando o relógio"] = "Syncing the clock",
        ["Limpar o cache de DNS"] = "Clear the DNS cache", ["Apaga os endereços guardados. Resolve sites e servidores de jogos que não abrem depois de mudarem de endereço."] = "Deletes stored addresses. Fixes sites and game servers that won't open after changing address.",
        ["Limpando o DNS"] = "Clearing DNS",
        ["Redefinir a rede"] = "Reset the network", ["Reinicia Winsock e TCP/IP e limpa o DNS. Use quando a internet não funcionar de jeito nenhum."] = "Resets Winsock and TCP/IP and clears DNS. Use it when the internet won't work at all.",
        ["Reiniciando o Winsock"] = "Resetting Winsock", ["Reiniciando o TCP/IP"] = "Resetting TCP/IP",
        ["Limpar caches de shaders"] = "Clear shader caches", ["Apaga os caches de shaders do DirectX, NVIDIA e AMD. Resolve travadas e falhas gráficas depois de atualizar driver ou jogo (os jogos recompilam os shaders)."] = "Deletes the DirectX, NVIDIA and AMD shader caches. Fixes stutters and graphical glitches after updating a driver or game (games recompile shaders).",
        ["Limpando o cache do DirectX"] = "Clearing the DirectX cache", ["Limpando o cache da NVIDIA"] = "Clearing the NVIDIA cache", ["Limpando o cache da AMD"] = "Clearing the AMD cache",
        ["Restaurar planos de energia padrão"] = "Restore default power plans", ["Recria os planos Equilibrado, Alto desempenho e Economia de energia do Windows. Resolve planos sumidos ou corrompidos."] = "Recreates the Windows Balanced, High performance and Power saver plans. Fixes missing or corrupted plans.",
        ["Restaurando os planos"] = "Restoring the plans",
        ["Limpar componentes antigos do Windows"] = "Clean up old Windows components", ["Remove versões antigas de atualizações guardadas no WinSxS. Libera espaço no disco do sistema (pode levar alguns minutos)."] = "Removes old update versions kept in WinSxS. Frees space on the system drive (may take a few minutes).",
        ["Limpando componentes"] = "Cleaning up components",

        // ---------- Serviços ----------
        ["Sistema e privacidade"] = "System & privacy", ["Rede e conexão"] = "Network & connectivity", ["Hardware e periféricos"] = "Hardware & peripherals", ["Recursos do Windows"] = "Windows features",
        ["Bloquear o Windows Update"] = "Block Windows Update", ["Para as atualizações automáticas e a Otimização de Entrega. Lembre de ligar de novo de vez em quando para receber correções de segurança."] = "Stops automatic updates and Delivery Optimization. Remember to turn it back on now and then to get security fixes.",
        ["Sem atualizações de segurança enquanto estiver desligado."] = "No security updates while it's off.",
        ["Bloquear a telemetria"] = "Block telemetry", ["Desliga a coleta e o envio de dados de diagnóstico e relatórios de erro para a Microsoft."] = "Turns off collecting and sending diagnostic data and error reports to Microsoft.",
        ["Desligar a descoberta na rede local"] = "Turn off local network discovery", ["Para o compartilhamento e a descoberta de dispositivos na rede (outros PCs, TVs e impressoras de rede deixam de aparecer)."] = "Stops sharing and device discovery on the network (other PCs, TVs and network printers stop showing up).",
        ["Desligar o acesso remoto"] = "Turn off remote access", ["Bloqueia a Área de Trabalho Remota, o registro remoto e o roteamento de VPN do Windows."] = "Blocks Remote Desktop, remote registry and Windows VPN routing.",
        ["A Área de Trabalho Remota deste PC para de funcionar."] = "Remote Desktop to this PC stops working.",
        ["Desligar a impressão"] = "Turn off printing", ["Para os serviços de impressora e digitalização. Só desligue se não usa impressora."] = "Stops printer and scanner services. Only turn it off if you don't use a printer.",
        ["Desligar o Bluetooth"] = "Turn off Bluetooth", ["Para o serviço de suporte ao Bluetooth. Fones, controles e mouses Bluetooth deixam de conectar."] = "Stops the Bluetooth support service. Bluetooth headsets, controllers and mice stop connecting.",
        ["Desligar o Hyper-V"] = "Turn off Hyper-V", ["Para os serviços de máquinas virtuais. WSL 2, Docker e o Sandbox do Windows precisam deles."] = "Stops virtual machine services. WSL 2, Docker and Windows Sandbox need them.",
        ["Desligar os serviços do Xbox"] = "Turn off Xbox services", ["Para a Xbox Live e o salvamento na nuvem de jogos do app Xbox. Controles continuam funcionando."] = "Stops Xbox Live and cloud saves for Xbox app games. Controllers keep working.",
        ["Jogos do Game Pass/Xbox app podem não abrir com eles desligados."] = "Game Pass/Xbox app games may not open with them off.",
        ["Em Modo Jogo"] = "In Game Mode", ["Exclusões de pastas de jogos e liga/desliga da proteção em tempo real ficam em Modo Jogo → Sistema."] = "Game folder exclusions and real-time protection on/off are in Game Mode → System.",

        // ---------- Apps ----------
        ["Otimizar apps"] = "Optimize apps", ["Desinstalar"] = "Uninstall", ["Otimizador de apps"] = "App optimizer",
        ["Apps que ficam abertos enquanto você joga também usam GPU e CPU. Cada ajuste é reversível: desmarque para voltar ao que era."] = "Apps left open while you play also use GPU and CPU. Every tweak is reversible: uncheck to go back to how it was.",
        ["Desligar a aceleração por hardware"] = "Turn off hardware acceleration", ["Não rodar em segundo plano"] = "Don't run in the background", ["Não rodar em segundo plano nem pré-carregar"] = "Don't run in the background or preload",
        ["O Discord deixa de usar a placa de vídeo para desenhar a janela, liberando a GPU para o jogo."] = "Discord stops using the graphics card to draw its window, freeing the GPU for the game.",
        ["O Spotify deixa de usar a placa de vídeo, que fica livre para o jogo."] = "Spotify stops using the graphics card, leaving it free for the game.",
        ["O Chrome fecha de verdade ao fechar a janela, em vez de continuar rodando escondido."] = "Chrome actually closes when you close the window, instead of running hidden.",
        ["Desliga o modo em segundo plano e a Inicialização Rápida, que deixa o Edge aberto desde o login."] = "Turns off background mode and Startup Boost, which keeps Edge open from sign-in.",
        ["O Brave fecha de verdade ao fechar a janela."] = "Brave actually closes when you close the window.",
        ["Não instalado"] = "Not installed", ["Padrão"] = "Default", ["Ajuste aplicado. Reabra o app para valer."] = "Tweak applied. Reopen the app for it to take effect.", ["Configuração original restaurada."] = "Original setting restored.",
        ["Debloat automático"] = "Auto debloat",
        ["Programas da área de trabalho abrem o desinstalador do fabricante; apps da Loja são removidos direto. O Debloat automático remove os apps que vêm com o Windows e quase ninguém usa."] = "Desktop programs open the maker's uninstaller; Store apps are removed directly. Auto debloat removes the apps that come with Windows and almost nobody uses.",
        ["Buscar programa…"] = "Search program…", ["Área de trabalho"] = "Desktop", ["Microsoft Store"] = "Microsoft Store",
        ["Lendo os programas instalados..."] = "Reading installed programs...", ["Nada encontrado"] = "Nothing found",
        ["Tente outro nome ou troque entre Área de trabalho e Microsoft Store."] = "Try another name or switch between Desktop and Microsoft Store.",

        // ---------- Win32 Priority ----------
        ["Win32 Priority"] = "Win32 Priority", ["Padrão do Windows"] = "Windows default", ["Comportamento original do Windows para computadores pessoais."] = "The original Windows behavior for personal computers.",
        ["Recomendado"] = "Recommended", ["Quantum curto e variável, com reforço triplo para o jogo em foco. Bom equilíbrio para jogar."] = "Short, variable quantum with a triple boost for the focused game. A good balance for gaming.",
        ["Resposta máxima"] = "Max responsiveness", ["Quantum curto e fixo com o maior reforço ao programa em foco. O mais agressivo."] = "Short, fixed quantum with the biggest boost for the focused program. The most aggressive.",
        ["Rápido e estável"] = "Fast and stable", ["Quantum curto e fixo, sem reforço extra. Tempo de resposta constante."] = "Short, fixed quantum with no extra boost. Consistent response time.",
        ["Adaptável com foco"] = "Adaptive with focus", ["Quantum longo e variável, com reforço triplo. Favorece o jogo sem cortar tarefas em segundo plano."] = "Long, variable quantum with a triple boost. Favors the game without starving background tasks.",
        ["Estável"] = "Stable", ["Quantum longo e fixo, sem reforço. O menos agressivo."] = "Long, fixed quantum with no boost. The least aggressive.",
        ["Win32 Priority restaurado ao valor original"] = "Win32 Priority restored to its original value",

        // ---------- Otimização completa ----------
        ["Otimização completa"] = "Full optimization", ["6 passos"] = "6 steps",
        ["Siga na ordem para revisar, aplicar e conferir as otimizações recomendadas."] = "Follow the order to review, apply and verify the recommended optimizations.",
        ["Limpeza"] = "Cleanup", ["Arquivos temporários seguros"] = "Safe temporary files", ["Driver de vídeo"] = "Graphics driver", ["Instalação limpa recomendada"] = "Clean install recommended",
        ["Ajustes recomendados"] = "Recommended tweaks", ["Revisados item por item"] = "Reviewed item by item", ["Segundo plano mais leve"] = "Lighter background",
        ["Presets dos jogos instalados"] = "Presets for installed games", ["BIOS"] = "BIOS", ["Grupos de ajustes da placa"] = "Board setting groups",

        // ---------- BIOS ----------
        ["PLACA-MÃE"] = "MOTHERBOARD", ["PROCESSADOR"] = "PROCESSOR", ["VERSÃO DA BIOS"] = "BIOS VERSION", ["Não identificado"] = "Not identified",
        ["Notebook detectado: os ajustes de BIOS são pensados para desktops. Em notebooks a fabricante costuma travar a BIOS, e mudanças de energia podem reduzir a bateria e aumentar a temperatura."] = "Laptop detected: BIOS tweaks are meant for desktops. Laptop makers usually lock the BIOS, and power changes can reduce battery life and raise temperatures.",
        ["Placa-mãe ASUS detectada"] = "ASUS motherboard detected", ["Placa-mãe ASRock detectada"] = "ASRock motherboard detected",
        ["Grupos de ajustes"] = "Setting groups", ["Escolha o que o app vai modificar. Grupos que não existem nesta BIOS aparecem desativados."] = "Choose what the app will modify. Groups that don't exist in this BIOS are disabled.",
        ["Indisponível"] = "Unavailable", ["Já aplicado"] = "Already applied", ["Vai modificar"] = "Will modify", ["Não vai modificar"] = "Won't modify",
        ["Marcar grupos selecionados"] = "Mark selected groups", ["Nada é gravado até você clicar em Gravar alterações."] = "Nothing is written until you click Write changes.",
        ["Os grupos escolhidos já estão aplicados."] = "The chosen groups are already applied.",
        ["Perfil de memória (XMP / EXPO / DOCP)"] = "Memory profile (XMP / EXPO / DOCP)", ["Faz a memória RAM rodar na velocidade anunciada pelo fabricante em vez do padrão lento. Costuma ser o maior ganho em jogos."] = "Makes RAM run at the speed advertised by the maker instead of the slow default. Usually the biggest gain in games.",
        ["Resizable BAR"] = "Resizable BAR", ["Permite à placa de vídeo acessar toda a VRAM de uma vez. Só é aplicado com o CSM desligado (senão o Windows pode não iniciar)."] = "Lets the graphics card access all of its VRAM at once. Only applied with CSM off (otherwise Windows may not boot).",
        ["Spread Spectrum desligado"] = "Spread Spectrum off", ["Mantém o clock de referência estável, sem a oscilação proposital usada para reduzir interferência."] = "Keeps the reference clock stable, without the intentional wobble used to reduce interference.",
        ["Precision Boost Overdrive (AMD)"] = "Precision Boost Overdrive (AMD)", ["Deixa processadores Ryzen subirem o clock por mais tempo quando a refrigeração permite. Aumenta temperatura e consumo."] = "Lets Ryzen processors boost longer when cooling allows. Raises temperature and power draw.",
        ["Estados de economia da CPU (C-States) desligados"] = "CPU power-saving states (C-States) off", ["O processador não entra em modos de economia profundos: resposta mais imediata, mais consumo e calor em repouso. Não use em notebook."] = "The processor doesn't enter deep power-saving modes: quicker response, more power and heat at idle. Don't use on laptops.",
        ["Virtualização desligada"] = "Virtualization off", ["Desliga SVM/VT-x. Pode reduzir latência em alguns sistemas, mas WSL 2, Hyper-V, Docker, emuladores e alguns anti-cheats precisam dela."] = "Turns off SVM/VT-x. May reduce latency on some systems, but WSL 2, Hyper-V, Docker, emulators and some anti-cheats need it.",
        ["Ativa o primeiro perfil de memória do fabricante."] = "Turns on the maker's first memory profile.", ["Ativa o PBO."] = "Turns on PBO.", ["Desliga os C-States profundos."] = "Turns off deep C-States.", ["Desliga a virtualização."] = "Turns off virtualization.",
        ["Não encontrado nesta BIOS."] = "Not found in this BIOS.",
        ["Clique em \"Reiniciar na BIOS/UEFI\" no topo desta página."] = "Click \"Restart to BIOS/UEFI\" at the top of this page.",
        ["Na BIOS, abra o modo avançado (F7) e vá até a aba Tool ou Advanced."] = "In the BIOS, open Advanced Mode (F7) and go to the Tool or Advanced tab.",
        ["Ative a opção \"Publish HII Resources\"."] = "Enable the \"Publish HII Resources\" option.",
        ["Em Advanced → UEFI Variables Protection, desative \"Password protection of Runtime Variables\"."] = "In Advanced → UEFI Variables Protection, disable \"Password protection of Runtime Variables\".",
        ["Salve (F10) e reinicie. Depois leia as configurações de novo por aqui."] = "Save (F10) and restart. Then read the settings again here.",
        ["Algumas placas ASRock só aceitam gravar pelo Windows com uma senha de supervisor definida."] = "Some ASRock boards only allow writing from Windows when a supervisor password is set.",
        ["Clique em \"Reiniciar na BIOS/UEFI\" e vá até a aba Security."] = "Click \"Restart to BIOS/UEFI\" and go to the Security tab.",
        ["Defina uma Supervisor Password e salve. Se o SCEWIN recusar a gravação, use essa senha ou remova-a depois de terminar."] = "Set a Supervisor Password and save. If SCEWIN refuses to write, use that password or remove it when you're done.",

        // ---------- Notas da versão 1.8.0 ----------
        ["Tutorial na primeira abertura: um tour guiado destaca cada área do app, e Recursos, Modo Jogo, Rede, Serviços e BIOS têm um tutorial curto na primeira visita. Reveja em Configurações → Tutoriais."] = "First-launch tutorial: a guided tour highlights each area of the app, and Resources, Game Mode, Network, Services and BIOS have a short tutorial on the first visit. Replay it in Settings → Tutorials.",
        ["Nova página Recursos: verificação de corrupção (ChkDsk, SFC e DISM), runtimes, reinstalação limpa do driver, atalhos do Windows, downloads recomendados e ferramentas de benchmark."] = "New Resources page: corruption check (ChkDsk, SFC and DISM), runtimes, clean driver reinstall, Windows shortcuts, recommended downloads and benchmark tools.",
        ["Nova página Correções: 13 reparos rápidos para Windows Update, Loja, ícones, Explorer, áudio, pesquisa, impressão, relógio, DNS, rede, shaders, planos de energia e WinSxS."] = "New Fixes page: 13 quick repairs for Windows Update, Store, icons, Explorer, audio, search, printing, clock, DNS, network, shaders, power plans and WinSxS.",
        ["Novas páginas Pontos de restauração (criar com nome, etiquetas e cor, e restaurar), Serviços (8 grupos com estado original guardado) e Apps (Discord, Spotify e navegadores sem disputar a GPU, e desinstalador)."] = "New pages: Restore points (create with name, tags and color, and restore), Services (8 groups with the original state saved) and Apps (Discord, Spotify and browsers without competing for the GPU, plus an uninstaller).",
        ["BIOS por grupos (memória XMP/EXPO, Resizable BAR, Spread Spectrum, PBO, C-States e virtualização), passo a passo para ASUS e ASRock e aviso em notebooks. Win32 Priority com 6 níveis no Modo Jogo."] = "BIOS by groups (XMP/EXPO memory, Resizable BAR, Spread Spectrum, PBO, C-States and virtualization), step-by-step for ASUS and ASRock and a laptop warning. Win32 Priority with 6 levels in Game Mode.",
        ["Interface redesenhada: Visão geral com cartão de saúde e ação principal, métricas com gráficos reais, menu organizado por categorias, última atividade na barra inferior e grades que se ajustam a telas menores."] = "Redesigned interface: Overview with a health card and primary action, metrics with real charts, menu organized by category, latest activity in the bottom bar and grids that adapt to smaller screens.",
        ["Aparência em Configurações: tema Escuro, OLED ou Automático, intensidade do roxo, densidade, tamanho dos cards, animações e pré-visualização ao vivo."] = "Appearance in Settings: Dark, OLED or Automatic theme, purple intensity, density, card size, animations and a live preview.",

        // ---------- Aparência ----------
        ["Aparência"] = "Appearance", ["Personalize o visual do PQueiroz Optimizer. Só muda a aparência: nenhuma função é alterada."] = "Customize how PQueiroz Optimizer looks. It only changes appearance: no feature is affected.",
        ["Tema"] = "Theme", ["Escuro"] = "Dark", ["OLED"] = "OLED", ["Automático"] = "Automatic",
        ["Automático segue o modo de aplicativo do Windows (claro ou escuro)."] = "Automatic follows the Windows app mode (light or dark).",
        ["Intensidade do roxo"] = "Purple intensity", ["Suave"] = "Soft", ["Vibrante"] = "Vibrant",
        ["Botões, seleção da barra lateral, gráficos, indicadores e brilhos."] = "Buttons, sidebar selection, charts, indicators and glows.",
        ["Densidade"] = "Density", ["Compacta"] = "Compact", ["Confortável"] = "Comfortable", ["Espaço entre os elementos e dentro dos cards."] = "Space between elements and inside cards.",
        ["Tamanho dos cards"] = "Card size", ["Compacto"] = "Compact", ["Médio"] = "Medium", ["Grande"] = "Large",
        ["Cards de monitoramento, hardware e das outras páginas."] = "Monitoring, hardware and other pages' cards.",
        ["Animações da interface"] = "Interface animations",
        ["Entrada das páginas, movimento dos cards, brilhos e fundo animado. O monitor ao vivo e os gráficos continuam atualizando."] = "Page entrances, card motion, glows and animated background. The live monitor and charts keep updating.",
        ["Pré-visualização"] = "Preview", ["Exemplo"] = "Example", ["MEMÓRIA"] = "MEMORY", ["SAÚDE"] = "HEALTH", ["Restaurar padrão"] = "Restore defaults",
        ["Padrão restaurado: Escuro, roxo Padrão, densidade Padrão, cards Médios e animações ligadas."] = "Defaults restored: Dark, Default purple, Default density, Medium cards and animations on.",
        ["Tema: Escuro (clique para OLED)"] = "Theme: Dark (click for OLED)", ["Tema: OLED (clique para Automático)"] = "Theme: OLED (click for Automatic)", ["Tema: Automático (clique para Escuro)"] = "Theme: Automatic (click for Dark)",

        // ---------- Visão geral ----------
        ["Sistema"] = "System", ["Tempo ligado"] = "Uptime", ["Sistema:"] = "System:", ["Tempo ligado:"] = "Uptime:",
        ["Mostra quanto espaço dá para liberar antes de apagar qualquer coisa"] = "Shows how much space can be freed before deleting anything",
        ["● Saudável"] = "● Healthy", ["▲ Atenção"] = "▲ Attention", ["▲ Crítico"] = "▲ Critical",
    };

    private static readonly (Regex Regex, Func<Match, string> Build)[] ParagonPatterns =
    {
        P(@"^(\d+) de (\d+) desligados$", m => $"{m.Groups[1].Value} of {m.Groups[2].Value} off"),
        P(@"^(\d+) correções$", m => $"{m.Groups[1].Value} fixes"),
        P(@"^(\d+)\. (.+)$", m => $"{m.Groups[1].Value}. {Tr(m.Groups[2].Value)}"),
        P(@"^(.+) — (Desligar a aceleração por hardware|Não rodar em segundo plano|Não rodar em segundo plano nem pré-carregar)$", m => $"{m.Groups[1].Value} — {Tr(m.Groups[2].Value)}"),
        P(@"^Serviços: (.+)$", m => $"Services: {m.Groups[1].Value.Replace("nenhum neste Windows", "none on this Windows")}"),
        P(@"^⚠ (.+)$", m => $"⚠ {Tr(m.Groups[1].Value)}"),
        P(@"^Quanto o Windows favorece o programa em foco \(o jogo\)\. Valor atual: (0x[0-9A-F]+)\. Vale na hora, sem reiniciar\.$", m => $"How much Windows favors the focused program (the game). Current value: {m.Groups[1].Value}. Takes effect right away, no restart."),
        P(@"^(.+) aplicado\.$", m => $"{Tr(m.Groups[1].Value)} applied."),
        P(@"^Win32 Priority: (.+) \((0x[0-9A-F]+)\)$", m => $"Win32 Priority: {Tr(m.Groups[1].Value)} ({m.Groups[2].Value})"),
        P(@"^(\d+)/(\d+) etapas concluídas\. Erro: (.*)$", m => $"{m.Groups[1].Value}/{m.Groups[2].Value} steps completed. Error: {m.Groups[3].Value}"),
        P(@"^Correção ""(.+)"": (\d+)/(\d+) etapas concluídas(.*)$", m => $"Fix \"{Tr(m.Groups[1].Value)}\": {m.Groups[2].Value}/{m.Groups[3].Value} steps completed{m.Groups[4].Value}"),
        P(@"^\[ERRO\] (.+?): (.+)$", m => $"[ERROR] {Tr(m.Groups[1].Value)}: {m.Groups[2].Value}"),
        P(@"^(.+)\.\.\.$", m => Exact.ContainsKey(m.Groups[1].Value) || ParagonExact.ContainsKey(m.Groups[1].Value) ? Tr(m.Groups[1].Value) + "..." : m.Value),
        P(@"^Serviços (desligados|restaurados): (.+) \((\d+)/(\d+)\)$", m => $"Services {(m.Groups[1].Value == "desligados" ? "turned off" : "restored")}: {Tr(m.Groups[2].Value)} ({m.Groups[3].Value}/{m.Groups[4].Value})"),
        P(@"^(Desligando|Restaurando): (.+)$", m => $"{(m.Groups[1].Value == "Desligando" ? "Turning off" : "Restoring")}: {Tr(m.Groups[2].Value)}"),
        P(@"^App otimizado: (.+) — (.+)$", m => $"App optimized: {m.Groups[1].Value} — {Tr(m.Groups[2].Value)}"),
        P(@"^Ajuste do app revertido: (.+) — (.+)$", m => $"App tweak reverted: {m.Groups[1].Value} — {Tr(m.Groups[2].Value)}"),
        P(@"^Feche o (.+) antes: ele regrava as configurações ao fechar\.$", m => $"Close {m.Groups[1].Value} first: it rewrites its settings when it closes."),
        P(@"^Desinstalar ""(.+)""\?$", m => $"Uninstall \"{m.Groups[1].Value}\"?"),
        P(@"^Desinstalando (.+)$", m => $"Uninstalling {m.Groups[1].Value}"),
        P(@"^Desinstalação iniciada: (.+)$", m => $"Uninstall started: {m.Groups[1].Value}"),
        P(@"^Mostrando 150 de (\d+)\. Use a busca para encontrar os outros\.$", m => $"Showing 150 of {m.Groups[1].Value}. Use search to find the others."),
        P(@"^Não foi possível (ler os pontos de restauração|listar os programas): (.+)$", m => $"Could not {(m.Groups[1].Value.StartsWith("ler") ? "read restore points" : "list programs")}: {m.Groups[2].Value}"),
        P(@"^Ponto de restauração criado: (.+)$", m => $"Restore point created: {m.Groups[1].Value}"),
        P(@"^Restaurando o sistema para o ponto (\d+); o PC vai reiniciar$", m => $"Restoring the system to point {m.Groups[1].Value}; the PC will restart"),
        P(@"^Restaurar o sistema para ""(.+)""\?\n\nO PC vai reiniciar agora para concluir\. Salve seus trabalhos antes\.$", m => $"Restore the system to \"{m.Groups[1].Value}\"?\n\nThe PC will restart now to finish. Save your work first."),
        P(@"^""(.+)"" precisa reiniciar o PC para terminar\. Executar agora\?$", m => $"\"{Tr(m.Groups[1].Value)}\" needs to restart the PC to finish. Run it now?"),
        P(@"^(\d+) configuração\(ões\) marcadas\. Revise em Alterados e grave\.$", m => $"{m.Groups[1].Value} setting(s) marked. Review them in Changed and write."),
        P(@"^Pontuação de saúde: (\d+) de 100$", m => $"Health score: {m.Groups[1].Value} of 100"),
    };
}
