namespace PQueirozOptimizer.Services;

/// <summary>Textos da v1.9.0: planos Base, Intermediário, Avançado e Vitalício e efeitos visuais em Personalizar Windows.</summary>
public static partial class Translator
{
    private static readonly Dictionary<string, string> PlansExact = new(StringComparer.Ordinal)
    {
        // ---------- Planos ----------
        ["Base"] = "Base",
        ["Intermediário"] = "Intermediate",
        ["Avançado"] = "Advanced",
        ["R$ 15/mês"] = "R$ 15/month",
        ["R$ 25/mês"] = "R$ 25/month",
        ["R$ 29,99/mês"] = "R$ 29.99/month",
        ["R$ 59,99 único"] = "R$ 59.99 one-time",
        ["Disponível a partir do plano {0}"] = "Available from the {0} plan",
        ["Quero o {0}"] = "Get {0}",
        ["Pedido de upgrade para o plano {0} copiado. No Discord, abra um ticket, cole o pedido e pague via Pix."] = "Upgrade request for the {0} plan copied. On Discord, open a ticket, paste the request and pay via Pix.",
        ["Seu plano atual é o {0}. Faça o upgrade para liberar esta página; o que você já aplicou continua funcionando e pode ser revertido em Atividade e reversão."] = "Your current plan is {0}. Upgrade to unlock this page; what you already applied keeps working and can be reverted in Activity and restore.",
        ["Recurso bloqueado"] = "Locked feature",
        ["Central de diagnóstico"] = "Diagnostics center",
        ["Otimização inteligente"] = "Smart optimization",
        ["Libera"] = "Includes",
        ["Já tenho a chave nova"] = "I already have the new key",
        ["Copia o pedido de upgrade e abre o Discord: abra um ticket, cole o pedido e pague via Pix"] = "Copies the upgrade request and opens Discord: open a ticket, paste the request and pay via Pix",
        ["O app completo, para sempre: pague uma vez, sem renovação."] = "The full app, forever: pay once, no renewals.",
        ["Otimizações, Inicialização, Correções, Ferramentas e Limpeza rápida."] = "Optimizations, Startup, Fixes, Tools and Quick clean.",
        ["Tudo do Base + Serviços, Apps, Drivers, Rede, Recursos e Central de diagnóstico."] = "Everything in Base + Services, Apps, Drivers, Network, Resources and Diagnostics center.",
        ["O app completo: tudo do Intermediário + Modo Jogo, Personalizar Windows, BIOS / UEFI e Modo de energia."] = "The full app: everything in Intermediate + Game Mode, Customize Windows, BIOS / UEFI and Power mode.",
        ["O Modo de energia está disponível a partir do plano Avançado. Em Configurações → Minha licença você pede o upgrade."] = "Power mode is available from the Advanced plan. Request the upgrade in Settings → My license.",

        // ---------- Efeitos visuais (Opções de desempenho) ----------
        ["Efeitos visuais"] = "Visual effects",
        ["As Opções de desempenho do Windows, direto aqui. \"Melhor desempenho\" desliga todas as animações e sombras; cada interruptor ajusta um efeito sozinho."] = "Windows Performance Options, right here. \"Best performance\" turns off every animation and shadow; each switch adjusts one effect on its own.",
        ["Melhor aparência"] = "Best appearance",
        ["Abrir no Windows"] = "Open in Windows",
        ["Aguarde a alteração em andamento terminar."] = "Wait for the current change to finish.",
        ["Ajustado para melhor desempenho."] = "Set for best performance.",
        ["Ajustado para melhor aparência."] = "Set for best appearance.",
        ["Animar controles e elementos dentro das janelas"] = "Animate controls and elements inside windows",
        ["Botões, barras e listas com transições animadas."] = "Buttons, bars and lists with animated transitions.",
        ["Animar janelas ao minimizar e maximizar"] = "Animate windows when minimizing and maximizing",
        ["A janela \"voa\" até a barra de tarefas em vez de sumir na hora."] = "The window \"flies\" to the taskbar instead of disappearing instantly.",
        ["Animações na barra de tarefas"] = "Animations in the taskbar",
        ["Ícones da barra deslizam e piscam ao abrir e fechar apps."] = "Taskbar icons slide and flash when apps open and close.",
        ["Ativar Espiar"] = "Enable Peek",
        ["Passar o mouse no canto da barra deixa as janelas transparentes para ver a área de trabalho."] = "Hovering the corner of the taskbar makes windows transparent so you can see the desktop.",
        ["Esmaecer ou deslizar menus"] = "Fade or slide menus into view",
        ["Menus aparecem com fade ou deslizando, em vez de abrir na hora."] = "Menus fade or slide in instead of opening instantly.",
        ["Esmaecer ou deslizar dicas de ferramenta"] = "Fade or slide ToolTips into view",
        ["As dicas ao passar o mouse aparecem com animação."] = "Hover tips appear with an animation.",
        ["Esmaecer itens de menu após clicar"] = "Fade out menu items after clicking",
        ["O item clicado some aos poucos depois que o menu fecha."] = "The clicked item fades out after the menu closes.",
        ["Salvar visualizações de miniaturas da barra de tarefas"] = "Save taskbar thumbnail previews",
        ["Guarda a prévia das janelas minimizadas na memória."] = "Keeps previews of minimized windows in memory.",
        ["Mostrar retângulo de seleção translúcido"] = "Show translucent selection rectangle",
        ["O retângulo ao selecionar arquivos com o mouse fica azul translúcido."] = "The rectangle drawn when selecting files with the mouse is translucent blue.",
        ["Mostrar conteúdo da janela ao arrastar"] = "Show window contents while dragging",
        ["A janela inteira acompanha o mouse ao ser arrastada, e não só o contorno."] = "The whole window follows the mouse while dragged, not just its outline.",
        ["Mostrar sombras sob janelas"] = "Show shadows under windows",
        ["Sombra suave em volta das janelas abertas."] = "Soft shadow around open windows.",
        ["Mostrar miniaturas em vez de ícones"] = "Show thumbnails instead of icons",
        ["O Explorador mostra a prévia de fotos e vídeos; desligado, só o ícone do tipo de arquivo."] = "File Explorer shows previews of photos and videos; when off, only the file type icon.",
        ["Mostrar sombras sob o ponteiro do mouse"] = "Show shadows under mouse pointer",
        ["Sombra embaixo da seta do mouse."] = "Shadow under the mouse arrow.",
        ["Usar sombras subjacentes para rótulos de ícones na área de trabalho"] = "Use drop shadows for icon labels on the desktop",
        ["Sombra atrás do nome dos ícones da área de trabalho."] = "Shadow behind the names of desktop icons.",
        ["Suavizar bordas das fontes de tela"] = "Smooth edges of screen fonts",
        ["Deixa o texto nítido (ClearType). Desligado, as letras ficam serrilhadas."] = "Keeps text crisp (ClearType). When off, letters look jagged.",
        ["Rolagem suave de caixas de listagem"] = "Smooth-scroll list boxes",
        ["Listas rolam com animação em vez de pular de linha em linha."] = "Lists scroll smoothly instead of jumping line by line.",
        ["Deslizar caixas de combinação ao abrir"] = "Slide open combo boxes",
        ["Listas suspensas abrem deslizando."] = "Drop-down lists slide open.",
    };
}
