using System.Text.RegularExpressions;

namespace PQueirozOptimizer.Services;

/// <summary>Traduções do HUD ao vivo e das páginas Modo Jogo e Rede.</summary>
public static partial class Translator
{
    private static readonly Dictionary<string, string> GamingExact = new(StringComparer.Ordinal)
    {
        ["Restauração pendente"] = "Recovery pending",
        ["Corrigida a validação dos planos de otimização em notebooks nos testes de publicação."] = "Fixed optimization plan validation on laptops in release tests.",
        ["Modo Jogo preserva os itens que não puderam ser restaurados e permite tentar novamente, sem informar sucesso indevido."] = "Game Mode keeps items that could not be restored and lets you retry without incorrectly reporting success.",
        ["Estado de recuperação salvo antes das alterações, com gravação atômica da sessão."] = "Recovery state is saved before changes, with atomic session writes.",
        ["Histórico com lista virtualizada, busca mais leve e atualização automática de novos registros."] = "History has a virtualized list, more responsive search and automatic updates for new entries.",
        ["Indicadores de restauração pendente, busca adaptável à largura e níveis de atividade destacados."] = "Pending recovery indicators, responsive search width and highlighted activity levels.",
        ["Tentar novamente"] = "Try again",
        ["Pendente"] = "Pending",
        ["Plano de energia a restaurar"] = "Power plan to restore",
        ["Alguns itens não foram restaurados. Tente novamente para concluir a restauração."] = "Some items could not be restored. Try again to complete recovery.",
        ["Restauração incompleta. As pendências foram salvas; tente novamente no Modo Jogo."] = "Recovery incomplete. Pending items were saved; try again in Game Mode.",
        // ---------- Navegação e HUD ----------
        ["JOGOS E REDE"] = "GAMING & NETWORK", ["Modo Jogo"] = "Game Mode", ["Rede"] = "Network", ["ATIVO"] = "ON",
        ["Monitor ao vivo"] = "Live monitor", ["Latência até 1.1.1.1"] = "Latency to 1.1.1.1",
        ["Monitor em tempo real"] = "Real-time monitor", ["● AO VIVO"] = "● LIVE",
        ["Uso de CPU, placa de vídeo, memória e rede no último minuto."] = "CPU, graphics card, memory and network usage over the last minute.",
        ["MEMÓRIA"] = "MEMORY", ["Processador"] = "Processor", ["Memória RAM"] = "RAM",
        ["Motor 3D da placa de vídeo"] = "Graphics card 3D engine", ["Uso da GPU indisponível neste PC"] = "GPU usage unavailable on this PC",

        // ---------- Modo Jogo ----------
        ["Modo Jogo ativo"] = "Game Mode on", ["Modo Jogo temporário"] = "Temporary Game Mode",
        ["Fecha programas em segundo plano, pausa serviços que disputam disco e internet e ativa o plano Alto desempenho enquanto você joga. Ao desativar, tudo volta como estava — mesmo que o PC reinicie no meio."] = "Closes background apps, pauses services that compete for disk and internet and switches to the High performance plan while you play. When you turn it off, everything goes back as it was — even if the PC restarts in between.",
        ["Programas para fechar"] = "Apps to close", ["Serviços para pausar durante a sessão"] = "Services to pause during the session",
        ["Aberto"] = "Open", ["Fechado"] = "Closed", ["Temporário"] = "Temporary", ["Pontual"] = "One-off", ["Ativo"] = "On",
        ["Sincronização de arquivos na nuvem"] = "Cloud file sync", ["Chat e reuniões"] = "Chat and meetings",
        ["Vincular ao Celular"] = "Phone Link", ["Notificações do celular no PC"] = "Phone notifications on the PC",
        ["Painel de notícias e clima"] = "News and weather panel", ["Microsoft Edge (em segundo plano)"] = "Microsoft Edge (background)",
        ["Feche só se não estiver usando o navegador"] = "Close only if you're not using the browser",
        ["Feche só se não estiver ouvindo música"] = "Close only if you're not listening to music",
        ["Sincronização e atualizações da Adobe"] = "Adobe sync and updates", ["Assistente da Microsoft"] = "Microsoft assistant",
        ["Evita downloads e instalações de atualizações no meio da partida."] = "Prevents update downloads and installs mid-match.",
        ["Transferência inteligente em segundo plano"] = "Background Intelligent Transfer",
        ["Usado pelo Windows Update e por outros downloads automáticos."] = "Used by Windows Update and other automatic downloads.",
        ["Otimização de Entrega"] = "Delivery Optimization", ["Compartilha atualizações com outros PCs pela internet."] = "Shares updates with other PCs over the internet.",
        ["Pré-carrega programas na memória e usa o disco em segundo plano."] = "Preloads apps into memory and uses the disk in the background.",
        ["Indexação de arquivos para a pesquisa."] = "File indexing for search.",
        ["Telemetria (DiagTrack)"] = "Telemetry (DiagTrack)", ["Envio de dados de diagnóstico para a Microsoft."] = "Sends diagnostic data to Microsoft.",
        ["Spooler de impressão"] = "Print spooler", ["Só pause se não for imprimir durante a sessão."] = "Only pause it if you won't print during the session.",
        ["Plano de energia Alto desempenho"] = "High performance power plan",
        ["O processador mantém a frequência alta durante o jogo. O plano anterior volta ao desativar."] = "The processor keeps its clock high while gaming. The previous plan comes back when you turn it off.",
        ["Desmarcado: no seu Ryzen X3D o plano Equilibrado é o que deixa o Windows usar o CCD com cache."] = "Unchecked: on your Ryzen X3D, the Balanced plan is what lets Windows use the cache CCD.",
        ["Liberar memória em espera ao iniciar"] = "Free standby memory on start",
        ["Esvazia o cache de arquivos que o Windows guarda na RAM. Ajuda em jogos com engasgos quando a memória está quase cheia."] = "Empties the file cache Windows keeps in RAM. Helps games that stutter when memory is almost full.",
        ["Ativar Modo Jogo"] = "Turn on Game Mode", ["Desativar Modo Jogo"] = "Turn off Game Mode",
        ["Ativando Modo Jogo"] = "Turning on Game Mode", ["Desativando Modo Jogo"] = "Turning off Game Mode",
        ["Nada é desinstalado nem desativado de forma permanente."] = "Nothing is uninstalled or permanently disabled.",
        ["Liberar memória em espera"] = "Free standby memory", ["Plano Alto desempenho"] = "High performance plan",
        ["Memória em espera liberada"] = "Standby memory freed", ["Não foi possível liberar a memória em espera"] = "Could not free standby memory",
        ["Memória em espera liberada. O Windows volta a usá-la como cache conforme você abre arquivos."] = "Standby memory freed. Windows will use it as cache again as you open files.",
        ["Não foi possível liberar a memória em espera (é preciso executar como administrador)."] = "Could not free standby memory (the app must run as administrator).",
        ["Plano de energia: Alto desempenho"] = "Power plan: High performance", ["Plano de energia anterior restaurado"] = "Previous power plan restored",
        ["Modo Jogo desativado: serviços e plano de energia restaurados"] = "Game Mode off: services and power plan restored",
        ["O Modo Jogo já está ativo. Desative-o antes de iniciar outra sessão."] = "Game Mode is already on. Turn it off before starting another session.",

        // ---------- Patch notes v1.8.0 ----------
        ["Nova página Modo Jogo: fecha programas em segundo plano, pausa serviços (Windows Update, indexação, telemetria) e ativa o plano de desempenho enquanto você joga; ao desativar, tudo volta como estava."] = "New Game Mode page: closes background apps, pauses services (Windows Update, indexing, telemetry) and switches to the performance plan while you play; turning it off puts everything back.",
        ["Plano de energia Qrz: plano de baixa latência instalado e ativado em um clique, com volta ao plano anterior."] = "Qrz power plan: a low-latency plan installed and activated in one click, with a way back to the previous plan.",
        ["Perfis de jogos: placa de vídeo dedicada, sem otimizações de tela cheia e prioridade de CPU alta sempre que o jogo abrir."] = "Game profiles: dedicated graphics card, no fullscreen optimizations and high CPU priority every time the game opens.",
        ["Liberar memória em espera, menos processos svchost e instalação de runtimes (Visual C++, DirectX, .NET, XNA) pelo winget."] = "Free standby memory, fewer svchost processes and runtime installs (Visual C++, DirectX, .NET, XNA) via winget.",
        ["Nova página Rede: teste de velocidade com ping, jitter e perda de pacotes, troca de DNS com medição, ajustes de latência reversíveis e reparos (DNS, relógio e reset)."] = "New Network page: speed test with ping, jitter and packet loss, DNS switching with benchmark, reversible latency tweaks and repairs (DNS, clock and reset).",
        ["Monitor ao vivo: CPU, GPU, RAM e ping na barra lateral e gráficos em tempo real na visão geral."] = "Live monitor: CPU, GPU, RAM and ping in the sidebar and real-time charts on the overview.",
        ["Ryzen X3D com dois CCDs: as otimizações mantêm a Game Bar e o plano Equilibrado, necessários para o jogo usar o 3D V-Cache, e o Modo Jogo mostra o que falta (driver de chipset, Game Bar, plano)."] = "Dual-CCD Ryzen X3D: optimizations keep Game Bar and the Balanced plan, which games need to use 3D V-Cache, and Game Mode shows what's missing (chipset driver, Game Bar, plan).",
        ["Visual: transição suave entre páginas, cartões com destaque ao passar o mouse e barra lateral mais compacta."] = "Visuals: smooth page transitions, cards that highlight on hover and a more compact sidebar.",

        // ---------- Plano de energia Qrz ----------
        ["Plano de energia Qrz"] = "Qrz power plan", ["Instalar"] = "Install", ["Ativar"] = "Activate", ["Restaurar"] = "Restore",
        ["Plano de energia: Qrz"] = "Power plan: Qrz", ["Ativando plano de energia Qrz"] = "Activating Qrz power plan", ["Restaurando plano de energia"] = "Restoring power plan",
        ["Plano de baixa latência: processador sempre em 100% e sem estacionamento de núcleos; PCIe, disco e Wi-Fi sem economia de energia. Restaurar volta ao plano anterior."] = "Low-latency plan: processor always at 100% with no core parking; PCIe, disk and Wi-Fi without power saving. Restore goes back to the previous plan.",
        ["Ativo. Plano de baixa latência: processador sempre em 100% e sem estacionamento de núcleos; PCIe, disco e Wi-Fi sem economia de energia."] = "On. Low-latency plan: processor always at 100% with no core parking; PCIe, disk and Wi-Fi without power saving.",
        ["O plano Qrz desliga o estacionamento de núcleos. Em Ryzen X3D com dois CCDs isso pode fazer o jogo rodar no CCD sem 3D V-Cache. Ativar mesmo assim?"] = "The Qrz plan turns off core parking. On dual-CCD Ryzen X3D this can make the game run on the CCD without 3D V-Cache. Activate anyway?",
        ["Plano de energia anterior restaurado e plano Qrz removido"] = "Previous power plan restored and Qrz plan removed",
        ["Configurações do plano Qrz não encontradas."] = "Qrz plan settings not found.",

        // ---------- X3D ----------
        ["Dois CCDs"] = "Two CCDs", ["Um CCD"] = "One CCD",
        ["Seu processador tem dois CCDs e só um tem o 3D V-Cache. Para o Windows mandar o jogo ao CCD certo, ele precisa do driver de chipset da AMD, da Game Bar ativa e do plano de energia Equilibrado."] = "Your processor has two CCDs and only one has 3D V-Cache. For Windows to send the game to the right CCD, it needs AMD's chipset driver, Game Bar enabled and the Balanced power plan.",
        ["Processador com 3D V-Cache em um único CCD. Mantenha o driver de chipset da AMD atualizado e ajuste a BIOS (EXPO e PBO) para tirar o máximo do cache."] = "Processor with 3D V-Cache on a single CCD. Keep AMD's chipset driver up to date and tune the BIOS (EXPO and PBO) to get the most out of the cache.",
        ["Driver AMD 3D V-Cache Performance Optimizer instalado"] = "AMD 3D V-Cache Performance Optimizer driver installed",
        ["Driver AMD 3D V-Cache não encontrado: instale o pacote de chipset da AMD"] = "AMD 3D V-Cache driver not found: install AMD's chipset package",
        ["Game Bar permitida (o Windows usa ela para reconhecer jogos)"] = "Game Bar allowed (Windows uses it to recognize games)",
        ["Game Bar bloqueada por política: o Windows não reconhece o jogo para usar o CCD com cache"] = "Game Bar blocked by policy: Windows can't recognize the game to use the cache CCD",
        ["Plano de energia Equilibrado ativo"] = "Balanced power plan active",
        ["Plano diferente do Equilibrado: a AMD recomenda o Equilibrado para estacionar o CCD sem cache"] = "Plan other than Balanced: AMD recommends Balanced to park the non-cache CCD",
        ["A Versão Avançada do otimizador já é compatível com o seu processador"] = "The optimizer's Advanced Version is already compatible with your processor",
        ["Driver de chipset AMD"] = "AMD chipset driver", ["Ajustes de BIOS"] = "BIOS settings", ["Liberar Game Bar"] = "Allow Game Bar",
        ["Game Bar liberada para o agendamento do Ryzen X3D"] = "Game Bar allowed for Ryzen X3D scheduling",

        // ---------- Perfis e ajustes rápidos ----------
        ["Perfis de jogos"] = "Game profiles",
        ["Ajustes que o Windows aplica sempre que o jogo abrir. Removíveis a qualquer momento."] = "Settings Windows applies every time the game opens. Removable at any time.",
        ["Usar a placa de vídeo dedicada"] = "Use the dedicated graphics card", ["Desativar otimizações de tela cheia"] = "Disable fullscreen optimizations",
        ["Prioridade de CPU alta"] = "High CPU priority", ["Adicionar jogo (.exe)"] = "Add game (.exe)", ["Remover perfil"] = "Remove profile",
        ["Escolha o executável do jogo"] = "Choose the game executable", ["Escolha o arquivo .exe do jogo."] = "Choose the game's .exe file.",
        ["Esse programa é do sistema e não pode receber um perfil de jogo."] = "That is a system program and can't get a game profile.",
        ["Marque pelo menos um ajuste para o perfil."] = "Check at least one setting for the profile.",
        ["GPU dedicada"] = "dedicated GPU", ["sem otimização de tela cheia"] = "no fullscreen optimization", ["prioridade alta"] = "high priority",
        ["GPU dedicada, sem otimização de tela cheia, prioridade alta"] = "dedicated GPU, no fullscreen optimization, high priority",
        ["GPU dedicada, prioridade alta"] = "dedicated GPU, high priority", ["GPU dedicada, sem otimização de tela cheia"] = "dedicated GPU, no fullscreen optimization",
        ["sem otimização de tela cheia, prioridade alta"] = "no fullscreen optimization, high priority",
        ["Ajustes rápidos"] = "Quick tweaks", ["Ações pontuais e ajustes reversíveis com um clique."] = "One-off actions and one-click reversible tweaks.",
        ["Memória em espera"] = "Standby memory", ["Liberar"] = "Free", ["Esvazia o cache de arquivos na RAM, como o ISLC."] = "Empties the file cache in RAM, like ISLC.",
        ["Menos processos svchost"] = "Fewer svchost processes", ["Aplicar"] = "Apply", ["Reverter"] = "Revert",
        ["Agrupa os serviços do Windows em menos processos. Vale após reiniciar."] = "Groups Windows services into fewer processes. Takes effect after restart.",
        ["Aplicado. Agrupa os serviços em menos processos (vale após reiniciar)."] = "Applied. Groups services into fewer processes (takes effect after restart).",
        ["Agrupamento de serviços alterado. Reinicie o PC para valer."] = "Service grouping changed. Restart the PC for it to take effect.",
        ["Agrupamento de serviços svchost aplicado (vale após reiniciar)"] = "svchost service grouping applied (takes effect after restart)",
        ["Agrupamento de serviços svchost revertido (vale após reiniciar)"] = "svchost service grouping reverted (takes effect after restart)",
        ["Versão Avançada (jogos)"] = "Advanced Version (gaming)",
        ["Os ajustes permanentes de latência e desempenho, revisados item por item."] = "The permanent latency and performance tweaks, reviewed item by item.",

        // ---------- Runtimes ----------
        ["Runtimes para jogos"] = "Game runtimes",
        ["Bibliotecas que muitos jogos exigem. Faltando uma delas, o jogo fecha ao abrir ou mostra erro de DLL (MSVCP140, d3dx9, XINPUT...)."] = "Libraries many games require. If one is missing, the game closes on launch or shows a DLL error (MSVCP140, d3dx9, XINPUT...).",
        ["Exigido pela maioria dos jogos atuais."] = "Required by most current games.", ["Jogos e launchers de 32 bits."] = "32-bit games and launchers.",
        ["Jogos de 2013 a 2016."] = "Games from 2013 to 2016.", ["Jogos mais antigos."] = "Older games.",
        ["DirectX (runtime de usuário final)"] = "DirectX (end-user runtime)", ["Bibliotecas do DirectX 9/10/11 usadas por jogos antigos."] = "DirectX 9/10/11 libraries used by older games.",
        ["Launchers e ferramentas feitas em .NET."] = "Launchers and tools built with .NET.",
        ["Jogos indie como Terraria e Stardew Valley (versões antigas)."] = "Indie games like Terraria and Stardew Valley (older versions).",
        ["Visual C++ 2015–2022 (64 bits)"] = "Visual C++ 2015–2022 (64-bit)", ["Visual C++ 2015–2022 (32 bits)"] = "Visual C++ 2015–2022 (32-bit)",
        ["Visual C++ 2013 (64 bits)"] = "Visual C++ 2013 (64-bit)", ["Visual C++ 2013 (32 bits)"] = "Visual C++ 2013 (32-bit)",
        ["Visual C++ 2012 (64 bits)"] = "Visual C++ 2012 (64-bit)", ["Visual C++ 2010 (64 bits)"] = "Visual C++ 2010 (64-bit)",
        ["Instalar selecionados"] = "Install selected", ["Instalando runtimes"] = "Installing runtimes",
        ["Já instalados são ignorados. Pode levar alguns minutos."] = "Already installed ones are skipped. It may take a few minutes.",
        ["Selecione pelo menos um runtime."] = "Select at least one runtime.", ["Runtimes"] = "Runtimes",
        ["O winget (Instalador de Aplicativos) não foi encontrado. Instale o \"Instalador de Aplicativos\" pela Microsoft Store e tente de novo."] = "winget (App Installer) was not found. Install \"App Installer\" from the Microsoft Store and try again.",

        // ---------- Rede ----------
        ["Teste de velocidade"] = "Speed test", ["Último resultado"] = "Last result",
        ["Quão rápida e estável é a sua conexão?"] = "How fast and stable is your connection?",
        ["Mede download, upload, ping, jitter e perda de pacotes nos servidores da Cloudflare. Leva cerca de 25 segundos."] = "Measures download, upload, ping, jitter and packet loss on Cloudflare's servers. Takes about 25 seconds.",
        ["Iniciar teste"] = "Start test", ["Testar de novo"] = "Test again", ["PERDA"] = "LOSS", ["MÍN / MÁX"] = "MIN / MAX",
        ["Medindo latência..."] = "Measuring latency...", ["Medindo download..."] = "Measuring download...", ["Medindo upload..."] = "Measuring upload...",
        ["Sem resposta do servidor de teste. Verifique a conexão."] = "No response from the test server. Check your connection.",
        ["Conexão instável: há perda de pacotes"] = "Unstable connection: packets are being lost", ["Ping oscilando bastante (jitter alto)"] = "Ping fluctuating a lot (high jitter)",
        ["Ping alto para jogos online"] = "High ping for online games", ["Conexão ótima para jogar e transmitir"] = "Great connection for gaming and streaming",
        ["Conexão boa para jogar"] = "Good connection for gaming",
        ["Servidor DNS"] = "DNS server", ["Medir DNS"] = "Measure DNS", ["Medindo servidores DNS"] = "Measuring DNS servers",
        ["Traduz nomes de sites e servidores de jogos. Um DNS rápido acelera conexões e o login nos jogos."] = "Translates site and game server names. A fast DNS speeds up connections and game logins.",
        ["Usar"] = "Use", ["Em uso"] = "In use", ["sem resposta"] = "no response", ["Sem conexão"] = "No connection",
        ["Automático (provedor)"] = "Automatic (ISP)", ["Volta ao DNS entregue pelo roteador."] = "Goes back to the DNS provided by the router.",
        ["Rápido e com foco em privacidade."] = "Fast and privacy-focused.", ["Estável e disponível no mundo todo."] = "Stable and available worldwide.",
        ["Bloqueia domínios maliciosos conhecidos."] = "Blocks known malicious domains.",
        ["Nenhum adaptador de rede conectado."] = "No network adapter connected.",
        ["Latência de rede para jogos"] = "Network latency for gaming", ["Aplicar ajustes"] = "Apply tweaks", ["Aplicado"] = "Applied",
        ["Desliga o algoritmo de Nagle e o ACK atrasado nos adaptadores conectados: pacotes pequenos saem na hora, sem esperar para serem agrupados. Não altera a velocidade da internet."] = "Turns off Nagle's algorithm and delayed ACK on connected adapters: small packets go out right away instead of waiting to be grouped. It doesn't change your internet speed.",
        ["Ajustes de latência revertidos."] = "Latency tweaks reverted.",
        ["Ajustes de latência aplicados. Reconecte a rede ou reinicie para valer em todos os programas."] = "Latency tweaks applied. Reconnect the network or restart for them to apply to every program.",
        ["Ajustes de latência de rede"] = "Network latency tweaks", ["Ajustes de latência de rede revertidos"] = "Network latency tweaks reverted",
        ["Ajustes de latência de rede aplicados (Nagle e ACK atrasado desligados)"] = "Network latency tweaks applied (Nagle and delayed ACK off)",
        ["Conexões ativas"] = "Active connections", ["Nenhuma conexão com a internet encontrada."] = "No internet connection found.",
        ["Cabo (Ethernet)"] = "Cable (Ethernet)", ["Wi-Fi"] = "Wi-Fi",
        ["Dica: para jogar, o cabo de rede tem ping mais baixo e estável que o Wi-Fi."] = "Tip: for gaming, a network cable has lower and steadier ping than Wi-Fi.",
        ["Reparos de rede"] = "Network repairs", ["Resolvem a maioria dos problemas de conexão, DNS e login em jogos."] = "Fix most connection, DNS and game login problems.",
        ["Limpar cache DNS"] = "Clear DNS cache", ["Limpando cache DNS"] = "Clearing DNS cache", ["Limpar"] = "Clear", ["Cache DNS limpo"] = "DNS cache cleared",
        ["Resolve sites e servidores que não abrem depois de mudarem de endereço."] = "Fixes sites and servers that won't open after changing address.",
        ["Sincronizar relógio"] = "Sync clock", ["Sincronizar"] = "Sync", ["Sincronizando relógio"] = "Syncing clock",
        ["Relógio errado causa falha de login, de certificado e de anti-cheat em jogos."] = "A wrong clock causes login, certificate and anti-cheat failures in games.",
        ["Relógio sincronizado com a internet"] = "Clock synced with the internet", ["Não foi possível sincronizar o relógio agora"] = "Couldn't sync the clock right now",
        ["Não foi possível sincronizar o relógio agora. Verifique a conexão."] = "Couldn't sync the clock right now. Check your connection.",
        ["Redefinir rede"] = "Reset network", ["Redefinir"] = "Reset", ["Redefinindo rede"] = "Resetting network",
        ["Reinicia Winsock e TCP/IP. Use quando nada mais funcionar; precisa reiniciar o PC."] = "Resets Winsock and TCP/IP. Use it when nothing else works; requires a restart.",
        ["Redefinir a rede? Configurações de IP fixo e de VPN podem precisar ser refeitas, e o PC precisa ser reiniciado em seguida."] = "Reset the network? Static IP and VPN settings may need to be redone, and the PC must be restarted afterwards.",
        ["Winsock reiniciado"] = "Winsock reset", ["Pilha TCP/IP reiniciada"] = "TCP/IP stack reset", ["Rede redefinida (reinicie o PC para concluir)"] = "Network reset (restart the PC to finish)",
    };

    private static readonly (Regex Regex, Func<Match, string> Build)[] GamingPatterns =
    {
        P(@"^(.+) — (Rápido e com foco em privacidade\.|Estável e disponível no mundo todo\.|Bloqueia domínios maliciosos conhecidos\.)$", m => $"{m.Groups[1].Value} — {Tr(m.Groups[2].Value)}"),
        P(@"^([\d.,]+) de ([\d.,]+) GB em uso$", m => $"{m.Groups[1].Value} of {m.Groups[2].Value} GB in use"),
        P(@"^Ativo desde (\S+) de (\S+)\. Ao terminar de jogar, desative para reiniciar os serviços e voltar ao plano de energia anterior\. Os programas fechados podem ser abertos de novo normalmente\.$", m => $"On since {m.Groups[1].Value} on {m.Groups[2].Value}. When you're done playing, turn it off to restart the services and go back to the previous power plan. Closed apps can be opened again normally."),
        P(@"^Plano de energia Qrz ativado \((\d+) configurações\)$", m => $"Qrz power plan activated ({m.Groups[1].Value} settings)"),
        P(@"^Fechado: (.+)$", m => $"Closed: {m.Groups[1].Value}"),
        P(@"^Pausado: (.+)$", m => $"Paused: {Tr(m.Groups[1].Value)}"),
        P(@"^Reiniciado: (.+)$", m => $"Restarted: {m.Groups[1].Value}"),
        P(@"^Não foi possível pausar (.+?): (.+)$", m => $"Could not pause {Tr(m.Groups[1].Value)}: {m.Groups[2].Value}"),
        P(@"^(\S+) não reiniciou agora; o Windows o inicia quando precisar\.$", m => $"{m.Groups[1].Value} didn't restart now; Windows starts it when needed."),
        P(@"^Modo Jogo ativado: (\d+) programa\(s\) fechado\(s\), (\d+) serviço\(s\) pausado\(s\)$", m => $"Game Mode on: {m.Groups[1].Value} app(s) closed, {m.Groups[2].Value} service(s) paused"),
        P(@"^Ryzen (\S+) detectado$", m => $"Ryzen {m.Groups[1].Value} detected"),
        P(@"^Perfil aplicado: (.+)\. Vale na próxima vez que o jogo abrir\.$", m => $"Profile applied: {m.Groups[1].Value}. Takes effect the next time the game opens."),
        P(@"^Perfil de jogo aplicado: (\S+) \((.+)\)$", m => $"Game profile applied: {m.Groups[1].Value} ({Tr(m.Groups[2].Value)})"),
        P(@"^Perfil de jogo removido: (.+)$", m => $"Game profile removed: {m.Groups[1].Value}"),
        P(@"^Instalando (.+)\.\.\.$", m => $"Installing {Tr(m.Groups[1].Value)}..."),
        P(@"^\[ERRO\] (.+): código (-?\d+)$", m => $"[ERROR] {Tr(m.Groups[1].Value)}: code {m.Groups[2].Value}"),
        P(@"^Runtimes: (\d+) instalado\(s\) ou já presente\(s\), (\d+) falha\(s\)$", m => $"Runtimes: {m.Groups[1].Value} installed or already present, {m.Groups[2].Value} failure(s)"),
        P(@"^DNS alterado para (.+) em (\d+) adaptador\(es\)$", m => $"DNS changed to {Tr(m.Groups[1].Value)} on {m.Groups[2].Value} adapter(s)"),
        P(@"^Alterando DNS para (.+)$", m => $"Changing DNS to {Tr(m.Groups[1].Value)}"),
        P(@"^DNS: (.+)$", m => $"DNS: {Tr(m.Groups[1].Value)}"),
        P(@"^Teste de velocidade falhou: (.+)$", m => $"Speed test failed: {m.Groups[1].Value}"),
        P(@"^Teste de velocidade: (.+)$", m => $"Speed test: {m.Groups[1].Value}"),
        P(@"^(.+) · (Cabo \(Ethernet\)|Wi-Fi)$", m => $"{m.Groups[1].Value} · {Tr(m.Groups[2].Value)}"),
    };
}
